### PR TITLE
Do not take singularity.conf defaults from current install

### LINKED ISSUE #2473: underlay disabled by default
## Version of Singularity:

Latest master branch

### Expected behavior

Expect the underlay option to be enabled

### Actual behavior

Underlay option is disabled by default

### Steps to reproduce behavior

Build an rpm and install it when there's no existing modified /etc/singularity/singularity.conf, so there's no singularity.conf.rpmnew.  Look at the 'enable underlay' option.

I took a quick look at the code and it seems that it should be on, but it isn't.

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

This PR removes /etc/singularity/singularity.conf from the input to newly built singularity.conf files, to avoid building into packages things that were set for testing purposes.

**This fixes or addresses the following GitHub issues:**

- Fixes #2473 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by DrDaveD** [comment]
An alternative would be to add another make variable, e.g. old_config, use it as the argument to gen.go, default its value to config_INSTALL, and set old_config= on the make command line inside singularity.spec.  Then it would only affect the rpm builds.  The disadvantage is that other packagings will have the same issue.

**Comment by DrDaveD** [comment]
Closing & reopening for travis which saw a download failiure.

**Comment by cclerget** [comment]
@DrDaveD As this is a feature to take the old config in order to apply old configured values to newly generated configuration file, I prefer the alternative you mentioned because the current fix breaks this feature. We can perfectly document this procedure for package maintainers.

**Comment by DrDaveD** [comment]
Ok @cclerget I updated this as you requested.

**Review by cclerget — APPROVED** [review]
Tested, looks good to me. Thanks @DrDaveD !

**Pull request merged**
