### PR TITLE
Consolidate namespace options

### PR DESCRIPTION
**Pull request by GodloveD**
**Description of the Pull Request (PR):**

Right now we have 5 different bools for all of the different namespaces that a user can join.  This PR consolidates them all into a single comma separated string.   

It also adds a few functions for to the util directory to work more efficiently with string arrays. 

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [user](https://www.github.com/sylabs/singularity-userdocs) and [administrator](https://www.github.com/sylabs/singularity-admindocs) documentation bases.
- [ ] I have tested this PR locally with a `make testall`
- [x] This PR is against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularity-maintainers

### CODE REVIEW

**Review by bauerm97 — CHANGES_REQUESTED** [review]
Don't have time to get to this yet, but this needs a few changes. I'll post a full review tonight or tomorrow

**Comment by bauerm97** [comment]
I would like to table this for 3.1. I think that with some work this could be a good change, but as it stands it needs more time than we have to implement before GA. Again, we can reassess this change moving into 3.1 and deprecate `--pid`, `--ipc`, etc... as needed.

**Comment by GodloveD** [comment]
Understood.  Moved it to the 3.1 release and off of the 3.0 release.

**Comment by GodloveD** [comment]
We're not going to do this.  So I'm closing 😺

**Pull request closed without merging**
