### PR TITLE
Remove prompt for dry run cache clean

### LINKED ISSUE #4225: 'cache clean --dry-run' is ignored
## Version of Singularity:

```
3.3.0-736.g2e524b566
```

### Expected behavior

`--dry-run` should not be interactive and should print what will be removed, imo.

```
$ singularity cache clean --dry-run
Would remove ...
```

### Actual behavior

```
$ singularity cache clean --dry-run
This will delete everything in your cache (containers from all sources and OCI blobs). 
Hint: You can see exactly what would be deleted by canceling and using the --dry-run option.
Do you want to continue? [N/y] 
```

WHAT?! I already specified the `--dry-run` flag! _seems to be ignored._

### Steps to reproduce behavior

```
$ singularity cache clean --dry-run
```

### PR DESCRIPTION
**Pull request by sashayakovtseva**
**Description of the Pull Request (PR):**

User will not be prompted if cache clean is running in a dry run mode.
Cache clean will always print names of removed entries. 

Flags `--verbose` and `--quiet` where not added. For extra verbosity one can use `-d` falg, for keeping things quiet one can redirect stdout to `/dev/null`.

Also, I didn't change output format as @GodloveD suggested b/c I think that needs further discussion. For example, 
```
$ singularity cache clean --force 
Singularity will remove the following container data:
lolcow_latest.sif        
lolcow_latest.sif        
lolcow_latest.sif       
3b61febd4aefe982e0cb9c  
73d5b1025fbfa138f2cacf  
7fac07fb303e0589b9c23e  
8e860504ff1ee5dc795367  
9d99b9777eb02b8943c0e7  
9fb6c798fa41e509b58bcc  
d010c8cf75d7eb5d2504d5  
f2a852991b0a36a9f3d6b2
```

`lolcow_latest.sif` is ambiguous, while full path to cache entry is not.

**This fixes or addresses the following GitHub issues:**

- Fixes #4225 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by WestleyK — APPROVED** [review]
Looks good to me :+1: This fixes the open issue. The other improvements like

>Flags --verbose and --quiet where not added.

_and improving the output of `cache clean`_

can probably be added in a separate PR (if we want to include them)

**Review by gvallee — CHANGES_REQUESTED** [review]
Could you please update the e2e tests so that the input to the command is removed? I can also do it separately if necessary.

**Review by gvallee — APPROVED** [review]
lgtm

**Review by GodloveD — APPROVED** [review]
This is a much improved workflow imho.

**Pull request merged**
