### PR TITLE
Development 3.0: Use golang package for user identity mapping

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Replace C functions by Golang `os/user` functions

### CODE REVIEW

**Comment by DrDaveD** [comment]
@bauerm97 asked me in #1846 to test this on rhel6 & 7, and I got the following compilation error messages on rhel6:
```
 GO singularity
# github.com/singularityware/singularity/src/pkg/build/assemblers
../src/pkg/build/assemblers/assembler_sif.go:52:16: parinput.SetPartExtra undefined (type sif.DescriptorInput has no field or method SetPartExtra)
../src/pkg/build/assemblers/assembler_sif.go:52:44: undefined: sif.PartPrimSys
../src/pkg/build/assemblers/assembler_sif.go:52:61: undefined: sif.GetSIFArch
../src/pkg/build/assemblers/assembler_sif.go:61:12: cannot assign 1 values to 2 variables
# github.com/singularityware/singularity/src/pkg/build/sources
../src/pkg/build/sources/packer_sif.go:52:22: fimg.GetPartPrimSys undefined (type sif.FileImage has no field or method GetPartPrimSys)
# github.com/singularityware/singularity/src/pkg/signing
../src/pkg/signing/signing.go:32:22: fimg.GetPartPrimSys undefined (type *sif.FileImage has no field or method GetPartPrimSys)
../src/pkg/signing/signing.go:46:22: fimg.GetPartPrimSys undefined (type *sif.FileImage has no field or method GetPartPrimSys)
../src/pkg/signing/signing.go:62:16: siginput.SetSignExtra undefined (type sif.DescriptorInput has no field or method SetSignExtra)
../src/pkg/signing/signing.go:152:22: fimg.GetPartPrimSys undefined (type sif.FileImage has no field or method GetPartPrimSys)
# github.com/singularityware/singularity/src/runtime/engines/singularity
../src/runtime/engines/singularity/container.go:393:23: fimg.GetPartPrimSys undefined (type sif.FileImage has no field or method GetPartPrimSys)
make: *** [singularity] Error 2
```

**Comment by bauerm97** [comment]
@DrDaveD I think that's probably an artifact of the PR that I just merged. Could you try `git clean -xfd` and then compiling again?

**Comment by DrDaveD** [comment]
That didn't help, I still get the same errors.  I first went to my master branch and made sure it was up to date, then did git rebase master on this PR branch, then did git clean -xfd before recompiling with these commands:
```
dep ensure -v
./mconfig
cd ./builddir
make 
```

**Comment by DrDaveD** [comment]
I also get the same errors on el7.

**Comment by yhcote** [comment]
Go 1.10 is a requirement, but I think you may able to get away with removing $GOPATH/pkg/ and duplicated $GOPATH/src/ folders.

**Comment by DrDaveD** [comment]
The problem was my dep ensure -v command which I got from INSTALL.md.   It modified Gopkg.lock.  Without that command, this builds OK on el6 and el7.

@yhcote On el6 I have golang-1.9.6-1.el6 from EPEL, and oddly on el7 it is slightly older golang-1.9.4-1.el7 but it doesn't seem to have caused me a problem yet.

**Comment by yhcote** [comment]
Perfect cheers!

**Review by bauerm97 — APPROVED** [review]
Looks good and fixes @DrDaveD problem!

**Pull request merged**
