### PR TITLE
Add makeit configure checks for ARM and AARCH64.

### PR DESCRIPTION
**Pull request by yhcote**
This patch enables the build for ARM and AARCH64 platforms.

### CODE REVIEW

**Review by jmstover — APPROVED** [review]

**Comment by jmstover** [comment]
Build/Run on 32bit ARM without issue.

**Review by dtrudg — CHANGES_REQUESTED** [review]
Fails to build on aarch64 pi64 distro...

```
pi@raspberrypi:~/go/src/github.com/singularityware/singularity/builddir$ go version
go version go1.10.4 linux/arm64
pi@raspberrypi:~/go/src/github.com/singularityware/singularity/builddir$ uname -r
4.11.12-pi64+
```

```
pi@raspberrypi:~/go/src/github.com/singularityware/singularity/builddir$ make
 CC src/runtime/c/lib/util/capability.c
 CC src/runtime/c/lib/util/message.c
 CC src/runtime/c/lib/util/setns.c
 AR src/runtime/c/lib/util/libutil.a
 CSCOPE
 DEPENDS
 AR lib/libruntime.a
 VENDORS
 GO singularity
# github.com/singularityware/singularity/src/pkg/instance
../src/pkg/instance/instance.go:244:12: undefined: syscall.Dup2
../src/pkg/instance/instance.go:247:12: undefined: syscall.Dup2
Makefile:211: recipe for target 'singularity' failed
make: *** [singularity] Error 2
```

Dup2 is not valid on arm64 - elsewhere, e.g. https://github.com/rfjakob/gocryptfs/issues/121

**Comment by dtrudg** [comment]
Also: https://github.com/golang/go/issues/11981

**Comment by jmstover** [comment]
@cclerget .... `syscall.Dup2()` not on aarch64.  Possible to change the two `syscall.Dup2()` calls in instance.go to `syscall.Dup3()` ?

**Comment by cclerget** [comment]
Yes no problem

**Comment by dtrudg** [comment]
With this diff:

```diff
diff --git a/src/pkg/instance/instance.go b/src/pkg/instance/instance.go
index 67655027..205b9340 100644
--- a/src/pkg/instance/instance.go
+++ b/src/pkg/instance/instance.go
@@ -241,10 +241,10 @@ func SetLogFile(name string) error {
        }
        defer stdout.Close()

-       if err := syscall.Dup2(int(stderr.Fd()), int(os.Stderr.Fd())); err != nil {
+       if err := syscall.Dup3(int(stderr.Fd()), int(os.Stderr.Fd()), 0); err != nil {
                return err
        }
-       if err := syscall.Dup2(int(stdout.Fd()), int(os.Stdout.Fd())); err != nil {
+       if err := syscall.Dup3(int(stdout.Fd()), int(os.Stdout.Fd()), 0); err != nil {
                return err
        }

```

It does build and work on aarch64:

```
pi@raspberrypi:~$ singularity build ubuntu.sif docker://aarch64/ubuntu
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
Getting image source signatures
Skipping fetch of repeat blob sha256:8944e166ce98dea9683e8774c236d487bcf684ad7ea34d9473a1841f724c32e9
Skipping fetch of repeat blob sha256:1f8c28d8b7a97d328272b79aa79c3f67b3392095073608fa6d27ef8edfd505fb
Skipping fetch of repeat blob sha256:9dbf9f348171f915235ded5ba3f3621688d2b5146ec51b405b5ea94958958754
Skipping fetch of repeat blob sha256:5cb9db57901bbdd8bc746e3c6ffe4da8bb53e7a34a4bacd8da99c6d0ed34ff3d
Skipping fetch of repeat blob sha256:7e21759f0cbfc6cd21a27ebe4c5122648b134770cb12637f51589a5d188063af
Copying config sha256:e7096a79fbfe677e12c216134ee6d20e845bdf0db334754f1119643d7c0c3df5
 2.60 KiB / 2.60 KiB [======================================================] 0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete!
pi@raspberrypi:~$ singularity shell ubuntu.sif
Singularity ubuntu.sif:~> cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=16.04
DISTRIB_CODENAME=xenial
DISTRIB_DESCRIPTION="Ubuntu 16.04.1 LTS"
Singularity ubuntu.sif:~> uname -r
4.11.12-pi64+
Singularity ubuntu.sif:~> uname -a
Linux raspberrypi 4.11.12-pi64+ #1 SMP PREEMPT Sun Jul 30 20:18:20 CEST 2017 aarch64 aarch64 aarch64 GNU/Linux
Singularity ubuntu.sif:~> exit
```

**Review by dtrudg — APPROVED** [review]

**Comment by dtrudg** [comment]
Confirmed build, runtime works. Signing/verification flow works. AARCH64.

**Pull request merged**
