### PR TITLE
Pass --no-cleanup flag pull command

### PR DESCRIPTION
**Pull request by ikaneshiro**
Fixes issue with pulls always cleaning up the underlying build performed
to convert docker images to SIF

Signed-off-by: Ian Kaneshiro <iankane@umich.edu>

### CODE REVIEW

**Review by jmstover — APPROVED** [review]

**Comment by jmstover** [comment]
LGTM, though this wouldn't keep the `fs` directory from being removed correct?

**Comment by ikaneshiro** [comment]
@jmstover This should preserve that, it being cleaned up on mac could still be an issue

**Comment by jmstover** [comment]
> it being cleaned up on mac could still be an issue

So it... doesn't preserve it then?

**Comment by gvallee** [comment]
@jmstover @ikaneshiro is it ready to merge? or do you need more time for discussions? thanks

**Comment by jmstover** [comment]
IMO, this can be merged. If there's still a problem, it can be dealt with
later on.

-J

**Pull request merged**
