### PR TITLE
Read inspect metadata from inspect-metadata.json SIF descriptor

### LINKED ISSUE #4279: Image metadata should be stored in its own partition
## Version of Singularity:

```
v3.3
```

### Expected behavior

The container information (like labels) should be stored it its own partition, not just some files in `.singularity.d/`.

### Actual behavior

Right now, container information is stored in some file.

 - Related to: https://github.com/sylabs/singularity/issues/3932

### Steps to reproduce behavior

Write here.

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Rely on #5136

### This fixes or addresses the following GitHub issues:

 - Fixes #4279

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by dtrudg — COMMENTED** [review]
This looks pretty fair to me coupled with #5136 - let's pause a little for some discussion points raised there though, before merging.

**Comment by dtrudg** [comment]
Discussion for 3.7 taking place from https://github.com/hpcng/singularity/pull/5136#issuecomment-669228245 onward

**Comment by dtrudg** [comment]
Hi @cclerget - this is on the 3.7 roadmap still I believe. Do you want to rebase and we can all go over the PR now?

**Comment by cclerget** [comment]
Both have been rebased

**Review by dtrudg — APPROVED** [review]
This looks good to me - I'm more concerned with the path forward for the other side of the metadata changes in #5136 - i.e. what's the path toware moving to having the SIF inspect data as the initial & sole metadata source... not writing stuff into the container and then copying it into the SIF.

**Pull request merged**
