### PR TITLE
urlparse bug in Python 2.6

### PR DESCRIPTION
**Pull request by hra0031**
**Description of the Pull Request (PR):**

Function urlparse is buggy in Python 2.6 https://bugs.python.org/issue754016. If a Docker Image is on repository with nondefault port e.g. docker://testdomain.cz:5000/ this function return "testdomain.cz" as scheme.

**This fixes or addresses the following GitHub issues:**

- Ref: #724

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [Author's file](https://github.com/singularityware/singularity/blob/master/AUTHORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
haha, I am a doop, I missed this earlier! The funny thing about it is that I used re in a much earlier version, and someone else insisted on urlparse. It looks like we are back to re!

I think PRs to master are reserved for releases, and we need to do this to development. @gmkurtzer is that correct?

**Comment by hra0031** [comment]
Sorry for the master branch. I'm working on some projects right now where I push directly to master... my fault.

**Comment by vsoch** [comment]
No worries! I'm really glad that you caught this. It took me a while to get an old python to reproduce it, and you are completely right it's an issue.

**Comment by gmkurtzer** [comment]
Yes @vsoch, the master branch is for releases and bug fixes only. Given that this is a bug fix, we can merge it directly iff it is affecting people directly now and if it has been tested, stable and reviewed. But in a nutshell, yes, everything should generally go through the development branch.

**Comment by vsoch** [comment]
ok I'm good to merge then. I can't test but it looks like it passes tests and the changes are very clean and logical.

**Comment by gmkurtzer** [comment]
Thanks!

**Pull request merged**
