### PR TITLE
Update CHANGELOG.md

### PR DESCRIPTION
**Pull request by BenisonSebastian**
**Description of the Pull Request (PR):**

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

**This fixes or addresses the following GitHub issues:**

- Fixes #

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by sashayakovtseva** [comment]
Sorry, what is the point of your change? As I can see you removed all formatting, but I don't see any benefits here...

**Review by mem — CHANGES_REQUESTED** [review]
It looks like this was accidentally uploaded. Sebastian, can you confirm?

**Comment by BenisonSebastian** [comment]
Well, the aim was to make it a bit more grammatically apt. That's all. Hope
it is fine.

**Comment by mem** [comment]
> Well, the aim was to make it a bit more grammatically apt. That's all. Hope it is fine.

Thanks!

I think the confusion is coming from the fact that file is a markdown file, and the proposed change is stripping all the markdown markup (which we want to keep :smile:). By chance, did you copy-paste from a markdown viewer or editor or something like that?

**Comment by GodloveD** [comment]
Hiya @BenisonSebastian.  Thanks very much for taking the time to submit this PR and attempt to help us improve the documentation for Singularity.  

Unfortunately, as @sashayakovtseva and @mem have pointed out, this change is a bit confusing to us.  We want to keep the markdown in the `.md` files because it allows them to be [displayed nicely](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md).

So while we appreciate the effort you put into this, I'm afraid we will respectfully decline to merge the PR.  But please feel free to submit future PRs and/or raise issues and we will consider them in turn.

Thanks!  😄

**Pull request closed without merging**
