### PR TITLE
Remove environment.tar

### PR DESCRIPTION
**Pull request by tri-adam**
**Description of the Pull Request (PR):**

Remove `environment.tar` and instead generate the equivalent files programatically.

Tests have been added for the new environment generation code. I have manually `diff -r`'dd the contents of `environment.tar` against the structure generated by `makeBaseEnv` and verified them to be to be identical.

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by tri-adam** [comment]
In addition to unit test, tested E2E. Cleaned `/usr/local/libexec/singularity/` (just to make sure), did a `make install`, then:

```
adam@ubuntu18:~/go/src/github.com/singularityware/singularity$ singularity build alpine.img docker://alpine
Getting image source signatures
Copying blob sha256:ff3a5c916c92643ff77519ffa742d3ec61b7f591b6b7504599d95a4a41134e28
 1.97 MiB / 1.97 MiB [======================================================] 0s
Copying config sha256:b1a7f144ece0194921befe57ab30ed1fd98c5950db7996719429020986092058
 585 B / 585 B [============================================================] 0s
Writing manifest to image destination
Storing signatures
Parallel mksquashfs: Using 4 processors
Creating 4.0 filesystem on /tmp/squashfs-496489330.img, block size 131072.
[=================================================================|] 99/99 100%

Exportable Squashfs 4.0 filesystem, gzip compressed, data block size 131072
	compressed data, compressed metadata, compressed fragments, compressed xattrs
	duplicates are removed
Filesystem size 1957.59 Kbytes (1.91 Mbytes)
	47.94% of uncompressed filesystem size (4083.20 Kbytes)
Inode table size 3141 bytes (3.07 Kbytes)
	17.59% of uncompressed inode table size (17854 bytes)
Directory table size 4636 bytes (4.53 Kbytes)
	55.05% of uncompressed directory table size (8421 bytes)
Number of duplicate files found 6
Number of inodes 496
Number of files 75
Number of fragments 4
Number of symbolic links  332
Number of device nodes 0
Number of fifo nodes 0
Number of socket nodes 0
Number of directories 89
Number of ids (unique uids + gids) 1
Number of uids 1
	adam (1000)
Number of gids 1
	adam (1000)


Build Succeeded
adam@ubuntu18:~/go/src/github.com/singularityware/singularity$ singularity run alpine.img
Singularity> 
Singularity> quit
```

**Review by dtrudg — COMMENTED** [review]
This seems complete, but I'm not really a big fan of having each of the scripts as a const in a single file.

1 - it's quite hard to find the boundaries of each scripts if you are just skimming through, and not in a  decent Golang IDE

2 - I think things like 90-environment.sh are appended to later on. These could really make use of golang's inbuilt templating functions to give a nice insertion point so their content can be nicely managed by a function that can be called with the envs to be injected.

**Review by ArangoGutierrez — APPROVED** [review]
LGTM

**Comment by bauerm97** [comment]
@dctrud We are going to merge this PR now, and @tri-adam will make a note for us to circle back to your comments a bit further down the line. For now this is a good starting point and will solve some headaches for external projects.

**Pull request merged**
