### PR TITLE
Grab all inspect metadata and add them as a SIF descriptor.

### LINKED ISSUE #4279: Image metadata should be stored in its own partition
## Version of Singularity:

```
v3.3
```

### Expected behavior

The container information (like labels) should be stored it its own partition, not just some files in `.singularity.d/`.

### Actual behavior

Right now, container information is stored in some file.

 - Related to: https://github.com/sylabs/singularity/issues/3932

### Steps to reproduce behavior

Write here.

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Grab all inspect metadata and add them as a SIF descriptor.

### This fixes or addresses the following GitHub issues:

 - Fixes #4279

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by dtrudg — COMMENTED** [review]
Hi @cclerget. In principle I'm okay with brining the existing style of script metadata into the SIF descriptor like this as a first stepping stone toward getting things out of the rootfs.

What I'd like to do, though is wait on this a little bit until @EmmEff has some available to discuss how the library might consume metadata to enhance the UX, and @tri-adam has some valuable time to think about the road toward more OCI compatibility. I'm not sure whether we migrate slowly from here towards an `oci-config.json` with some implementation specific additions, or something else. Would be good to have at least a bit more thought on this I think.

**Comment by dtrudg** [comment]
@cclerget - probably a good time to circle back on this one now. I'm definitely still of the opinion that capturing the metadata like this in the SIF is a win for inspecting without needing to mount the rootfs. That's good for Singularity and any other tools.

Looking forward though, are there any plans on your side to be moving more toward OCI driven metadata format etc? My only real concern is that if this is inspect JSON format is a stepping stone, and would be short lived, then we need to consider a path for transition of anything that might start consuming it.

**Comment by cclerget** [comment]
@dctrud Regarding OCI compatibility, you are thinking about a fit with https://github.com/opencontainers/image-spec/blob/79b036d80240ae530a8de15e1d21c7ab9292c693/specs-go/v1/config.go#L24 ?

**Comment by dtrudg** [comment]
@cclerget - yeah, something like that. I don't know if that's a long term plan though? On the roadmap draft doc I've left a space for @gmkurtzer to indicate long-term aims. It would be good if we could get an idea of if there is an intent to do more OCI work so we can think about metadata in that context.

There are probably good reasons that we can't be 100% OCI compatible by default, due to the security model etc, and that's fine. It'd just be good to have a bit of an idea of where GMK thinks the project should be aiming over coming releases.

**Comment by dtrudg** [comment]
Hi @cclerget - this is on the 3.7 roadmap still I believe. Do you want to rebase and we can all go over the PR now?

**Review by dtrudg — COMMENTED** [review]
I'm good with this code in theory - but can we still get a little bit more information about the direction embedded metadata might take before we merge this? I'm keen to know where we are going if this is an intermediate step.

Ultimately... are we going to have the descriptor as a primary source of metadata, and inject files it in the container at runtime if needed?

**Comment by cclerget** [comment]
> Ultimately... are we going to have the descriptor as a primary source of metadata, and inject files it in the container at runtime if needed?

Like this is done actually injection is not possible, the descriptor just reflect the image content to ease inspection without extraction steps, the primary source during runtime remains the image. Is injection something guys want/need ?

**Comment by dtrudg** [comment]
> > Ultimately... are we going to have the descriptor as a primary source of metadata, and inject files it in the container at runtime if needed?
> 
> Like this is done actually injection is not possible, the descriptor just reflect the image content to ease inspection without extraction steps, the primary source during runtime remains the image. Is injection something guys want/need ?

It's not something I thought was urgent. I just remember that @gmkurtzer was keen to move metadata out of the container in past discussion - so wanted to check if it's something that you or other Ctrl-Cmd folks were thinking about pushing forward with.

Given there isn't a strong path forward, but this enables reasoning about a container without having to mount an fs it's likely quite useful for tools that might work with singularity containers. I think we can merge at this point.

**Review by dtrudg — APPROVED** [review]

**Pull request merged**
