### PR TITLE
Use cobra --version flag

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
**Description of the Pull Request (PR):**

as requested by @GodloveD 

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by GodloveD** [comment]
Travis seems to be having some trouble building this.   😕

**Review by GodloveD — APPROVED** [review]
Ugh. Freaking Cobra! Why does it feel that it's necessary to prepend the version number with the name of the program and the word "version"?
```
09:50 PM 
ubuntu ~/go/src/github.com/singularityware/singularity/builddir
$ ./singularity version
3.0.0-version_flag.117d73c1

09:57 PM 
ubuntu ~/go/src/github.com/singularityware/singularity/builddir
$ ./singularity --version
singularity version 3.0.0-version_flag.117d73c1
```
I'm going to approve this because it's an improvement over the current situation.  But it would be nice of the `--version` flag returned something more sensible.  Don't know if it should be a priority right now when we have so much other stuff to do.

**Comment by ArangoGutierrez** [comment]
Hit it @GodloveD , when you feel to

**Comment by GodloveD** [comment]
Consider it hit @ArangoGutierrez !

**Pull request merged**
