### PR TITLE
adding size and consistent scif  env naming

### LINKED ISSUE #946: docker pull errors with missing --size option
## Version of Singularity:

2.3.2

### Expected behavior

should pull the image and provide an error that's usable. `--size` is not an option for the pull command.

### Actual behavior

```
$ singularity pull docker://debian:stretch                                               
ERROR: Could not obtain the container size, try using --size                                                          ABORT: Aborting with RETVAL=255
```

### Steps to reproduce behavior

use command above.

### PR DESCRIPTION
**Pull request by vsoch**
**Description of the Pull Request (PR):**

This will close #946 

Attn: @singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
And here is what the finished environment looks like, when running app "foo"

```
Singularity app.img:~/Desktop> env | grep APP

SINGULARITY_APPNAME=foo
SINGULARITY_APPMETA=/scif/apps/foo/scif
SINGULARITY_APPDATA=/scif/data/foo
SINGULARITY_APPINPUT=/scif/data/foo/input
SINGULARITY_APPROOT=/scif/apps/foo
SINGULARITY_APPOUTPUT=/scif/data/foo/output
SINGULARITY_APPS=/scif/apps

Singularity app.img:~/Desktop> env | grep DATA
SINGULARITY_DATA=/scif/data
SINGULARITY_APPDATA=/scif/data/foo
```

Changes include:

 - `SINGULARITY_APPBASE` changed to SINGULARITY_APPROOT`
 - `SINGULARITY_DATA` added to indicate the containers base for all app data (/scif/data)
 -  `SINGULARITY_APPS` added to indicate the container's base for all apps

**Comment by vsoch** [comment]
This will also close #948 

@gmkurtzer ready for review and merge (another tiny PR - they are much quicker / cleaner / easier I'm finding!)

**Comment by GodloveD** [comment]
Do you want to go ahead and document the `-F/--force` option while you are at it?

**Comment by vsoch** [comment]
you got it!

**Comment by vsoch** [comment]
@GodloveD I was talking with @gmkurtzer about adding environment variable exports for all apps, to be present and accessible when any are running. For example, if I run:

```
singularity exec --app foo container.img
```

I would have a wide set of environment variables about foo, but not bar. If I wanted to do something simple like call an executable from bar, or get the data output from it, it would be useful to have:

```
SINGULARITY_APPROOT_BAR
SINGULARITY_APPDATA_BAR
```

And of course the names / which environment variables are included is up for discussion! What are  your thoughts?

**Comment by gmkurtzer** [comment]
Haha, you guys are a riot! Is this ready to merge?

**Comment by GodloveD** [comment]
I think it is good to go.  After playing some with the SCI-F concept and getting my head around it I think it's a great idea to have the env vars ready for users.

**Comment by vsoch** [comment]
ok, when this passes we should be good! here is what it adds, for example, for cowsay (the section at the top):

```
singularity exec --app cowsay cowsay.img env | grep APP

# Relevant to all apps installed, including those not active
APPDATA_cowsay=/scif/data/cowsay
APPROOT_cowsay=/scif/apps/cowsay
APPDATA_fortune=/scif/data/fortune
APPROOT_fortune=/scif/apps/fortune
APPDATA_lolcat=/scif/data/lolcat
APPROOT_lolcat=/scif/apps/lolcat

SINGULARITY_APPS=/scif/apps
(note we also have this, which doesn't appear in the grep)
SINGULARITY_DATA=/scif/data

# Relevant to running app (cowsay)
SINGULARITY_APPOUTPUT=/scif/data/cowsay/output
SINGULARITY_APPDATA=/scif/data/cowsay
SINGULARITY_APPINPUT=/scif/data/cowsay/input
SINGULARITY_APPROOT=/scif/apps/cowsay
SINGULARITY_APPNAME=cowsay
SINGULARITY_APPMETA=/scif/apps/cowsay/scif
```

**Comment by vsoch** [comment]
@gmkurtzer ready for review!

**Comment by gmkurtzer** [comment]
Looks, great... THANKS!

**Pull request merged**
