### PR TITLE
changing pull to a wrapper for build (docker hub)

### PR DESCRIPTION
**Pull request by GodloveD**
**Description of the Pull Request (PR):**

Because `import` and `export` no longer escalate privs, `pull` from Docker Hub no longer works properly as a non-privileged user.  You can now `build` from Docker Hub rendering the `pull` command obsolete, and it uses a slightly different method.  Instead of importing a tar pipe into a pre-made image, build unpacks to a temporary directory and then uses `mksquashfs` to create an image.  This path results in fewer errors when used by a non-prived user.  

So this PR will deprecate pull from docker by making it a wrapped build command instead.  The only trade-off is that images built from Docker Hub will now be squashfs instead of writable image format.  But this is what we want anyway.  If a user wants to convert the squashfs image to writable they can also do that with the build command, but will need to be root. 

**This fixes or addresses the following GitHub issues:**

- Ref: #977

**Checkoff for all PRs:**

✅  I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
:white_check_mark: I have tested this PR locally with a `make test`
:white_check_mark:  This PR is NOT against the project's master branch
:white_check_mark:  have added myself as a contributor to the [Author's file](https://github.com/singularityware/singularity/blob/master/AUTHORS.md)
:white_check_mark: This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
So currently this gives a warning but doesn't prevent it? Might make sense to change this line too:

```
 message ERROR "pull is only supported for docker and shub URIs\n"
```
This is definitely not going to be taken well, I think we need to still have support for pull for this release, get up the next version of singularity hub, and then only remove it when singularity hub / registry can meet the need of a non sudo pull. I'm treading lightly around this one because it's an explosion waiting to happen...boum!

**Comment by bauerm97** [comment]
@vsoch I think you are misreading the error message and code combination. The error "pull is only supported for docker and shub URIs\n" only is shown when the user enters an invalid URI (i.e. not a shub or docker URI).

**Comment by vsoch** [comment]
Are you sure? It  used to be that, and now it just lists "shub". I think it was changed since I commented. But whatever,  I don't care.

**Comment by gmkurtzer** [comment]
Looks good, thanks!

**Pull request merged**
