### PR TITLE
Propagate proxy environment variables for e2e tests

### LINKED ISSUE #5651: e2e-tests will need to be modified so that the proxy environment is set.
### Version of Singularity:

```
$ singularity version
singularity version 3.6.3
```

### Expected behavior

E2e-test passes even in Proxy environment.

### Actual behavior

This issue is about support for e2e testing in a proxy environment.

When the system-wide HTTP_PROXY environment variable was set outside the test code, about 95 tests failed.
<pre>
  $ export HTTP_PROXY=http://xxxx:xxxx@rep.proxy.nic.com:xxxx
  $ export HTTPS_PROXY=http://xxxx:xxxx@rep.proxy.nic.com:xxxx
  $ SINGULARITY_E2E=1 make -C builddir e2e-test > singularity_e2e-test.external.log
</pre>
  Please refer to the attached singularity_e2e-test.external.log for details.

When the HTTP_PROXY environment variable was set inside the test code, fail decreased 90.
<pre>  
$ git diff
  diff --git a/e2e/e2e.go b/e2e/e2e.go
  index ca5072cd2..413134808 100644
  --- a/e2e/e2e.go
  +++ b/e2e/e2e.go
  @@ -7,10 +7,14 @@ package e2e

   import (
          "testing"
  +       "os"
   )

   // RunE2ETests is the main func to trigger the test suite.
   func RunE2ETests(t *testing.T) {
  +       // Set the system-wide proxy IP to the http(s)_proxy environment variable.
  +       os.Setenv("http_proxy", "http://id:pass@rep.proxy.nic.com:port")
  +       os.Setenv("https_proxy", "http://id:pass@rep.proxy.nic.com:port")
          t.Log("Running E2E tests for Singularity")
          Run(t)
   }
  $
</pre>
<pre>
  $ SINGULARITY_E2E=1 make -C builddir e2e-test > singularity_e2e-test.internal.log
</pre>
  Please refer to the attached singularity_e2e-test.internal.log for details.

The following 5 cases are still FAIL, but I don't know why.
<pre>
  TestE2E/PAR/ENV/environment_manipulation
  TestE2E/PAR/ACTIONS/shell/ShellHostname
  TestE2E/PAR/DOCKER/registry
  TestE2E/PAR/INSTANCE/issue_5033
  TestE2E/PAR/BUILD/issue_5172
</pre>
[singularity_e2e-test.external.log](https://github.com/hpcng/singularity/files/5427492/singularity_e2e-test.external.log)
[singularity_e2e-test.internal.log](https://github.com/hpcng/singularity/files/5427493/singularity_e2e-test.internal.log)

P.S.
The test to access oras registry fails because we do not have an oracle account.

### Steps to reproduce this behavior

Run e2e-test on Proxy required system.
$ git clone https://github.com/sylabs/singularity.git
$ cd singularity
$ git checkout v3.6.3
$ ./mconfig
$ cd builddir
$ make
$ cd ../
$ export HTTP_PROXY=http://xxxx:xxxx@rep.proxy.nic.com:xxxx
$ export HTTPS_PROXY=http://xxxx:xxxx@rep.proxy.nic.com:xxxx
$ SINGULARITY_E2E=1 make -C builddir e2e-test
 

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="Red Hat Enterprise Linux"
VERSION="8.2 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.2"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.2 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.2:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.2
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.2"

```

### How did you install Singularity
<pre>
$ git clone https://github.com/sylabs/singularity.git
$ cd singularity
$ git checkout v3.6.3
$ ./mconfig
$ cd builddir
$ make
# make install
</pre>

### PR DESCRIPTION
**Pull request by cclerget**
### This fixes or addresses the following GitHub issues:

 - Fixes #5651

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by dtrudg** [comment]
@TomokiUemoto  - are you able to test this change?

@cclerget - It might be worth propagating "ALL_PROXY", and "NO_PROXY" while we are at it here. Here is what singularity itself is passing r.e. proxy vars:

https://github.com/hpcng/singularity/blob/e417948a55cacb4167530ae1246dfe4f705dc816/internal/pkg/util/env/clean.go#L24

**Comment by cclerget** [comment]
@dctrud Fixed

**Comment by dtrudg** [comment]
@cclerget :+1: - believe this should work. I'd like to get confirmation from @TomokiUemoto though.

There *may* be an issue with the fact we use `wget` in an alpine based docker registry container, and the default `wget` (from busybox) might not work correctly with https proxying. This was an old issue I'm aware of, but I'm not sure if it got fixed in alpine.

See e.g.: https://gitlab.com/gitlab-org/gitlab-ci-yml/-/merge_requests/197

**Comment by cclerget** [comment]
@dctrud I added those checks and disabled proxy for localhost :

```
if [ -n "$ALL_PROXY" -o -n "$HTTP_PROXY" -o -n "$HTTPS_PROXY" ]; then
    no_proxy_default="127.0.0.1,localhost,::1"
    if [ -z "$NO_PROXY" ]; then
        NO_PROXY=$no_proxy_default
    else
        NO_PROXY="$no_proxy_default,$NO_PROXY"
    fi
fi
```

For `wget`, we could replace it by curl if necessary

**Comment by dtrudg** [comment]
> For `wget`, we could replace it by curl if necessary

Yeah - either that, or you can install the apk of wget... which gets the full GNU wget, not the busybox version.

**Comment by cclerget** [comment]
Seems to work, `wget` is only used in registry image :
```
$ singularity shell docker://registry:2.7.1
Singularity> HTTP_PROXY=http://localhost:8888 HTTPS_PROXY=http://localhost:8888 wget https://www.google.com
Connecting to www.google.com (216.58.215.36:443)
saving to 'index.html'
index.html           100% |*********************************************************************************************************| 13692  0:00:00 ETA
'index.html' saved
```

**Review by dtrudg — APPROVED** [review]

**Pull request merged**
