### PR TITLE
Singularity remote command enhancements

### LINKED ISSUE #5540: Proposal: Remote service management
# Remote services management

This a follow up and proposal regarding discussions about changes introduced by #5445 and #5464 in order to allow users/admins to define additional services for managing them through `singularity remote`.

An idea brought up by Adam Hughes (https://github.com/hpcng/singularity/pull/5464#pullrequestreview-460923370) involves expanding the `singularity remote` command group to support keyserver overrides. We generally agree with this assessment for both the registry credential management as well as the key service, and potentially future remote service options. We think this idea is worth discussion beyond just the keyserver use case as it gives us the opportunity to standardize the way Singularity interacts with all external service configurations within a single command group.

## Singularity remote proposal

Here a proposal to manage detached services, a detached service wouldn't be tight to any particular endpoint and would be available as long it is not removed explicitly:

```
// Add an SCS endpoint
singularity remote add [-g] <endpoint_name> <hostname>
// Add a keyserver to override SCS endpoint keystore
singularity remote add [-g] keyserver://<service_name> <hostname>
// Add oci registry
singularity remote add oci://<service_name> <hostname>

// List configured SCS endpoints
singularity remote list
// List configured keyserver override
singularity remote list keyserver
// List configured oci registry hostnames
singularity remote list oci

// Ping SCS endpoint for service statuses
singularity remote status
// Ping keyserver for status
singularity remote status keyserver
// Ping oci registry for status
singularity remote status oci

// Remove an SCS endpoint
singularity remote remove [-g] <endpoint_name>
// Remove a keyserver override
singularity remote remove [-g] keyserver://<service_name>
// Remove oci registry
singularity remote remove oci://<service_name>

// Authenticate with SCS endpoint
singularity remote login [--username|--password|--password-stdin|--insecure] <endpoint_name>
// Authenticate with keyserver (if applicable)
singularity remote login [--username|--password|--password-stdin|--insecure] keyserver://<service_name>
// Authenticate with OCI registry
singularity remote login [--username|--password|--password-stdin|--insecure] oci://<service_name>

// Set remote used by default
singularity remote use [-g] <endpoint_name>
```

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

- Two subcommands have been added for managing keyservers (globally only):
  - `add-keyserver` with two options:
    - `--order`: to define the order of the keyserver (1 is the primary
keyserver)
    - `--insecure`: to allow to connect to insecure keyserver (like no
valid TLS certificate)
  - `remove-keyserver` to remove a custom keyserver

- Login subcommand now support multiple scheme authentication to allow to
authenticate to Docker/OCI registries and custom keyservers in addition
to the remote endpoint.

- `remote logout` has been added to remove credentials stored by `remote
login`.

- `--exclusive` option has been added to `remote use` in order to allow
administrator to lock remote usage to a specific remote.

CLI remote code has been cleanup in order to centralize the way we get
remote configuration for various endpoints.

### This fixes or addresses the following GitHub issues:

- Fixes #5540 
- Related to #5445 and #5464

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by dtrudg** [comment]
Hi @cclerget - initial thoughts on the UX... I haven't gone through the code yet.

### remote list

```
dave@ythel~/G/singularity> singularity remote list
Cloud Services Endpoints
========================

NAME           URI                       GLOBAL  EXCLUSIVE
[SylabsCloud]  cloud.sylabs.io           YES     NO
local          cloud.k8s.randomroad.net  NO      NO

Keyservers
==========

URI                     GLOBAL  INSECURE  ORDER
https://keys.sylabs.io  YES     NO        1*

* Active cloud services keyserver

Service's credentials
=================================

URI                 INSECURE
docker://docker.io  NO
```

1. Not a critique of your work, but while we are changing the `remote list` command it's probably a good time to modify the way that the in-use cloud service endpoint is shown. I don't think `[....]` is very clear. Maybe a column that denotes ACTIVE would be better.

2. The `Service's credentials` header might be better as soemthing like `Authenticated Logins`, or something else that better shows these belong to the `login/logout` pairing of commands?

3. If my active endpoint is down then I'm seeing an ugly fatal when it tries to list the keyservers portion of the output. This should probably be caught, and skipped over / shown offline?

```
dave@ythel~/G/singularity> singularity remote list
Cloud Services Endpoints
========================

NAME         URI                       GLOBAL  EXCLUSIVE
SylabsCloud  cloud.sylabs.io           YES     NO
[k8s]        cloud.k8s.randomroad.net  YES     YES
local        cloud.k8s.randomroad.net  NO      NO
FATAL:   error making request to server: Get https://cloud.k8s.randomroad.net/assets/config/config.prod.json: dial tcp 192.168.1.240:443: connect: no route to host
```

### remote login

If I forget the `docker://` transport, I'm asked for my details before I get told it's not supported, and the error message pulls out the hostname as the transport:

```
singularity remote login -u xxxxxx docker.io
Password (or token when username is empty): 
FATAL:   while login to docker.io:  transport is not supported
```


If I don't use `-u` then I get:


```
singularity remote login docker://docker.io
Password (or token when username is empty): 
```

The above is a bit confusing to me as without any flags, `docker login` and similar tools will ask me for a username by default. The prompt could also say `Password` when user is provided, or `token` when not to avoid confusion over those?

### exclusive

This flag is maybe a bit confusing. The help doesn't say it is root only, or only for global endpoints. If I try to set an exclusive remote as a normal user:

```
singularity remote use --exclusive local
FATAL:   -e/--exclusive requires --global/-g
```

Can `--exclusive` just infer `--global` and directly say only the root user can set it?

Very minor comment...

```
dave@ythel~/G/singularity> singularity remote use local
FATAL:   could not use local: remote SylabsCloud is set to exclusive
```

I'd probably word this as `could not use local: remote SylabsCloud has been set exclusive by the system administrator` ... so it's clear it's a system administrator thing and users won't sit there wondering if there is some other setting they can adjust themselves.

**Comment by dtrudg** [comment]
Something else which I think is important to consider here is around the messaging when we start having remotes being able to be set `exclusive`, and showing ordered keyservers etc. They aren't really ever exclusive currntly as we can always override with command flags later. This might be intended, but maybe it's reasonable that an admin would assume setting a remote `exclusive` means users can't pull things from other locations? Messaging and docs are important. Would you be able to open a userdocs PR in parallel to this work? I think it's important they docs would be merged for these changes pretty swiftly.

E.g. do you intend that the `--library` flag can be a workaround for a remote set to exclusive? I have set the main SylabsCloud as exclusive here, but I can still pull from another location with `--library` provided to pull.

```
dave@ythel~/G/singularity> singularity remote list
Cloud Services Endpoints
========================

NAME           URI                       GLOBAL  EXCLUSIVE
[SylabsCloud]  cloud.sylabs.io           YES     YES
k8s            cloud.k8s.randomroad.net  YES     NO
local          cloud.k8s.randomroad.net  NO      NO

Keyservers
==========

URI                     GLOBAL  INSECURE  ORDER
https://keys.sylabs.io  YES     NO        1*

* Active cloud services keyserver

Service's credentials
=================================

URI                 INSECURE
docker://docker.io  NO
dave@ythel~/G/singularity> singularity pull --library https://library.staging.sylabs.io library://dtrudg-sylabs-2/multiarch/alpine
INFO:    Downloading library image
2.6MiB / 2.6MiB [============================================================================] 100 % 9.8 MiB/s 0s
WARNING: integrity: signature not found for object group 1
WARNING: Skipping container verification
```


And I can pull keys from places other than anything listed in `remote list` even if a remote is set exclusive etc.

```
dave@ythel~/G/singularity> singularity remote list
Cloud Services Endpoints
========================

NAME           URI                       GLOBAL  EXCLUSIVE
[SylabsCloud]  cloud.sylabs.io           YES     YES
k8s            cloud.k8s.randomroad.net  YES     NO
local          cloud.k8s.randomroad.net  NO      NO

Keyservers
==========

URI                     GLOBAL  INSECURE  ORDER
https://keys.sylabs.io  YES     NO        1*

* Active cloud services keyserver

Service's credentials
=================================

URI                 INSECURE
docker://docker.io  NO
dave@ythel~/G/singularity> singularity key search -u https://keys.staging.sylabs.io david
Showing 1 results

KEY ID    BITS  NAME/EMAIL
EC8409BD  4096  David C. Trudgian (Development Keys) <david.trudgian@sylabs.io>  

dave@ythel~/G/singularity> singularity key pull -u https://keys.staging.sylabs.io EC8409BD
1 key(s) added to keyring of trust /home/dave/.singularity/sypgp/pgp-public
```

**Comment by cclerget** [comment]
Thanks for the review @dctrud , I will apply fixes shortly. Regarding exclusive, I tend to think that specifying alternative library/builder/keyserver should be denied when exclusive is set, so I will fix that too. Yes I will write some doc about those changes

**Review by dtrudg — APPROVED** [review]
@cclerget - thanks for taking on board the input from all sides. I'm pretty happy we're at a good point with this to merge what is here now, and address anything else as 3.7 is worked up further.

Have discussed with @EmmEff who is lead on the cloud things and we don't have any major objections. I have a ToDo for 'tidying remote UX' for 3.7 so if there are any rough edges that show up over time we'll just address them as they appear.

**Pull request merged**
