### PR TITLE
Add a Gitter chat badge to README.md

### PR DESCRIPTION
**Pull request by gitter-badger**
### singularityware/singularity now has a Chat Room on Gitter

@vsoch has just created a chat room. You can visit it here: [https://gitter.im/singularityware/singularity](https://gitter.im/singularityware/singularity?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&content=body_link).

This pull-request adds this badge to your README.md:

[Gitter](https://gitter.im/singularityware/singularity?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=body_badge)

If my aim is a little off, please [let me know](https://github.com/gitterHQ/readme-badger/issues).

Happy chatting.

PS: [Click here](https://gitter.im/settings/badger/opt-out) if you would prefer not to receive automatic pull-requests from Gitter in future.

### CODE REVIEW

**Comment by vsoch** [comment]
wow, is it just me, or did this robot spell check for us too? Wowza.

**Comment by gmkurtzer** [comment]
Do we want Gitter as our default? I love the idea, but it is a tad clunky and not as intuitive as Slack. On the other hand, even though Slack has a fantastic interface, it's financially motivated limitations (especially for an open source project) has really rubbed me the wrong way.

Thoughts?

**Comment by vsoch** [comment]
yeah I'm in agreement - I really wanted Gitter to be great, but it doesn't work very well.

**Comment by vsoch** [comment]
There still could be another option, here are some that I found:

- https://ryver.com/
- https://rocket.chat/
- https://www.samepage.io/
- https://sdelements.github.io/lets-chat/
- https://glip.com/pricing

it's too bad the [new hangouts](https://www.recode.net/2017/3/9/14872162/googles-hangouts-slack-rooms-thread-conversation) I think isn't free, I bet that one will top them all :)

self hosting is probably a no go, but a nice option if we ever have the resources.

**Comment by jjohnson42** [comment]
mattermost may be worth thinking about if you do self host

**Comment by gmkurtzer** [comment]
I am going to close this for now, as I don't think we are ready to move away from Slack yet.

Thanks everyone!

**Pull request closed without merging**
