### PR TITLE
Creates parent directories before copying in %files

### LINKED ISSUE #1549: Create parent directories for files added in %file section
Filed on behalf of @fdawg4l

## Version of Singularity:

2.5.1

### Expected behavior

The `%files` section should create the parent directory tree for a file if it doesn't already exist. 

### Actual behavior

I have to copy my binary to a tmp location then move it in `%post`.

### Steps to reproduce behavior

If you want to copy a file to a directory structure that does not yet exist before the `%post` section you must do something like this:

```
Bootstrap: docker
From: busybox

%files
    ./foo /foo

%post
    mkdir -p /my/file/location
    mv /foo /my/file/location/foo
```

It would be much nicer if one could just do this:

```
Bootstrap: docker
From: busybox

%files
    ./foo /my/file/location/foo
```

### LINKED ISSUE #3348: Multi-stage file copy and non-existent parent directories
## Version of Singularity: 

3.2.0-rc1

### Expected behavior

Image successfully built with file at path `/some/other/path/foo`.

### Actual behavior

```
INFO:    Copying /tmp/sbuild-471116024/fs/path/to/something/foo to /tmp/sbuild-068948471/fs/some/other/path/foo
FATAL:   While performing build: unable to copy files a stage to container fs: while copying /tmp/sbuild-471116024/fs/path/to/something/foo to /tmp/sbuild-068948471/fs/some/other/path/foo: exit status 1: /bin/cp: cannot create regular file '/tmp/sbuild-068948471/fs/some/other/path/foo': No such file or directory
```

### Steps to reproduce behavior

```
# cat foo.def
BootStrap: docker
From: centos:7
Stage: zero

%post
    mkdir -p /path/to/something
    echo "foo" >> /path/to/something/foo

BootStrap: docker
From: centos:7

%files from zero
    /path/to/something/foo /some/other/path/foo

# singularity build foo.sif foo.def
...
```

This is almost certainly the same underling issue as https://github.com/sylabs/singularity/issues/1549.  However, the `%setup` workaround does not work in the second stage of a multi-stage definition file - it looks like `%setup` is completely ignored?

The "copy file to root, then move in %post" trick does work.

IMHO, multi-stage builds add some urgency to fix #1549.  It seems very natural to build something in the first stage, and then want to copy it to another location in the second stage.  More so than copying files from the host into the container, which is the use case of #1549.  

@ikaneshiro

### PR DESCRIPTION
**Pull request by ikaneshiro**
**Description of the Pull Request (PR):**

- Creates parent directories in `%files` if they do not exist in container
- Removes some duplicate code in build system
- Adds unit tests

**This fixes or addresses the following GitHub issues:**

- Fixes #1549 
- Fixes #3348 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by WestleyK — APPROVED** [review]
Looks good to me! :+1:

**Review by sashayakovtseva — APPROVED** [review]
`copy.Copy` is not best naming IMO
Otherwise looks goof

**Comment by ikaneshiro** [comment]
@sashayakovtseva True, I plan on doing some refactoring of this package for 3.3 so I'll keep this in mind as something to improve

**Review by tri-adam — APPROVED** [review]
LGTM

**Pull request merged**
