### PR TITLE
Test addition of SonarQube scanner support.

### PR DESCRIPTION
**Pull request by bbockelm**
This test PR is meant to kick off a Travis-CI build so I can preview SonarQube support

### CODE REVIEW

**Comment by gmkurtzer** [comment]
Is there something else we need to configure to enable? Travis is failing on this PR.

**Comment by bbockelm** [comment]
Seems to be two things:
1.  SonarQube Java version mismatch.
2.  It seems to not figure out that the env var is encrypted and automatically disabling.

**Comment by vsoch** [comment]
Did you go through [these steps](https://docs.travis-ci.com/user/environment-variables/) and everything? I would first try an interactive shell, and if that doesn't work, if you give me the details of how this thing works / what it is, I can try help to debug.

**Comment by bbockelm** [comment]
Yeah - I'm trying various recipes I found on their mailling list.  Seems that this code scan tool is more oriented to the Java community, so C support is ... lacking.

**Comment by bbockelm** [comment]
Ah!  Github documentation pages note that the variables are only marked as secure if `.travis.yml` is unchanged.  So, I may need to upload the branch to the singularity repo, then merge from within the same project.

**Pull request closed without merging**
