### PR TITLE
Fix mount invalid argument and restrictive directory binds

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR remove `open` call from singularity_mount.
`open` was used to get path from `/proc/self/fd/x` and obtain a "trusted" path, but a kernel bug on CentOS 7.2.1511 in overlay code give a wrong path relative to overlay mountpoint and singularity always fail.
Another issue was to open directories or file with restrictive permissions since the code is executed unprivileged, `open` fail.

**This fixes or addresses the following GitHub issues:**

- Ref: #1524 #1518 

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [ ] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by GodloveD** [comment]
@gabrielmartinh and @blakedewey are you able to test this PR?

**Comment by blakedewey** [comment]
Works!

**Review by jmstover — APPROVED** [review]

**Review by GodloveD — APPROVED** [review]
lgtm
:shipit:

**Comment by GodloveD** [comment]
Switched merge target to release-2.5 and will cherry-pick into development-2.x.

**Pull request merged**
