### PR TITLE
Boot/start instance

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

- Allow to start instance and execute /sbin/init by default
- Add --noboot option to execute startscript rather than init
- Add UTS namespace as init system set hostname when they start services
- Add fakeroot options to run container as root in user namespace
- User namespace support for running/joining instances

```

 Compatibility between host system init and container system init

                   +---------------------+----------------------+---------------------+
                   | systemd (container) | sysvinit (container) | upstart (container) |
 +-----------------+---------------------+----------------------+---------------------+
 | systemd (host)  |        YES          |         YES (2,3)    |        YES (4)      |
 +-----------------+--------------------------------------------+---------------------+
 | upstart (host)  |        YES (1)      |         YES (2,3)    |        YES (2,4)    |
 +-----------------+---------------------+----------------------+---------------------+
 | sysvinit (host) |     NOT TESTED      |      NOT TESTED      |     NOT TESTED      |
 +-----------------+---------------------+----------------------+---------------------+

 (1) Depends of host kernel version, requires >= 3.5
 (2) Network namespace is required (dbus socket conflict, bring down network interfaces)
 (3) Changed processus name and CAP_SYS_BOOT must be dropped
 (4) Depends of upstart version (ubuntu 14.04 don't start services automatically)
```

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
This is so ridiculously awesome. I'm still getting my head around it!

**Comment by gmkurtzer** [comment]
I was hoping to get this integrated before the release but this isn't quite as simple as an integration as I would have hoped.

Thoughts?

**Comment by bauerm97** [comment]
@gmkurtzer I think this is too major of a change to push before release

**Comment by vsoch** [comment]
I think there is so much going on with this release, we should hold off on this awesome feature for the next one. A wise grandmaster once told me... patience, grasshoppa!

**Comment by cclerget** [comment]
Since this feature rely on others which will be integrate in next release, it's better to integrate it in the next one

**Comment by gmkurtzer** [comment]
Yep, agreed! And so looking forward for this in the next release! WAHOO!

**Comment by gmkurtzer** [comment]
I think the `--boot` option should also force `--net` to separate out the network namespace. Thoughts?

**Comment by cclerget** [comment]
Yes, network namespace is set automatically now, wait merge to drop some capabilities

**Comment by gmkurtzer** [comment]
This looks fantastic, thank you Cedric!

**Pull request merged**
