### PR TITLE
Have signals forward transparently to the payload process.

### PR DESCRIPTION
**Pull request by bbockelm**
Signals are now forwarded correctly from parent to child; if the
namespace daemon is killed, then the exec daemon will exit immediately.

### CODE REVIEW

**Comment by bbockelm** [comment]
NOTE NOTE NOTE: This moves the exec process to be PID 1!!!

Will this be OK?  It seems so, as the namespace daemon does all the cleanup.

Just to be safe, I made the exec daemon drop privileges permanently.  Not clear why it doesn't already do that.

**Comment by gmkurtzer** [comment]
Hi @bbockelm, there is a conflict with this merge. Did you want to check that or should I merge it in?

Thanks!

**Comment by bbockelm** [comment]
Whoops, I missed the merge conflict.  Will try to get that fixed this afternoon.

**Comment by bbockelm** [comment]
Ok, all fixed up.

**Comment by gmkurtzer** [comment]
Hrmm, for some reason the CI is now failing:

https://travis-ci.org/gmkurtzer/singularity/builds/149864399

Wanna have a quick look when you get a chance?

**Pull request merged**
