### PR TITLE
Fix to honor user name request for Singularity Hub pull

### PR DESCRIPTION
**Pull request by vsoch**
**Description of the Pull Request (PR):**

I'm not sure why there is such a discrepancy in the branches (I started with the same development base) so if someone has insight let me know!

This PR will address the pull issues reported in #1095 , specifically we do the following:

1. if the user provides a name with `--name`, honor it and don't touch extensions
2. If the user names by commit or hash, give image extension based on compressed gz (.img) or squash fs (simg)
3. If the user doesn't ask for any name, default to using the manifest, and same extension rules as above.

Here I will show each case:

# Case 1. Squash, default name
```
singularity pull shub://vsoch/hello-world
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/Desktop/singularity/vsoch-hello-world-master-latest.simg
```

# Case 2. Ext3, default name
```
singularity pull shub://doc.fish/vsoch/hello-world
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/Desktop/singularity/vsoch-hello-world-master.img
```
# Case 3. Squash, by commit
```
singularity pull --commit shub://vsoch/hello-world
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/Desktop/singularity/e279432e6d3962777bb7b5e8d54f30f4347d867e.simg
```
# Case 4. Ext3, by commit
```
singularity pull --commit shub://doc.fish/vsoch/hello-world
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/Desktop/singularity/f9cd90a7b030a9c794bfe76c123da5a518ad9962.img
```
# Case 5. Squash, custom name
```
singularity pull --name pasta.is.great shub://vsoch/hello-world
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/Desktop/singularity/pasta.is.great
```
# Case 6. Ext3, custom_name
```
singularity pull --name meatballs.are.great shub://doc.fish/vsoch/hello-world
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/Desktop/singularity/meatballs.are.great
```
# Case 7. Squash, by hash
```
singularity pull --hash shub://vsoch/hello-world
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/Desktop/singularity/ed9755a0871f04db3e14971bec56a33f.simg
```
# Case 8. Ext3, by hash
```
singularity pull --hash shub://doc.fish/vsoch/hello-world
Progress |===================================| 100.0% 
Done. Container is at: /home/vanessa/Desktop/singularity/abba5a1f91b2e98ebe125fc7a5151b33.img
```

I also fixed issues with the Docker `--name` - it was doing the equivalent forcing of an extension, which we don't want to do.

Attn: @singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
@gmkurtzer @GodloveD - I disabled the Docker pulls because travis is clearly having issues. The rest seems ok! Any idea why there is this extra alpine stuffs for the development that I pulled? Was it added and removed? I can remove it again if needed... let me know!

**Review by GodloveD — APPROVED** [review]
I can certify that this is working as advertised.

**Comment by vsoch** [comment]
woot! I can too... but I'm biased :) Can we merge?

**Comment by GodloveD** [comment]
We're sposed to have two reviews. Care to solicit another?

**Comment by vsoch** [comment]
@truatpasteurdotfr care to review?

**Comment by gmkurtzer** [comment]
I'm gonna go ahead and merge for 2.4.1 incorporation. Thank you!

**Comment by vsoch** [comment]
woohoo!!

**Comment by johanneskoester** [comment]
Thanks for this fix! Can we expect 2.4.1 to be released soon? The current behavior breaks Snakemake.

**Pull request merged**
