### PR TITLE
a quick fix to resolve the documentation issues around pull

### PR DESCRIPTION
**Pull request by vsoch**
This is a quick fix to make the documentation about the pull command correct, as it does not pull anymore to `SINGULARITY_CACHEDIR`, but instead to `$PWD` This will not fix (insert arbitrary stuff here so Github doesn't close) #464 but will minimally communicate the correct usage to the user.

I also fixed a print statement when decompressing the image which was driving me nuts :_)

@gmkurtzer we will still need to discuss the change for #464 when you return from linux-admin duties!

@singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
@gmkurtzer ready for merge.

**Comment by vsoch** [comment]
@gmkurtzer I added a note about the -H/--home option to the doc - let's merge after checks?

**Comment by vsoch** [comment]
@gmkurtzer ready for merge! I'm going to keep poking you about this one :)

**Comment by gmkurtzer** [comment]
Heya @vsoch, can you update this for the development branch? Thanks!

**Comment by vsoch** [comment]
looks like I snuck this change into another PR, because it's already in :)

I will update the PR I just did to have the pull command reflect current practice (eg using the name of the image instead of hash!) closing this one now.

**Pull request closed without merging**
