### PR TITLE
Overlaymount

### PR DESCRIPTION
**Pull request by aduffy19**
Added setup and call to mount_overlay within mount_image, if not writable and overlay is enabled. Includes addition to singularity.conf file.

### CODE REVIEW

**Comment by gmkurtzer** [comment]
Heya @aduffy19! This looks great but it isn't building via travis. Can you take a look at that?

Thank you!

**Comment by aduffy19** [comment]
Ah, @jjohnson42 had done some separate setup to test this and we didn't copy it all over. Will update once he's available, as I'm not sure what he did.

**Comment by gmkurtzer** [comment]
It looks like it is building properly now, but we are getting errors on unsupported systems (e.g. in the above travis output) that it is failing on unsupported systems.

How are you configuring it to work automatically? That perhaps needs to be conditional at runtime or better yet checked with ./configure.

Thanks!

**Comment by gmkurtzer** [comment]
Looks good! I'm going to merge this and shortly start looking at how to integrate into the devel branch (unless of course you want to do that?). :)

**Pull request merged**
