### PR TITLE
Possible Rebase 1673 Extraction of ext/squashfs shub image content to bundle

### PR DESCRIPTION
**Pull request by dtrudg**
Alternate rebase strategy compared to https://github.com/bauerm97/singularity/commits/ian-shub-merge - for consideration. But I prefer @bauerm97's at the link above.

**Description of the Pull Request (PR):**

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

**This fixes or addresses the following GitHub issues:**

- Ref: #

**Checkoff for all PRs:**

- [ ] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [ ] I have tested this PR locally with a `make test`
- [ ] This PR is NOT against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [ ] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
Beautiful! This makes my heart so happy :-) I'm going to visit someone in the hospital but I'll be able to review this likely tomorrow. Thank you everyone for your hard work and making this right 🤗

**Comment by vsoch** [comment]
@dctrud this seems like the most consistent to preserve commit history, for example the updated file now has the correct git blame view!

gitblame

I looked over the other proposed link above, and I can't trace/find the original code. Perhaps this one is the way to go? I might need some help to understand the differences between the two - for example, this has the shub provisioner and the one one I can't find it.

**Comment by vsoch** [comment]
Oh, I see the difference now! If you look under commits, each of this one and @bauerm97 have the addition reversed - one has the pink butterflies on top, the other the bottom. Which end do we look at to determine what is the current, the top right?

**Comment by dtrudg** [comment]
They are equivalent - in this PR view top is first, bottom is last. In the commit view for the bauerm branch it’s reversed - top is newest.

**Comment by vsoch** [comment]
okay, this PR I believe to be more accurate. @bauerm97 has the commits shared by two people, which wouldn't be accurate given that the code had been added then updated. Here is the git blame to show this - notice two icons next to the lines.

two

And notice in the picture above, this isn't the case. The devil is in the details! Again, many thanks for your making this right.

**Comment by dtrudg** [comment]
Git tracks 2 people for each cherry pick. The author (who wrote the commit originally) and the committer (who cherry picked). The 2 pictures is an annoyance that is github related. I’d advise trying to ignore that. Look at git log / git blame output on the cli and you should see your name associated, with michael’s only if you specifically ask for a more verbose format.

**Comment by vsoch** [comment]
@dctrud this is why I think your PR is preferable, it should be that author == commit.

**Pull request closed without merging**
