### PR TITLE
2.4 alpine test fixes

### PR DESCRIPTION
**Pull request by truatpasteurdotfr**
**Description of the Pull Request (PR):**

- tentative portability fixes of singularity-2.4 for passing the tests on alpine linux 
- requires @vsoch PR1045

**This fixes or addresses the following GitHub issues:**

- Ref: #1042 

**Checkoff for all PRs:**

- [ ] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have tested this PR locally with a `make test`
- [ ] This PR is NOT against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [X ] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Review by GodloveD — COMMENTED** [review]
I can verify that these changes allow all tests to pass on Alpine Linux and that all tests still pass on Ubuntu.

@vsoch would you have a minute to look at these changes too.  If you like them I say we should merge!

**Comment by vsoch** [comment]
are we just deciding to remove the `--exclude` bits for when image (self) build is re-enabled? The other things look reasonable, I can't comment because I don't know a thing about alpine linux. other than it has ~441 "files" most of which are symlinks :)

**Comment by GodloveD** [comment]
Oh good catch @vsoch! Removing that line is probably going to result in creating images that are far to big right?  We should probably add it back in, but it looks like alpine `du` does not have the `--exclude` option.  Any ideas @truatpasteurdotfr ?

**Comment by truatpasteurdotfr** [comment]
`       -x      Skip directories on different filesystems` so that should be ok if the excluded list are mount points only
[x] /proc
[x] /dev (listed twice)
[?] /var
[?] /tmp   <- mount point only?
[?] /media <- mount point only?
[?] /home  <- bind mount?

OTOH we can make some math by susbstracting the excluded size.

**Comment by GodloveD** [comment]
> `-x Skip directories on different filesystems`

Ah OK.  I didn't know that.  

@truatpasteurdotfr if you have time would you mind running a test please?  Can you build two containers from the same .def file; one with the `du -x` option and one with the old syntax.  If the `-x` option excludes everything that we want, I assume the two containers will be the same size.  Is that a reasonable assumption?

If you don't have time I will try to test as soon as I am finished re-working the `--nv` option.  Thank you!

**Comment by truatpasteurdotfr** [comment]
hi, something is not quite right but I can't figure out what tonight:
( I have added 3 lines to the pristine 2.4 version to print out the `du w/exclude` and the `du -x` ones
running on CentOS-7 
```
--- /usr/libexec/singularity/bootstrap-scripts/post.sh-orig	2017-10-12 09:19:40.000000000 +0200
+++ /usr/libexec/singularity/bootstrap-scripts/post.sh	2017-10-20 23:25:15.342934097 +0200
@@ -73,8 +73,11 @@
 
 # Calculate image final size
 message 1 "Calculating final size for metadata...\n"
+IMAGE_SIZE_A=$(du -x --apparent-size -sm $SINGULARITY_ROOTFS | cut -f 1)
+message 1 "du -x --apparent-size -sm: $IMAGE_SIZE_A\n"
 EXCLUDE_LIST="--exclude=$SINGULARITY_ROOTFS/proc --exclude=$SINGULARITY_ROOTFS/dev --exclude=$SINGULARITY_ROOTFS/dev --exclude=$SINGULARITY_ROOTFS/var --exclude=$SINGULARITY_ROOTFS/tmp --exclude=$SINGULARITY_ROOTFS/media --exclude=$SINGULARITY_ROOTFS/home"
 IMAGE_SIZE=$(du --apparent-size -sm $EXCLUDE_LIST $SINGULARITY_ROOTFS | cut -f 1)
+message 1 "du --apparent-size -sm $IMAGE_SIZE\n"
 eval $SINGULARITY_ADD_SCRIPT -f --key "org.label-schema.build-size" --value "${IMAGE_SIZE}MB" --file $SINGULARITY_LABELFILE

```

```
[tru@elitebook840g3 alpine]$ cat alpine.def 
Bootstrap: docker
From: alpine:3.6
[tru@elitebook840g3 alpine]$ sudo singularity build /dev/shm/a.simg alpine.def 
Using container recipe deffile: alpine.def
Sanitizing environment
Adding base Singularity environment to container
Docker image path: index.docker.io/library/alpine:3.6
Cache folder set to /root/.singularity/docker
Exploding layer: sha256:88286f41530e93dffd4b964e1db22ce4939fffa4a4c665dab8591fbab03d4926.tar.gz
Exploding layer: sha256:dee84a4c12468c1ceaff6effeab567b3cd6e2dcc403a33b357e04abf9f3a1d7f.tar.gz
Finalizing Singularity container
Calculating final size for metadata...
du -x --apparent-size -sm: 6
du --apparent-size -sm 643
Skipping checks
Building Singularity image...
Singularity container built: /dev/shm/a.simg
Cleaning up...
[tru@elitebook840g3 alpine]$ du -sm /dev/shm/a.simg
2	/dev/shm/a.simg
[tru@elitebook840g3 alpine]$ 

```

**Comment by GodloveD** [comment]
Hey @truatpasteurdotfr just wanted to check in and see where this currently stands.  Were you ever able to figure out the discrepancy in file size estimation?  

I'm also tagging this as a bug so that @gmkurtzer sees it should be cherry picked into 2.4.1 if we can get it completed in time.

**Comment by gmkurtzer** [comment]
Heya @truatpasteurdotfr, what is the status of this PR? Ready to merge into development?

**Comment by GodloveD** [comment]
Hey @truatpasteurdotfr I talked about this with @gmkurtzer and I think we are good to merge.  But this is against the master branch.  Would you mind changing the PR to be against development please?

**Comment by gmkurtzer** [comment]
Merging this into development and release-2.4 branches. Closing here as this is against master.

**Pull request closed without merging**
