### PR TITLE
Flx42 python add http cleanup

### PR DESCRIPTION
**Pull request by vsoch**
Fixes #356 and integrates and closes #356 to integrate @flx42 contributions to the functions

Changes proposed in this pull request

 - add_http function reliably returns the correct URI asked for the by the user, given that http, https, or no URI are supplied. It does this by using `urlparse` to parse the url and add the extension to what is requested to the rest. 
 - the tests have been updated to test for all these cases

@singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
@gmkurtzer ready for merge! Thanks @flx42 ! Good teamwork.

**Comment by flx42** [comment]
You don't remove the trailing `/` anymore, and you are not preserving `http`.

**Comment by vsoch** [comment]
What do you mean not preserving http? it always returns http or https, which is what we want. The trailing `/` is a good call - let me add that back in!

**Comment by flx42** [comment]
You always discard the user-provided scheme, I thought we agreed not to do that?

**Comment by vsoch** [comment]
@gmkurtzer mentioned that it should be controlled to http or https, so I think that's reasonable to do now, and using a boolean (and not an open string as default argument) is a good way to do that. We can easily add support for other URIs if/when we need them.

**Comment by flx42** [comment]
My updated PR verifies it's `http` or `https`, rejecting other schemes, but it's also extensible to other schemes in the future by passing an open string.

**Comment by vsoch** [comment]
It's generally not a good idea to use mutable objects in function arguments, because they are created at the time the function is created (not when called) which can result in weird behavior. I think this is why you tend to see defaults set as `None` and then set in the function when called. I haven't read a ton about it, but [here is a good starting point](https://pythonconquerstheuniverse.wordpress.com/2012/02/15/mutable-default-arguments/). So if we need this functionality in the future, we will find a different way to implement it. I greatly appreciate your input and general contributions @flx42. @gmkurtzer this is ready for merge.

**Comment by gmkurtzer** [comment]
Will do, thanks!

**Comment by flx42** [comment]
Actually, a string is **not** a mutable object, so that's fine.
If you really want to have an argument called `use_https`, then you should really enforce it and raise an error for both of these cases: `add_http("http://example.com", use_https=True)` and `add_http("https://example.com", use_https=False)` because that looks like a logic error.

**Comment by flx42** [comment]
Thanks for merging, we're making good progress!

**Pull request merged**
