### PR TITLE
Release 3.0.2

### PR DESCRIPTION
**Pull request by GodloveD**
Placeholder for 3.0.2.  This contains every commit that has been merged into the master branch as of today with the exception of 24721b98043732d5f8b2cd86e55319f531d4598f which adds new functionality and changes the CLI.

Note that this release *will* contain some changes to the CLI which is usually a big no-no in a point release.  But those changes can be regarded as bugs since they represent functionality that was already in 2.x and was missing from 3.x.  

Will also need to go through these changes and update the `CHANGELOG.md` before release.

Here's a list of all the PRs added:
#2328 
#2336 
#2337 
#2340 
#2342 
#2334 
#2344 
#2353 
#2355 
#2358 
#2361 
#2346 
#2366 
#2382 
#2368 
#2378 
#2388 
#2396 
#2365 
#2399 
#2395 
#2359 
#2360 
#2372 
#2393 
#2375
#2401 
#2408 
#2422 
#2426 
#2416 
#2427 
#2419 
#2423 
#2437 
#2392 
#2452 
#2457 
#2463

### CODE REVIEW

**Comment by DrDaveD** [comment]
If possible, I would like to get not-yet-merged #2472 and #2481 into this release.

**Comment by GodloveD** [comment]
@DrDaveD this includes some bug fixes that are long overdue and have caused some users problems.  I would prefer to try to expedite the process and tag the release with the current set of PRs if possible.  3.1.0 is also in the planning stage, so we should be able to get those PRs in quickly.

**Comment by DrDaveD** [comment]
#2481 fixes a serious bug too, but it's up to you.

**Comment by GodloveD** [comment]
After discussion with @bauerm97 it seems that #2400 should be included too.  I'll cut a cleaner PR.

**Pull request closed without merging**
