### PR TITLE
For EPEL - prefer python3 if present

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

This PR prefers python3 if it is installed, based on release-2.6.  It is not expected to be merged, but to be used as a basis for an EPEL/Fedora patch.  Replaces PR #1762.

**This fixes or addresses the following GitHub issues:**

- Ref: #

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [ ] This PR is ready for review and/or merge

### CODE REVIEW

**Comment by truatpasteurdotfr** [comment]
could this be pushed for the next release of 2.x ?

**Comment by DrDaveD** [comment]
It's already in the EPEL release of 2.6.0.  Do you want it for something that can't use EPEL?

**Comment by truatpasteurdotfr** [comment]
I just want uptream from EPEL to carry it :P ie accepted/discussed in the singularity released version on github.

**Comment by DrDaveD** [comment]
I never even asked for that for this PR.  The singularity core team is focused on 3.0 and they want to avoid putting stuff into 2.x that isn't strictly necessary.  I only made the PR because EPEL requires working with python3 and they also require linking package modifications to upstream tickets.  singularity 2.x works fine with python 2.x, and singularity 3.0 has no python in it so it won't be relevant going forward.

**Pull request closed without merging**
