### PR TITLE
Fix megabyte/mebibyte confusion in help

### PR DESCRIPTION
**Pull request by loveshack**
Also fix expand default size.

### CODE REVIEW

**Comment by gmkurtzer** [comment]
Ooops,.... pedantics! Thanks!

**Comment by loveshack** [comment]
You wrote: 

> Ooops,.... pedantics! Thanks!

Well, it's a 7% difference for the default image size.

**Comment by remyd1** [comment]
Hum... Interesting, that could explain a bit the size problem conversion
from docker to singularity...

**Comment by loveshack** [comment]
DERNAT R�my notifications@github.com writes:

> Hum... Interesting, that could explain a bit the size problem conversion
> from docker to singularity...

I don't think so, but it would help, if anything.

**Pull request merged**
