### PR TITLE
Make the testing makefile rules more consistent

### PR DESCRIPTION
**Pull request by jscook2345**
**Description of the Pull Request (PR):**

Make the testing makefile rules more consistent so they can be split up later.

Attn: @singularity-maintainers

### CODE REVIEW

**Review by ArangoGutierrez — CHANGES_REQUESTED** [review]
you also need to apply this change on travis and circlci file

**Review by jmstover — APPROVED** [review]

**Comment by jscook2345** [comment]
I actually fixed the `.PHONY`.

**Comment by ArangoGutierrez** [comment]
My point is not about the PHONY, but about the make target. circleci config will be calling a make target that doesn't exist

**Comment by jscook2345** [comment]
It never did. `.PHONY` does not create a proper make target. I'm just changing things now to fix that.

**Review by ArangoGutierrez — APPROVED** [review]

**Pull request merged**
