### PR TITLE
Respect available caps in set_master_privileges

### PR DESCRIPTION
**Pull request by dtrudg**
## Description of the Pull Request (PR):

WIP toward addressing #5267 

### This fixes or addresses the following GitHub issues:

 - Fixes #

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by dtrudg** [comment]
Would be super grateful for your input here @cclerget if you are able.

**Comment by cclerget** [comment]
@dctrud For this issue, the same would apply to RPC and container capabilities. Here an attached patch taking those cases into account:

[patch.txt](https://github.com/sylabs/singularity/files/4574630/patch.txt)

**Comment by dtrudg** [comment]
@cclerget - do you want to me to apply the patch here, or do you want to open a different PR? I don't mind which you prefer.

**Comment by dtrudg** [comment]
This one looks good to me, and we had a report of confirmed fix from the reporting user. 

However, since this is my PR, and the commited change here is now @cclerget 's updated patch I'm going to ask if @EmmEff or @tri-adam have a change to take a quick look to give the final okay.

**Review by EmmEff — APPROVED** [review]
lgtm

**Pull request merged**
