### PR TITLE
Alpine singularity 3.1.1 singularity 3.2.0

### PR DESCRIPTION
**Pull request by truatpasteurdotfr**
**Description of the Pull Request (PR):**
alpine linux versions

**This fixes or addresses the following GitHub issues:**

- Fixes #

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by GodloveD** [comment]
Heya @truatpasteurdotfr.  Thanks so much for keeping Singularity up to speed on Alpine!

I'm trying to test/review this, but unfortunately I have no idea what I'm doing.  😜 I'm using [this vagrant box](https://app.vagrantup.com/generic/boxes/alpine39) for my Alpine environment, and I've installed `alpine-sdk`.  I'm basically trying to follow the instructions [here](https://wiki.alpinelinux.org/wiki/Creating_an_Alpine_package).  But I keep getting the following:

```
localhost:~/singularity/dist/alpinelinux/singularity-3.1.1$ abuild -r build
/usr/bin/abuild: cd: line 47: can't cd to x86_64-alpine-linux-musl: No such file or directory
>>> ERROR: singularity: build failed
```
Probably missing something very obvious.  Can you tell what I'm doing wrong?

**Comment by truatpasteurdotfr** [comment]
Hi, alpine people are picking the ball :P at https://github.com/alpinelinux/aports/tree/master/testing/singularity
My cheat sheet is https://github.com/sylabs/singularity/blob/master/dist/alpinelinux/README.txt, you just need to run `abuild -r` in the folder containing the APKBULD file. ymmv, but you need to belong to the abuild group to write into /var/cache/distfiles.

**Comment by GodloveD** [comment]
Ah.  You'd think I'd have enough sense to read a file called `README.md`.  Spoiler alert. You'd be wrong.

Thanks for the pointer.  I _think_ I was probably missing the linux headers.  After following the instructions in the cheat sheet this looks good to me.  

One quick question though before merging.  Is there any way to get `singularity version` to display something more useful?  Right now it just displays the hash of the most recent commit after installation.  But I don't know if that is on your end or our end.

**Comment by truatpasteurdotfr** [comment]
It seems to work for me:
```
alpine:~$ apk info singularity
singularity-3.2.0-r2 description:
Singularity: Application containers for Linux

singularity-3.2.0-r2 webpage:
https://www.sylabs.io/singularity

singularity-3.2.0-r2 installed size:
110206976

alpine:~/packages/singularity-build/x86_64$ singularity version
3.2.0-1

```
upgrading to 3.2.1 (I will make a new PR for that):
```
alpine:~/packages/singularity-build/x86_64$ sudo apk add singularity-3.2.1-r1.apk
(1/1) Upgrading singularity (3.2.0-r2 -> 3.2.1-r1)
Executing busybox-1.29.3-r10.trigger
OK: 2144 MiB in 495 packages
alpine:~/packages/singularity-build/x86_64$ singularity version
3.2.1-1
```
```

**Comment by truatpasteurdotfr** [comment]
coudl you try to rebuild from the APKBULD file listed in the PR at  https://github.com/sylabs/singularity/pull/3674 ? I am still trying to use a singularity container to build singularity on alpine, but it seems that it needs some suid magic to become member of the abuild group.

**Comment by GodloveD** [comment]
Wonder why the version command is not working correctly for me.  

```
$ sudo apk add --allow-untrusted ~/packages/alpinelinux/x86_64/singularity-3.2.1-r1.apk
(1/5) Installing lz4-libs (1.8.3-r2)
(2/5) Installing lzo (2.10-r2)
(3/5) Installing squashfs-tools (4.3-r5)
(4/5) Installing libseccomp (2.3.3-r1)
(5/5) Installing singularity (3.2.1-r1)
Executing busybox-1.29.3-r10.trigger
OK: 470 MiB in 123 packages

$ singularity version
41666b162
```

EDIT:
Oh you know what, I bet I just don't have the tags.  This is what happens when somebody who's become a meeting jockey tries to step in and start reviewing PRs again.  😊 

EDIT:
EDIT:
Looks good once I have the tags.

**Review by GodloveD — APPROVED** [review]
lgtm

**Pull request merged**
