### PR TITLE
Updating logger to be class with functions for mapping and level information

### PR DESCRIPTION
**Pull request by vsoch**
@gmkurtzer try out this alternative - it would fit the current print statements into our current workflow, but really just make the default behavior to silence most when the user runs. I'm not sure if I like it, but it's what (I think) you were more in support of given your comment, so let me know what you think.

### CODE REVIEW

**Comment by gmkurtzer** [comment]
So in the C and shell code, the default logging level is 1 and quiet is 0. INFO messages (e.g. `singularity_message(INFO, "...")` are at level 1, so they will get printed on the default log level or anything greater then 1. But when --quiet is requested and the messagelevel is set to 0, only warning and error messages will be displayed.

Does that fit with what you have? (Haven't looked at code yet, will do on keyboard shortly).

**Comment by vsoch** [comment]
hmm, not sure about that error in post.sh, I haven't seen it before. I want to try something different with the logger anyway , will update the PR.

**Comment by vsoch** [comment]
Hey @gmkurtzer ! Check out these changes. What I've done is updated the logger to be a class (`Logman`) instead of a variable imported from a file (which is a class, but one that doesn't have our own functions). It works similarity, except you import the logger class instead of the logger (now associated with the class):

```python
# Old way
from logman import logger
logger.debug("Oh no's!")

# New way
from logman import bot
bot.logger.debug("Oh no's!")
```

What this means is that I can add functions that made it easy to determine the level, and make it easy to understand the mapping between the Singularity C code and python. For example, to check if I should silent a (usually default) print statement, that is print exclusively for the user information and aesthetic, I can do:

```python
if not bot.is_quiet():
    print("The logger is not quiet.")
```

I can also produce a data structure that gives information about the mappings:

```python
from logman import bot

bot.is_quiet()
False

bot.get_mapping()

{'ABRT': {'flags': ['--quiet', '-q'],
  'python_effective_level': 50,
  'python_level': 'logging.CRITICAL',
  'singularity_levels': [-4]},
 'DEFAULT': {'python_effective_level': 50,
  'python_level': 'logging.FATAL',
  'singularity_levels': [0]},
 'ERROR': {'python_effective_level': 40,
  'python_level': 'logging.ERROR',
  'singularity_levels': [-3]},
 'INFO': {'python_effective_level': 20,
  'python_level': 'logging.INFO',
  'singularity_levels': [1]},
 'LOG': {'python_effective_level': 20,
  'python_level': 'logging.INFO',
  'singularity_levels': [1]},
 'VERBOSE': {'python_effective_level': 10,
  'python_level': 'logging.DEBUG',
  'singularity_levels': [4]},
 'VERBOSE1': {'python_effective_level': 10,
  'python_level': 'logging.DEBUG',
  'singularity_levels': [4]},
 'VERBOSE2': {'python_effective_level': 10,
  'python_level': 'logging.DEBUG',
  'singularity_levels': [4]},
 'VERBOSE3': {'python_effective_level': 10,
  'python_level': 'logging.DEBUG',
  'singularity_levels': [4]},
 'WARNING': {'python_effective_level': 30,
  'python_level': 'logging.WARNING',
  'singularity_levels': [-2]}}
```

I think this is a good change because it will fix #544 and open up the door for future functionality for a user to spit a lot somewhere else, or even programatically post it to some more web based endpoint. Or do anything advanced with the logger, period. Let me know your thoughts.

**Comment by gmkurtzer** [comment]
This looks good to me. The only thing I would add is that it might make sense to use the same nomenclature that we have for the shell and C interfaces (e.g. message/singularity_message, instead of logman), but other then the pedantics of nomenclature, this looks awesome! :-D

**Comment by vsoch** [comment]
@gmkurtzer the logman has been that way already, he's not new lol. You are going to hold off merging for that!?

**Comment by vsoch** [comment]
@gmkurtzer ready for merge.

**Comment by vsoch** [comment]
I'm going to change one more "info" to "debug" but the PR should still pass.

**Comment by vsoch** [comment]
travis failed with an `apt-get` ?? /facepalm

**Comment by vsoch** [comment]
it looks like there are issues with getting dependency packages on travis, and the build is likely to fail. It passed previously and should be ready to go if you want to merge, if you don't trust me you can wait for travis, rebuild, and then merge.

**Comment by vsoch** [comment]
@gmkurtzer ready for merge!

**Comment by vsoch** [comment]
@gmkurtzer just to be clear, the issue at #557 was fixed by reversing the layers dump back to how we originally had it, which we thought was a fix for the original docker permissions issue, but it wasn't. To verify the (old) bug is still fixed with changing the layers back, I re-tested the original command:

```bash
vanessa@vanessa-ThinkPad-T450s:~$ singularity shell docker://blacklabelops/centos   
INFO:python:Docker image path: index.docker.io/blacklabelops/centos:latest
INFO:python:Cache folder set to /home/vanessa/.singularity/docker
Importing: base Singularity environment
Exploding layer: sha256:45a2e645736c4c66ef34acce2407ded21f7a9b231199d3b92d6c9776df264729.tar.gz
Exploding layer: sha256:9b1c42aabd4ab6bc9f1d5b9adc09373129d740829435a6272c9b15b1f57eb9bd.tar.gz
Exploding layer: sha256:31ed0535b3812c1058299c63d15e1c838f80900d0d269cde4f0f933a5886c782.tar.gz
Singularity: Invoking an interactive shell within container...

Singularity centos:~> 
```

and note with `--debug` there were a ton of print lines about changing permissions. So I think this is the correct thing to do.

**Comment by gmkurtzer** [comment]
Looks great, thanks!

**Pull request merged**
