### PR TITLE
Fix 'singularity build' when there's no "which" command installed

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

This fixes the `singularity build` command when there is no "which" command installed.

**This fixes or addresses the following GitHub issues:**

- Ref: #1078

**Checkoff for all PRs:**

- [*] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [*] I have tested this PR locally with a `make test`
   I have but it is failing for an unrelated problem, apparently with singularity hub
- [*] This PR is NOT against the project's master branch
- [*] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [*] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Review by GodloveD — APPROVED** [review]
Oh thanks.  This is a good change and should be merged asap.

**Comment by vsoch** [comment]
The errors are due to the DNS being cached about another ~18 hours, after that #1077 will pass and needs to be merged, then this should be green too :)

**Comment by gmkurtzer** [comment]
Crossing fingers, I just re-triggered a build...

**Comment by GodloveD** [comment]
This is failing because it doesn't have the updated python bits from https://github.com/singularityware/singularity/pull/1077 .  We need to merge that and then @DrDaveD can merge development into this.  After that is should build without trouble.  

@gmkurtzer can you look over https://github.com/singularityware/singularity/pull/1077 real quick and tell if it is ready to go.  I already gave thumbs up.

**Comment by gmkurtzer** [comment]
All merged in, thanks everyone!

**Pull request merged**
