### PR TITLE
Add the underlay feature

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

This PR builds on pull request #1624 to add the underlay feature described in issue #1207.  Most of the code changes are in the underlying PR, not yet merged at this time, and they are included here.  #1624 should be merged first.  Meanwhile, to see only the changes for this PR see this separate [PR](https://github.com/DrDaveD/singularity/pull/1) that I created between the two branches in my own github area.

**This fixes or addresses the following GitHub issues:**

- Ref: #1207

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by DrDaveD** [comment]
Rebased against current pr #1624 (which was rebased against current development-2.x).

**Comment by DrDaveD** [comment]
Closing and reopening to try to trigger travis build.

**Comment by DrDaveD** [comment]
Rebased again against current pr #1624 (which was rebased against current development-2.x).

**Comment by jthiltges** [comment]
I've done some initial testing with Dave's underlay patch and it seems to work fine on a SL 6.9 cluster:

- `bind path` entries from singularity.conf were OK
- `--bind` arguments for local filesystems were OK (tested one, two, and three argument forms, with `ro` and `rw` working as expected)
- No apparent issues with the existing bind mounts from our SLURM job environment

We have EL6 clusters with various local filesystems: /work, /scratch, etc. (I believe this is a common pattern for most HPC sites.) We maintain local images with the mount points pre-created, but it would be handy--and a time-saver for users and support staff--to allow generic shub or docker images to run unmodified.

**Comment by DrDaveD** [comment]
Rebased again against current pr #1624 (which was rebased against current development-2.x).

**Comment by DrDaveD** [comment]
Closing & reopening to re-trigger travis.

**Comment by DrDaveD** [comment]
Travis seems to have failed with a transit failure on el6 only, closing & reopening to trigger build again.

**Comment by DrDaveD** [comment]
Triggering travis again.

**Comment by afortiorama** [comment]
We tested the patch for the ATLAS workflows on the grid and it now works well for us. We tested it under the following conditions

- SL6/CentOS7 and other non RH OS with more recent kernels
-  --containall and without
- with and without suid enabled
- with unpacked images in CVMFS and with file images

We have 10ths of sites with very different file systems configurations and mount points that need to be accessed by containerized jobs. So far we have worked with overlay, but this doesn't cover all the situations. So we need the underlay feature to replace it. In particular overlay doesn't work

- with unpacked images in CVMFS. This is a long standing problem being tracked https://github.com/singularityware/singularity/issues/943 and https://sft.its.cern.ch/jira/browse/CVM-1434
- to disable suid and use user name spaces in the future. 

from the current testing we think underlay can replace overlay completely for us.

**Comment by paulhopkins** [comment]
I have also tested this patch on SL6 using LIGO images distributed over CVMFS and found that it has worked well. The inclusion of this feature would accelerate adoption of Singularity within the LSC.

**Comment by DrDaveD** [comment]
@afortiorama's testing was quite thorough, and she in fact found a bug, which I already [fixed](https://github.com/singularityware/singularity/pull/1638/commits/d450efb6351d37ac45cecd48ed1a472a162bef3c).

**Comment by GodloveD** [comment]
Hey @DrDaveD between this and the other PR this is a pretty massive amount of code to review.  It's my understanding that @bauerm97 has reached out to you about trying to incorporate this idea into 3.0 since that is where most of our effort is concentrated.  What do you think about working this into 3.0?

**Comment by DrDaveD** [comment]
@godloved Yes I do plan to do that at some point, but as I told @bauerm97 I won't be able to get to it for at least a month and a half.  There are many people who want this feature, and I do not expect 3.0 to be stable enough for their production use until at least the end of the year, so I do think it is important for this to be in 2.6.

**Comment by DrDaveD** [comment]
Rebased again on current pr #1624

**Comment by DrDaveD** [comment]
Closing & reopening to re-trigger travis.  Expect Debian travis builds to fail.

**Comment by DrDaveD** [comment]
Rebased again on updated delayed-mount, closing & reopening for travis.

**Comment by DrDaveD** [comment]
Closing & reopening for travis again after patch.

**Comment by DrDaveD** [comment]
Rebased on pr #1624 after it was rebased on 2.6.0-rc2 tag.  Closing & reopening for travis.

**Comment by DrDaveD** [comment]
Kicking travis again.

**Comment by DrDaveD** [comment]
@godloved I can't reopen, please reopen it.  I rebased again against pr #1624 which was rebased against release-2.6.

**Comment by GodloveD** [comment]
@DrDaveD we've had several conversations about this through PM and email. Seems pretty clear that there is no appetite on our end to merge this into the 2.x branch right? And the 2.x branch is now officially closed to new features. That being the case, I'm sorry but I don't see a point in re-opening this PR.

Thanks very much for your contributions. I encourage you to switch any development efforts you wish to make to the master branch (formerly development-3.0).

**Pull request closed without merging**
