### PR TITLE
Update missing dependencies on INSTALL.md

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Signed-off-by: ArangoGutierrez <eduardo@sylabs.io>

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by GodloveD — CHANGES_REQUESTED** [review]
Did you try this?  I think it will fail because you did not include `pkg-config`.

**Comment by ArangoGutierrez** [comment]
@GodloveD it works like that , look at our CI scripts 
https://github.com/sylabs/singularity/blob/master/.circleci/config.yml#L37

**Comment by GodloveD** [comment]
Try with a fresh Ubuntu 18 VM.  Here is what I got.
```
vagrant@ubuntu-bionic:~/go/src/github.com/sylabs/singularity/builddir$ make
 CC src/runtime/c/lib/util/capability.c
 CC src/runtime/c/lib/util/message.c
 CC src/runtime/c/lib/util/setns.c
 AR src/runtime/c/lib/util/libutil.a
 CSCOPE
 DEPENDS
 AR lib/libruntime.a
 VENDORS
 GO singularity
# pkg-config --cflags  -- libseccomp libseccomp
pkg-config: exec: "pkg-config": executable file not found in $PATH
Makefile:235: recipe for target 'singularity' failed
make: *** [singularity] Error 2
```

**Comment by ArangoGutierrez** [comment]
@GodloveD  b6051da  adds "pkg-config"

**Comment by GodloveD** [comment]
Also would you mind breaking the dependencies into a few lines with `\` so that they do not scroll off of the screen?

**Comment by ArangoGutierrez** [comment]
@GodloveD in my 55 inches screen I can read them with no problem :stuck_out_tongue_winking_eye:

**Comment by GodloveD** [comment]
Us old folks that have to hit Ctrl + a few times to read any text have problems.

**Review by GodloveD — APPROVED** [review]

**Comment by GodloveD** [comment]
lgtm whenever travis is happy

**Pull request merged**
