### PR TITLE
Add Fedora bootstrap example

### PR DESCRIPTION
**Pull request by wpoely86**
This adds a bootstrap example for Fedora. It required some changes to the `build-yum.sh`. It only has support for `baseurl` in the repo configuration. This caused problems for Fedora: often a mirror is not fully up to date resulting in many 404 errors during bootstrapping. This PR also adds support to use `metalink` in the repo configuration. This fetches a list of mirrors and continues if it hits a 404 on one mirror.

ToDo: update docs.

@singularityware-admin

### CODE REVIEW

**Comment by gmkurtzer** [comment]
Does it make sense to make a new Bootstrap module for `dnf` instead? If so, do you want to take a stab at this?

Also,... It might be worth while to submit into the lib-refactor as significant development is occurring there which affects bootstrapping, and it will soon be merged to the development branch, and from there back into master.

Thanks!

**Comment by wpoely86** [comment]
I don't think it is currently worth the trouble to separate yum and dnf. Both CLI and config files are still mostly the same and the difference for bootstrapping are tiny.

I'm rebasing my changes to the lib-refactor branch but I cannot create images any more:
```
$ sudo singularity -vvvv create  test7.img
increasing verbosity level (5)
ending argument loop
Exec'ing: /usr/libexec/singularity/cli/create.exec test7.img
VERBOSE [U=0,P=22945]      message_init()                            Set messagelevel to: 5
VERBOSE [U=0,P=22945]      singularity_suid_init()                   Running SUID program workflow
VERBOSE [U=0,P=22945]      singularity_suid_init()                   Checking program has appropriate permissions
VERBOSE [U=0,P=22945]      singularity_suid_init()                   Checking configuration file is properly owned by root
VERBOSE [U=0,P=22945]      singularity_suid_init()                   Checking if we were requested to run as NOSUID by user
VERBOSE [U=0,P=22945]      singularity_registry_init()               Initializing Singularity Registry
VERBOSE [U=0,P=22945]      singularity_registry_set()                Adding value to registry: 'WRITABLE' = '1'
DEBUG   [U=0,P=22945]      singularity_registry_set()                Returning singularity_registry_set(WRITABLE, 1) = 0
VERBOSE [U=0,P=22945]      singularity_registry_set()                Adding value to registry: 'LIBEXECDIR' = '/usr/libexec'
DEBUG   [U=0,P=22945]      singularity_registry_set()                Returning singularity_registry_set(libexecdir, /usr/libexec) = 0
VERBOSE [U=0,P=22945]      singularity_registry_set()                Adding value to registry: 'COMMAND' = 'create'
DEBUG   [U=0,P=22945]      singularity_registry_set()                Returning singularity_registry_set(COMMAND, create) = 0
VERBOSE [U=0,P=22945]      singularity_registry_set()                Adding value to registry: 'MESSAGELEVEL' = '5'
DEBUG   [U=0,P=22945]      singularity_registry_set()                Returning singularity_registry_set(MESSAGELEVEL, 5) = 0
VERBOSE [U=0,P=22945]      singularity_registry_set()                Adding value to registry: 'LOCALSTATEDIR' = '/var'
DEBUG   [U=0,P=22945]      singularity_registry_set()                Returning singularity_registry_set(localstatedir, /var) = 0
VERBOSE [U=0,P=22945]      singularity_registry_set()                Adding value to registry: 'SYSCONFDIR' = '/etc'
DEBUG   [U=0,P=22945]      singularity_registry_set()                Returning singularity_registry_set(sysconfdir, /etc) = 0
VERBOSE [U=0,P=22945]      singularity_registry_set()                Adding value to registry: 'IMAGE' = 'test7.img'
DEBUG   [U=0,P=22945]      singularity_registry_set()                Returning singularity_registry_set(IMAGE, test7.img) = 0
VERBOSE [U=0,P=22945]      singularity_config_parse()                Initialize configuration file: /etc/singularity/singularity.conf
DEBUG   [U=0,P=22945]      singularity_config_parse()                Starting parse of configuration file /etc/singularity/singularity.conf
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key allow setuid = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key allow pid ns = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key allow user image = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key protected image mode = 'none'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key enable overlay = 'no'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key config passwd = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key config group = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key config resolv_conf = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key mount proc = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key mount sys = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key mount dev = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key mount home = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key mount tmp = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key mount hostfs = 'no'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key bind path = '/etc/hosts'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key user bind control = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key mount slave = 'yes'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key container dir = '/var/lib/singularity/mnt'
VERBOSE [U=0,P=22945]      singularity_config_parse()                Got config key singularity user = 'singularity'
DEBUG   [U=0,P=22945]      singularity_config_parse()                Finished parsing configuration file '/etc/singularity/singularity.conf'
DEBUG   [U=0,P=22945]      singularity_priv_init()                   Initializing user info
DEBUG   [U=0,P=22945]      singularity_priv_init()                   Marking uinfo structure as ready
DEBUG   [U=0,P=22945]      singularity_priv_init()                   Obtaining home directory
VERBOSE [U=0,P=22945]      singularity_priv_init()                   Set the home directory source (via getpwuid()) to: /root
DEBUG   [U=0,P=22945]      singularity_priv_drop()                   Running as root, not changing privileges
INFO    [U=0,P=22945]      main()                                    Initializing Singularity image subsystem
DEBUG   [U=0,P=22945]      singularity_registry_get()                Retriving value from registry: 'IMAGE' = 'test7.img'
INFO    [U=0,P=22945]      main()                                    Opening image file: test7.img
DEBUG   [U=0,P=22945]      singularity_image_open()                  Opening file descriptor to image: test7.img
INFO    [U=0,P=22945]      main()                                    Creating 768MiB image
VERBOSE [U=0,P=22945]      singularity_image_create()                Writing image header
VERBOSE [U=0,P=22945]      singularity_image_create()                Growing image to 768MB
VERBOSE [U=0,P=22945]      singularity_image_create()                Making image executable
INFO    [U=0,P=22945]      main()                                    Binding image to loop
DEBUG   [U=0,P=22945]      singularity_config_get_value_impl()       No configuration entry found for 'sessiondir prefix'; returning default value '/tmp/.singularity-session-'
DEBUG   [U=0,P=22945]      singularity_image_sessiondir_init()       Got sessiondir_prefix from configuration: '/tmp/.singularity-session-'
DEBUG   [U=0,P=22945]      singularity_image_sessiondir_init()       Set sessiondir_prefix to: /tmp/.singularity-session-
DEBUG   [U=0,P=22945]      singularity_image_sessiondir_init()       Set sessiondir_suffix to: 0.2065.41943248
VERBOSE [U=0,P=22945]      singularity_registry_set()                Adding value to registry: 'SESSIONDIR' = '/tmp/.singularity-session-0.2065.41943248'
DEBUG   [U=0,P=22945]      singularity_registry_set()                Returning singularity_registry_set(sessiondir, /tmp/.singularity-session-0.2065.41943248) = 0
VERBOSE [U=0,P=22945]      singularity_image_sessiondir_init()       Creating session directory: /tmp/.singularity-session-0.2065.41943248
DEBUG   [U=0,P=22945]      singularity_image_sessiondir_init()       Opening sessiondir file descriptor
DEBUG   [U=0,P=22945]      singularity_image_sessiondir_init()       Setting shared flock() on session directory
DEBUG   [U=0,P=22945]      singularity_image_bind()                  Entered singularity_image_bind()
DEBUG   [U=0,P=22945]      singularity_image_bind()                  Opening image loop device file: /tmp/.singularity-session-0.2065.41943248/loop_lock
DEBUG   [U=0,P=22945]      singularity_image_bind()                  Requesting exclusive flock() on loop_dev lockfile
DEBUG   [U=0,P=22945]      singularity_image_bind()                  Calculating image offset
VERBOSE [U=0,P=22945]      singularity_image_check()                 Checking that file pointer is a Singularity image
DEBUG   [U=0,P=22945]      singularity_image_check()                 First line of image(fd=4): #!/usr/bin/env run-singularity
DEBUG   [U=0,P=22945]      singularity_image_check()                 Checking if first line matches key
VERBOSE [U=0,P=22945]      singularity_image_check()                 File is a valid Singularity image
VERBOSE [U=0,P=22945]      singularity_image_offset()                Calculating image offset
VERBOSE [U=0,P=22945]      singularity_image_offset()                Found image at an offset of 31 bytes
DEBUG   [U=0,P=22945]      singularity_image_offset()                Returning image_offset(image_fp) = 31
DEBUG   [U=0,P=22945]      singularity_priv_escalate()               Running as root, not changing privileges
DEBUG   [U=0,P=22945]      singularity_image_bind()                  Finding next available loop device...
VERBOSE [U=0,P=22945]      singularity_image_bind()                  Found available loop device: /dev/loop0
DEBUG   [U=0,P=22945]      singularity_image_bind()                  Setting loop device flags
DEBUG   [U=0,P=22945]      singularity_priv_drop()                   Running as root, not changing privileges
VERBOSE [U=0,P=22945]      singularity_image_bind()                  Using loop device: /dev/loop0
DEBUG   [U=0,P=22945]      singularity_image_bind()                  Writing active loop device name (/dev/loop0) to loop file cache: /tmp/.singularity-session-0.2065.41943248/loop_lock
DEBUG   [U=0,P=22945]      fileput()                                 Called fileput(/tmp/.singularity-session-0.2065.41943248/loop_lock, /dev/loop0)
DEBUG   [U=0,P=22945]      singularity_image_bind()                  Resetting exclusive flock() to shared on lockfile
DEBUG   [U=0,P=22945]      main()                                    Cleaning environment
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: LC_PAPER
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: LC_MONETARY
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: HOSTNAME
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SINGULARITY_WRITABLE
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: TERM
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SHELL
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: HISTSIZE
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: LC_NUMERIC
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: QTDIR
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SINGULARITY_libexecdir
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SINGULARITY_COMMAND
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: USER
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SINGULARITY_MESSAGELEVEL
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: LS_COLORS
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SUDO_USER
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SUDO_UID
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: USERNAME
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: MAIL
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: PATH
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SINGULARITY_localstatedir
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: NEW_HOME
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: PWD
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: LANG
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: LC_MEASUREMENT
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: RETVAL
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: HOME
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SUDO_COMMAND
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SHLVL
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SINGULARITY_sysconfdir
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: LOGNAME
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: DISPLAY
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SUDO_GID
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: CHANGE_HOME
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: SINGULARITY_IMAGE
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: LC_TIME
DEBUG   [U=0,P=22945]      envclean()                                Unsetting environment variable: COLORTERM
DEBUG   [U=0,P=22945]      singularity_priv_escalate()               Running as root, not changing privileges
INFO    [U=0,P=22945]      main()                                    Creating file system within image
DEBUG   [U=0,P=22945]      prepare_fork()                            Creating parent/child coordination pipes.
VERBOSE [U=0,P=22945]      singularity_fork()                        Forking child process
VERBOSE [U=0,P=22945]      singularity_fork()                        Hello from parent process
DEBUG   [U=0,P=22945]      singularity_fork()                        Assigning sigaction()s
DEBUG   [U=0,P=22945]      singularity_fork()                        Creating generic signal pipes
DEBUG   [U=0,P=22945]      singularity_fork()                        Creating sigchld signal pipes
DEBUG   [U=0,P=22945]      singularity_fork()                        Dropping permissions
DEBUG   [U=0,P=22945]      singularity_priv_drop()                   Running as root, not changing privileges
DEBUG   [U=0,P=22945]      singularity_fork()                        Waiting on signal from watchdog
VERBOSE [U=0,P=22952]      singularity_fork()                        Hello from child process
DEBUG   [U=0,P=22952]      singularity_fork()                        Closing watchdog write pipe
DEBUG   [U=0,P=22952]      singularity_fork()                        Child process is returning control to process thread
VERBOSE [U=0,P=22952]      singularity_fork_exec()                   Running child program: /sbin/mkfs.ext3
ext2fs_create_resize_inode: Invalid argument while reserving blocks for online resize
DEBUG   [U=0,P=22945]      singularity_fork()                        Parent process is exiting
DEBUG   [U=0,P=22945]      singularity_fork_exec()                   Waiting on child process
DEBUG   [U=0,P=22945]      singularity_fork_exec()                   Returning from singularity_fork_exec with: 1
DEBUG   [U=0,P=22945]      singularity_priv_drop()                   Running as root, not changing privileges
INFO    [U=0,P=22945]      main()                                    Image is done: test7.img
```

The error `ext2fs_create_resize_inode: Invalid argument while reserving blocks for online resize` is the cause. Are already aware of this?

**Comment by vsoch** [comment]
Just to clarify - this is with a fresh clone of lib-refactor and install? Did you clean out the old singularity install directory (eg, `/usr/local/lib/singularity`)? I tried to replicate your error, and I couldn't:

	sudo singularity -vvvv create  test7.img
	increasing verbosity level (5)
	ending argument loop
	Exec'ing: /usr/local/libexec/singularity/cli/create.exec test7.img
	VERBOSE [U=0,P=7622]       message_init()                            Set messagelevel to: 5
	VERBOSE [U=0,P=7622]       singularity_suid_init()                   Running SUID program workflow
	VERBOSE [U=0,P=7622]       singularity_suid_init()                   Checking program has appropriate permissions
	VERBOSE [U=0,P=7622]       singularity_suid_init()                   Checking configuration file is properly owned by root
	VERBOSE [U=0,P=7622]       singularity_suid_init()                   Checking if we were requested to run as NOSUID by user
	VERBOSE [U=0,P=7622]       singularity_registry_init()               Initializing Singularity Registry
	VERBOSE [U=0,P=7622]       singularity_registry_set()                Adding value to registry: 'WRITABLE' = '1'
	DEBUG   [U=0,P=7622]       singularity_registry_set()                Returning singularity_registry_set(WRITABLE, 1) = 0
	VERBOSE [U=0,P=7622]       singularity_registry_set()                Adding value to registry: 'LIBEXECDIR' = '/usr/local/libexec'
	DEBUG   [U=0,P=7622]       singularity_registry_set()                Returning singularity_registry_set(libexecdir, /usr/local/libexec) = 0
	VERBOSE [U=0,P=7622]       singularity_registry_set()                Adding value to registry: 'COMMAND' = 'create'
	DEBUG   [U=0,P=7622]       singularity_registry_set()                Returning singularity_registry_set(COMMAND, create) = 0
	VERBOSE [U=0,P=7622]       singularity_registry_set()                Adding value to registry: 'MESSAGELEVEL' = '5'
	DEBUG   [U=0,P=7622]       singularity_registry_set()                Returning singularity_registry_set(MESSAGELEVEL, 5) = 0
	VERBOSE [U=0,P=7622]       singularity_registry_set()                Adding value to registry: 'LOCALSTATEDIR' = '/usr/local/var'
	DEBUG   [U=0,P=7622]       singularity_registry_set()                Returning singularity_registry_set(localstatedir, /usr/local/var) = 0
	VERBOSE [U=0,P=7622]       singularity_registry_set()                Adding value to registry: 'SYSCONFDIR' = '/usr/local/etc'
	DEBUG   [U=0,P=7622]       singularity_registry_set()                Returning singularity_registry_set(sysconfdir, /usr/local/etc) = 0
	VERBOSE [U=0,P=7622]       singularity_registry_set()                Adding value to registry: 'IMAGE' = 'test7.img'
	DEBUG   [U=0,P=7622]       singularity_registry_set()                Returning singularity_registry_set(IMAGE, test7.img) = 0
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Initialize configuration file: /usr/local/etc/singularity/singularity.conf
	DEBUG   [U=0,P=7622]       singularity_config_parse()                Starting parse of configuration file /usr/local/etc/singularity/singularity.conf
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key allow setuid = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key allow pid ns = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key allow user image = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key protected image mode = 'none'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key enable overlay = 'no'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key config passwd = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key config group = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key config resolv_conf = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key mount proc = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key mount sys = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key mount dev = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key mount home = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key mount tmp = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key mount hostfs = 'no'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key bind path = '/etc/hosts'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key user bind control = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key mount slave = 'yes'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key container dir = '/var/lib/singularity/mnt'
	VERBOSE [U=0,P=7622]       singularity_config_parse()                Got config key singularity user = 'singularity'
	DEBUG   [U=0,P=7622]       singularity_config_parse()                Finished parsing configuration file '/usr/local/etc/singularity/singularity.conf'
	DEBUG   [U=0,P=7622]       singularity_priv_init()                   Initializing user info
	DEBUG   [U=0,P=7622]       singularity_priv_init()                   Marking uinfo structure as ready
	DEBUG   [U=0,P=7622]       singularity_priv_init()                   Obtaining home directory
	VERBOSE [U=0,P=7622]       singularity_priv_init()                   Set the home directory source (via getpwuid()) to: /root
	DEBUG   [U=0,P=7622]       singularity_priv_drop()                   Running as root, not changing privileges
	INFO    [U=0,P=7622]       main()                                    Initializing Singularity image subsystem
	DEBUG   [U=0,P=7622]       singularity_registry_get()                Retriving value from registry: 'IMAGE' = 'test7.img'
	INFO    [U=0,P=7622]       main()                                    Opening image file: test7.img
	DEBUG   [U=0,P=7622]       singularity_image_open()                  Opening file descriptor to image: test7.img
	INFO    [U=0,P=7622]       main()                                    Creating 768MiB image
	VERBOSE [U=0,P=7622]       singularity_image_create()                Writing image header
	VERBOSE [U=0,P=7622]       singularity_image_create()                Growing image to 768MB
	VERBOSE [U=0,P=7622]       singularity_image_create()                Making image executable
	INFO    [U=0,P=7622]       main()                                    Binding image to loop
	DEBUG   [U=0,P=7622]       singularity_config_get_value_impl()       No configuration entry found for 'sessiondir prefix'; returning default value '/tmp/.singularity-session-'
	DEBUG   [U=0,P=7622]       singularity_image_sessiondir_init()       Got sessiondir_prefix from configuration: '/tmp/.singularity-session-'
	DEBUG   [U=0,P=7622]       singularity_image_sessiondir_init()       Set sessiondir_prefix to: /tmp/.singularity-session-
	DEBUG   [U=0,P=7622]       singularity_image_sessiondir_init()       Set sessiondir_suffix to: 0.64512.28450221
	VERBOSE [U=0,P=7622]       singularity_registry_set()                Adding value to registry: 'SESSIONDIR' = '/tmp/.singularity-session-0.64512.28450221'
	DEBUG   [U=0,P=7622]       singularity_registry_set()                Returning singularity_registry_set(sessiondir, /tmp/.singularity-session-0.64512.28450221) = 0
	VERBOSE [U=0,P=7622]       singularity_image_sessiondir_init()       Creating session directory: /tmp/.singularity-session-0.64512.28450221
	DEBUG   [U=0,P=7622]       s_mkpath()                                Creating directory: /tmp/.singularity-session-0.64512.28450221
	DEBUG   [U=0,P=7622]       singularity_image_sessiondir_init()       Opening sessiondir file descriptor
	DEBUG   [U=0,P=7622]       singularity_image_sessiondir_init()       Setting shared flock() on session directory
	DEBUG   [U=0,P=7622]       singularity_image_bind()                  Entered singularity_image_bind()
	DEBUG   [U=0,P=7622]       singularity_image_bind()                  Opening image loop device file: /tmp/.singularity-session-0.64512.28450221/loop_lock
	DEBUG   [U=0,P=7622]       singularity_image_bind()                  Requesting exclusive flock() on loop_dev lockfile
	DEBUG   [U=0,P=7622]       singularity_image_bind()                  Calculating image offset
	VERBOSE [U=0,P=7622]       singularity_image_check()                 Checking that file pointer is a Singularity image
	DEBUG   [U=0,P=7622]       singularity_image_check()                 First line of image(fd=4): #!/usr/bin/env run-singularity

	DEBUG   [U=0,P=7622]       singularity_image_check()                 Checking if first line matches key
	VERBOSE [U=0,P=7622]       singularity_image_check()                 File is a valid Singularity image
	VERBOSE [U=0,P=7622]       singularity_image_offset()                Calculating image offset
	VERBOSE [U=0,P=7622]       singularity_image_offset()                Found image at an offset of 31 bytes
	DEBUG   [U=0,P=7622]       singularity_image_offset()                Returning image_offset(image_fp) = 31
	DEBUG   [U=0,P=7622]       singularity_priv_escalate()               Running as root, not changing privileges
	DEBUG   [U=0,P=7622]       singularity_image_bind()                  Finding next available loop device...
	VERBOSE [U=0,P=7622]       singularity_image_bind()                  Found available loop device: /dev/loop0
	DEBUG   [U=0,P=7622]       singularity_image_bind()                  Setting loop device flags
	DEBUG   [U=0,P=7622]       singularity_priv_drop()                   Running as root, not changing privileges
	VERBOSE [U=0,P=7622]       singularity_image_bind()                  Using loop device: /dev/loop0
	DEBUG   [U=0,P=7622]       singularity_image_bind()                  Writing active loop device name (/dev/loop0) to loop file cache: /tmp/.singularity-session-0.64512.28450221/loop_lock
	DEBUG   [U=0,P=7622]       fileput()                                 Called fileput(/tmp/.singularity-session-0.64512.28450221/loop_lock, /dev/loop0)
	DEBUG   [U=0,P=7622]       singularity_image_bind()                  Resetting exclusive flock() to shared on lockfile
	DEBUG   [U=0,P=7622]       main()                                    Cleaning environment
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SINGULARITY_WRITABLE
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: TERM
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SHELL
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SINGULARITY_libexecdir
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SINGULARITY_COMMAND
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: USER
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SINGULARITY_MESSAGELEVEL
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: LS_COLORS
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SUDO_USER
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SUDO_UID
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: USERNAME
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: PATH
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: MAIL
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SINGULARITY_localstatedir
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: NEW_HOME
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: PWD
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: LANG
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: RETVAL
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: HOME
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SUDO_COMMAND
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SHLVL
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: LANGUAGE
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SINGULARITY_sysconfdir
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: LOGNAME
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: DISPLAY
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SUDO_GID
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: CHANGE_HOME
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: SINGULARITY_IMAGE
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: XAUTHORITY
	DEBUG   [U=0,P=7622]       envclean()                                Unsetting environment variable: COLORTERM
	DEBUG   [U=0,P=7622]       singularity_priv_escalate()               Running as root, not changing privileges
	INFO    [U=0,P=7622]       main()                                    Creating file system within image
	DEBUG   [U=0,P=7622]       prepare_fork()                            Creating parent/child coordination pipes.
	VERBOSE [U=0,P=7622]       singularity_fork()                        Forking child process
	VERBOSE [U=0,P=7622]       singularity_fork()                        Hello from parent process
	DEBUG   [U=0,P=7622]       singularity_fork()                        Assigning sigaction()s
	DEBUG   [U=0,P=7622]       singularity_fork()                        Creating generic signal pipes
	DEBUG   [U=0,P=7622]       singularity_fork()                        Creating sigchld signal pipes
	DEBUG   [U=0,P=7622]       singularity_fork()                        Dropping permissions
	DEBUG   [U=0,P=7622]       singularity_priv_drop()                   Running as root, not changing privileges
	DEBUG   [U=0,P=7622]       singularity_fork()                        Waiting on signal from watchdog
	VERBOSE [U=0,P=7627]       singularity_fork()                        Hello from child process
	DEBUG   [U=0,P=7627]       singularity_fork()                        Closing watchdog write pipe
	DEBUG   [U=0,P=7627]       singularity_fork()                        Child process is returning control to process thread
	VERBOSE [U=0,P=7627]       singularity_fork_exec()                   Running child program: /sbin/mkfs.ext3
	DEBUG   [U=0,P=7622]       singularity_fork()                        Parent process is exiting
	DEBUG   [U=0,P=7622]       singularity_fork_exec()                   Waiting on child process
	DEBUG   [U=0,P=7622]       singularity_fork_exec()                   Returning from singularity_fork_exec with: 0
	DEBUG   [U=0,P=7622]       singularity_priv_drop()                   Running as root, not changing privileges
	INFO    [U=0,P=7622]       main()                                    Image is done: test7.img

what host are you trying this from? I could try that next...I'm just using Ubuntu. That might be the difference.

**Comment by wpoely86** [comment]
@vsoch this was on top of ccb228de9823019b6d25dca0e03561e0b1da6405 and I test it using: `./configure && make dist && rpmbuild --define "_sourcedir $PWD" -bb singularity.spec` and the rpm resulting from that.

I'm testing on top of Fedora 25. I will Ubuntu a spin too.

**Comment by vsoch** [comment]
I think it would be helpful, if you intend to merge this into a different branch, to adjust the PR to that branch. Then we can look at the differences in "files changed" and better understand what might be going wrong? The differences in `lib-refactor` vs. `master` are quite substantial, so it's probably a detail being missed. So - maybe open a new PR for this change specifically to lib refactor.

**Comment by wpoely86** [comment]
@vsoch I've tried with a Ubuntu 16.10 vm and it get exactly the same error. I didn't include any changes from this PR: the test was with ccb228d

**Comment by wpoely86** [comment]
Maybe I'm missing something but why does `singularity create` require root? It's the equivalent (more or less) of running:
```
dd if=/dev/zero of=test.img bs=1M count=1024
mkfs.ext3 -E offset=31 test.img
```
So I think the loopback can be dropped (and thus the root requirement)?

**Comment by wpoely86** [comment]
@vsoch it's rebased on `lib-refactor` and tested with CentOS 7 + Fedora 25.

**Comment by vsoch** [comment]
ok, it might be time then for @gmkurtzer to take a peek.

**Comment by gmkurtzer** [comment]
Merged into "development" branch. Thanks!

**Pull request closed without merging**
