### PR TITLE
Fix check for image type before image offset calculation

### LINKED ISSUE #817: SquashFS regression
WIth singularity v2.3.1-dist, I have trouble running some (not all) SquashFS images. The images run fine with v2.2.1, but with v2.3.1 I get

    ERROR  : Failed to mount squashfs image in (read only): Invalid argument
    ABORT  : Retval = 255

I can provide a container for testing - it's quite big, though (3.7 GB SquashFS image).

### PR DESCRIPTION
**Pull request by oschulz**
**Description of the Pull Request (PR):**

Fixes #817. Tested with the SquashFS file that used to fail, seems fine now.

**This fixes or addresses the following GitHub issues:**

- Ref: #817

**Checkoff for all PRs:**

- [X] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [X] I have tested this PR locally with a `make test`
- [ ] This PR is NOT against the project's master branch
- [ ] I have added myself as a contributor to the [Author's file](https://github.com/singularityware/singularity/blob/master/AUTHORS.md)
- [X] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by oschulz** [comment]
Or should we use

    if ( image->type != SINGULARITY )

instead of

    if ( image->type == SQUASHFS )

?

**Comment by vsoch** [comment]
Did you change, compile, and test? SQUASHFS I think just points to 2

**Comment by oschulz** [comment]
> Did you change, compile, and test? SQUASHFS I think just points to 2

No, currently it's still `if ( image->type == SQUASHFS )`. Should I change to `if ( image->type != SINGULARITY )`?

I wasn't sure which is better - currently, `_singularity_image_check` only distinguishes between `SINGULARITY`, `SQUASHFS` and `DIRECTORY`, so it doesn't matter much. But that might change, depending on what the future plans for Singularity are.

**Comment by vsoch** [comment]
I think generally we should follow a "match the right thing or fail" pattern, vs. a "match the right thing or go to some default." So given that we have (currently) three kinds:

```
#define SINGULARITY 1
#define SQUASHFS    2
#define DIRECTORY   3
```

I think it's reasonable that we have a very specific check for one type (SQUASHFS) and your suggestion

```
    if ( image->type == SQUASHFS ) {
        singularity_message(DEBUG, "File is a SquashFS image, returning zero offset\n");
          return(0);
 }
```
granted that it fixes the bug, and tests pass, seems reasonable to me. @gmkurtzer ? Does directory need some special case too? That would be the only other thing to check.

**Comment by oschulz** [comment]
I have a request - once this is merged, could it backported to 2.3 and could you make a 2.3.2 bugfix release? This is really a bit of a blocker for us at the moment, and in the past I had trouble convincing admins to install Singularity versions that are not official releases.

**Comment by gmkurtzer** [comment]
Hi @oschulz, I added and changed the fix in the development branch, can you test that?

Thanks!

**Comment by oschulz** [comment]
> Hi @oschulz, I added and changed the fix in the development branch, can you test that?

Thanks, @gmkurtzer - looks good, can use the image that failed before without problems now. Would a bugfix-release be possible? Or do you have a new release planned soon, anyhow?

**Comment by gmkurtzer** [comment]
@oschulz Yep, I can now use the image that was failing before, and also yes. I will merge this into master so it will be part of the next release.

Thanks!

**Comment by gmkurtzer** [comment]
This has been merged into master. I was hoping that GitHub will automatically realize that and close the PR, but it didn't so I'm closing it myself.

Thanks!

**Comment by oschulz** [comment]
Many thanks, Greg! Can you estimate when you'll do the next release, yet? Just so I know whether I can wait for the release, or will need to deploy an interim solution, in-house.

**Comment by gmkurtzer** [comment]
I am thinking 2.3.2 will be released in August sometime (perhaps towards the end), but don't hold me to it yet. ;)

**Comment by vsoch** [comment]
yeah so, in other words, (or Greg speak) maybe around Thanksgiving? hehe...

image <--- what he says

**Comment by GodloveD** [comment]
You've been drinking your hateraid this morning @vsoch?

**Comment by vsoch** [comment]
https://www.youtube.com/watch?v=3p6PYQVj5hE

**Comment by vsoch** [comment]
https://www.youtube.com/watch?v=7CzbXA53I24

**Comment by gmkurtzer** [comment]
Haha, and wow... So not work appropriate @vsoch!!! (which I completely support LOL)

**Comment by vsoch** [comment]
formetopoopon

**Pull request closed without merging**
