### PR TITLE
Update support.md (against master)

### PR DESCRIPTION
**Pull request by vsoch**
Development seems broken? See #1250 (not sure why, but I only changed one file in the interface and the testing didn't pass?) so giving this a second try, but against master.

Attn: @singularityware-admin

### CODE REVIEW

**Review by jmstover — APPROVED** [review]
These changes look good to me. If this gets merged, should we cherry pick the same commit back into the development branch so it doesn't get overwritten?

**Comment by vsoch** [comment]
Sure thing! I'd be happy to do that. :)

**Comment by GodloveD** [comment]
I'm going to suggest some changes to the text in a PR.  😄

**Comment by GodloveD** [comment]
Whoops!  I actually meant to send this to @vsoch as a PR, but I screwed up and pulled directly from the singularityware repo.  Oh well.  At least it wasn't from the main or development branches.  😅 Anyway, can you take a look at these proposed changes and approve/disapprove them @vsoch?  If you think it's good I think it's ready to merge.

**Review by GodloveD — APPROVED** [review]
Whoops! I actually meant to send this to @vsoch as a PR, but I screwed up and pulled directly from the singularityware repo. Oh well. At least it wasn't from the main or development branches. 😅 Anyway, can you take a look at these proposed changes and approve/disapprove them @vsoch? If you think it's good I think it's ready to merge.

**Comment by vsoch** [comment]
Looks ok to me :) Thanks @GodloveD !

**Comment by GodloveD** [comment]
OK.  I merged.  @vsoch do you want to send another PR against development that has these changes cherry-picked in?  Or is there a simpler way to do it?

**Comment by vsoch** [comment]
It's easier to just do fresh, I will take care of!

**Pull request merged**
