### PR TITLE
Do not forward 'SINGULARITY_'-variables from user to container environment

### PR DESCRIPTION
**Pull request by obreitwi**
**Description of the Pull Request (PR):**

If environmental variables starting with `SINGULARITY_` are present, they will overwrite the ones set on container start. This makes it hard, for instance, to identify the current container if - for some reason - `SINGULARITY_NAME`/`SINGULARITY_CONTAINER` is already set:

```
$ singularity exec ./container.img env | grep SINGULARITY_
SINGULARITY_APPNAME=
SINGULARITY_CONTAINER=/home/obreitwi/containers/container.img
SINGULARITY_NAME=container.img

$ SINGULARITY_NAME="foobar" SINGULARITY_CONTAINER="deadbeef" singularity exec ./container.img env | grep SINGULARITY_
SINGULARITY_APPNAME=
SINGULARITY_CONTAINER=deadbeef
SINGULARITY_NAME=foobar
```

With this fix:
```
$ SINGULARITY_NAME="foobar" SINGULARITY_CONTAINER="deadbeef" singularity exec ./container.img env | grep SINGULARITY_                                                                                                                                                                                            (0)[20499] 
SINGULARITY_APPNAME=
SINGULARITY_CONTAINER=/home/obreitwi/containers/container.img
SINGULARITY_NAME=container.img
```

**This fixes or addresses the following GitHub issues:**

_None opened._

**Before submitting a PR, make sure you have done the following:**

- [x] Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
 → small bugfix, none needed
- [ ] Added tests to validate this PR and tested this PR locally with a `make testall`
 → small bugfix, ~none~ apparently some needed - is being able to set `SINGULARITY_CONTAINER` from the outside a desired feature?
- [x] Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- [x] Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by obreitwi** [comment]
I should add that this problem is especially apparent in nested containers (see #2729).

**Comment by GodloveD** [comment]
Hey @obreitwi I was just doing some PR cleanup and I am shocked and dismayed that nobody has even commented on this!  I sincerely apologize!

**Review by GodloveD — APPROVED** [review]
This lgtm.  I believe we were doing something similar in 2.x but just omitted it in the 3.x series.

**Comment by GodloveD** [comment]
Looks like this is failing tests, but I'm pretty sure it is just because the tests need to be updated to reflect the fact that `SINGULARITY_*` variables will not be transposed into the container environment.

**Comment by GodloveD** [comment]
So, we've basically left you hanging on this for 2 and a half months, and then we have introduced a test that is broken with this PR in the meantime.  Under the circumstances, I don't really think it's realistic to ask you fix the tests up, so I'm just going to go ahead and take the liberty of pushing (hopefully) a fix.  😄

**Comment by GodloveD** [comment]
Thanks @obreitwi.  And once again, sorry that this fell through the cracks for a while.

**Comment by obreitwi** [comment]
> Thanks @obreitwi. And once again, sorry that this fell through the cracks for a while.

No problem, thank you for fixing the tests! :+1:

**Pull request merged**
