### PR TITLE
INSTALL.md version update

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
**INSTALL.md version update:**

minor update

Examples on [INSTALL.md](https://github.com/singularityware/singularity/blob/release-2.4/INSTALL.md) have an older version *2.3.1* , moved to *2.4*

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Review by GodloveD — CHANGES_REQUESTED** [review]
Nice catch.  Can you also add this as an item to the `.github/RELEASE_CHECKLIST.md`?

**Comment by GodloveD** [comment]
Also I'm putting the bug label on this so that it goes in 2.4.1, (although we had better change it for that version lol).

**Comment by ArangoGutierrez** [comment]
Sure I'll make the changes.
Thanks @GodloveD

**Comment by gmkurtzer** [comment]
I would like to make this more abstract so it doesn't specify a particular version at all. Perhaps just use the master branch?

**Pull request merged**
