### PR TITLE
1238 rebase SCIF Revision

### PR DESCRIPTION
**Pull request by dtrudg**
**Description of the Pull Request (PR):**

This is a rebase against development-2.x of #1238 SCIF revision from @vsoch

### CODE REVIEW

**Review by GodloveD — APPROVED** [review]
This has basically already been reviewed right?  So if Travis is happy, I am happy.

**Comment by dtrudg** [comment]
@GodloveD - yup. and there are SCIF tests running through Travis... so fingers crossed 🤞

**Comment by GodloveD** [comment]
:shipit:

**Comment by dtrudg** [comment]
Tests are good. Merging. Thanks for this stuff @vsoch !

**Comment by vsoch** [comment]
woohoo! Thank you @dctrud , this is so great! I'm really appreciative that you could fix things up :hugs:

**Pull request merged**
