### PR TITLE
Update instance command

### LINKED ISSUE #1709: instance.start return code
In spirit of the case that `instance.list` returns a 1 to be programatically accessible to scripts (and does not reflect the successful return of the command) I would expect the `singularity instance.start` command to also return a value that is meaningful for a script. My first expectation was returning the pid.  Currently, the return value is 0:

```bash
$ singularity instance.start ubuntu.simg hakuna_matata
$ echo $?
0
```
And the script would then have to iterate through the listing of containers, parse the text output, and figure out the pid based on a matching name. Is there a better / any easy way to do this? Just curious, why is the standard different between the two? As a suggestion, why not do like a bunch of programs do, and at least print the pid of the started container to the stdout? That way, we could use the return code of 0 to say "successfully started!" and then easily have a handle to the beastie thing we have unleahsed. Let me know what you would suggest as a workaround, in the meantime!

### PR DESCRIPTION
**Pull request by sashayakovtseva**
**Description of the Pull Request (PR):**

Functional changes:
- `instance list` now accepts optional argument to filter instances by glob
- `instance start` now has `--pid-file` option. If specified, instance PID will be written there after successful startup

Non-functional changes:
- instance cmds are not exported
- instance action functions are moved to the corresponding files, i.e. `listInstance` is now located in `internal/app/singularity/instance.go` rather than in `instance_linux.go`, etc
- different flags don't share the same global variable 

**This fixes or addresses the following GitHub issues:**

- Fixes #1709 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by sashayakovtseva** [comment]
@vsoch your feedback will be appreciated :)

**Review by mem — APPROVED** [review]

**Review by cclerget — COMMENTED** [review]
Some note based on slack discussion:

- move list/stop/kill instance code in `internal/app/singularity` instead
- help change `singularity instance list test*` to `singularity instance list 'test*'` to avoid `*` being evaluated by shell terminal

**Comment by vsoch** [comment]
Is this ready for a test or are there further changes to be done, per @cclerget comment?

**Comment by sashayakovtseva** [comment]
@vsoch changes will not affect CLI API, so feel free to test

**Comment by gvallee** [comment]
@sashayakovtseva The user documentation and issue #4086 will need to be updated because the user interface is modified. I am not saying that both need to be addressed right away but if issues are not created/updated it is not possible for the team to track what is required at release time.

**Comment by vsoch** [comment]
okay, testing! I will review functional commands here.

No instances started
```bash
$ singularity instance list
INSTANCE NAME    PID      IMAGE
```
Start a single instance

```bash
$ singularity instance start docker://busybox mrbigglesworth
INFO:    instance started successfully
```
List again
```bash
$ singularity instance list
INSTANCE NAME    PID      IMAGE
mrbigglesworth   1000     /home/vanessa/.singularity/cache/oci-tmp/9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70/busybox_latest.sif
```
Try providing name as single argument

```bash
$ singularity instance list mrbigglesworth
INSTANCE NAME    PID      IMAGE
mrbigglesworth   1000     /home/vanessa/.singularity/cache/oci-tmp/9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70/busybox_latest.sif
```
Doesn't work with partial

```bash
$ singularity instance list mrbig
INSTANCE NAME    PID      IMAGE
```

Ask for json
```bash
$ singularity instance list --json mrbigglesworth 
{
	"instances": [
		{
			"instance": "mrbigglesworth",
			"pid": 1000,
			"img": "/home/vanessa/.singularity/cache/oci-tmp/9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70/busybox_latest.sif"
		}
	]
}
```
Start a second instance

```bash
$ singularity instance start docker://busybox meow
INFO:    instance started successfully
```
Now list both

```bash
$ singularity instance list
INSTANCE NAME    PID      IMAGE
meow             1213     /home/vanessa/.singularity/cache/oci-tmp/9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70/busybox_latest.sif
mrbigglesworth   1000     /home/vanessa/.singularity/cache/oci-tmp/9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70/busybox_latest.sif
```

Ask for both with json

```bash
$ singularity instance list --json
{
	"instances": [
		{
			"instance": "meow",
			"pid": 1213,
			"img": "/home/vanessa/.singularity/cache/oci-tmp/9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70/busybox_latest.sif"
		},
		{
			"instance": "mrbigglesworth",
			"pid": 1000,
			"img": "/home/vanessa/.singularity/cache/oci-tmp/9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70/busybox_latest.sif"
		}
	]
}
```

Now just ask for one!

```bash
$ singularity instance list --json meow
{
	"instances": [
		{
			"instance": "meow",
			"pid": 1213,
			"img": "/home/vanessa/.singularity/cache/oci-tmp/9f1003c480699be56815db0f8146ad2e22efea85129b5b5983d0e0fb52d9ab70/busybox_latest.sif"
		}
	]
}
```

Try --pid-file option - stop and start the instance:

```bash
$ singularity instance stop meow
$ singularity instance start --pid-file /tmp/meowmeowmeow meow
$ singularity instance start --pid-file /tmp/meowmeowmeow meow
Error for command "start": requires at least 2 arg(s), only received 1

Usage:
  singularity [global options...] instance start [start options...] <container path> <instance name> [startscript args...]

Run 'singularity instance start --help' for more detailed usage information.
```

Ah okay, so this is unlike Docker where you can stop a container, and start again referring to it's name, I would need to again provide the docker:// (or container) uri, is that correct?

```bash
$ singularity instance start --pid-file /tmp/meowmeowmeow docker://busybox meow
INFO:    instance started successfully
```
Get the pid in the file that should (and does!) exist:
```bash
$ cat /tmp/meowmeowmeow 
1648
```
inspect

```bash
$ ps -p 1648
  PID TTY          TIME CMD
 1648 ?        00:00:00 sinit
```

So that looks good! That's exactly what I was getting at in the issue - being able to inspect based on the name. Is there anything else I need to test?

**Comment by sashayakovtseva** [comment]
@vsoch Thanks, really appreciated!

> Doesn't work with partial

That is expected, a glob form should be used, i.e. `'mrbig*'`

**Comment by vsoch** [comment]
Yep I wanted to ensure that it wouldn't work (the test was meant to fail, which is a pass!) :)

**Review by vsoch — APPROVED** [review]
For what I reviewed (before the new commits) this meets the needs of the issues.

**Review by cclerget — APPROVED** [review]
LGTM, thanks !

**Comment by vsoch** [comment]
Thank you @sashayakovtseva !

**Pull request merged**
