### PR TITLE
Add --timeout and --force flag for oci kill command

### LINKED ISSUE #2806: Unable to delete OCI Container
I'm not able to delete an OCI image that is running no matter what I try:

```bash
i$ sudo singularity oci delete mycontainer
FATAL:   container is not stopped: running
```
Okay, it's running,and I can see that via it's state:

```bash
$ sudo singularity oci state mycontainer
{
	"ociVersion": "1.0.1-dev",
	"id": "mycontainer",
	"status": "running",
	"pid": 9981,
	"bundle": "/tmp/bundleo",
	"createdAt": 1551733595253713479,
	"startedAt": 1551733603560563021,
	"attachSocket": "/var/run/singularity/instances/root/mycontainer/attach.sock",
	"controlSocket": "/var/run/singularity/instances/root/mycontainer/control.sock"
}
```
So I'd try killing it, pausing it, etc.

```bash
$ sudo singularity oci pausel mycontainer
$ sudo singularity oci kill mycontainer
```
There aren't any errors so this means it must have worked! I can try deleting it now:

```bash
$ sudo singularity oci delete mycontainer
FATAL:   container is not stopped: running
```
omg, he's still running!

```bash
$ sudo singularity oci state mycontainer
{
	"ociVersion": "1.0.1-dev",
	"id": "mycontainer",
	"status": "running",
	"pid": 9981,
	"bundle": "/tmp/bundleo",
	"createdAt": 1551733595253713479,
	"startedAt": 1551733603560563021,
	"attachSocket": "/var/run/singularity/instances/root/mycontainer/attach.sock",
	"controlSocket": "/var/run/singularity/instances/root/mycontainer/control.sock"
}
```

How do I stop the container?

## Version of Singularity:

3.1.0

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR adds `--timeout` and `--force` command line option for `oci kill` command

**This fixes or addresses the following GitHub issues:**

- Fixes #2806

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by jscook2345** [comment]
`[vagrant@localhost tmp]$ FATAL:   EOF`

The following occurs in the shell where I `start`ed a oci container and than `kill --force` it. Not sure if that is an error or not.

**Comment by jscook2345** [comment]
`--timeout 0` does not seem to kill the oci container, where as `--timeout 10` and `--timeout 30` do.

**Comment by jscook2345** [comment]
Using `-s SIGTERM`, `-s TERM` or no signal kill `oci kill <container>` didn't seem to work for me. See issue #2845.

I was able to use `sudo singularity oci kill bb SIGKILL` from the version of singularity that does not include this PR.

**Comment by jscook2345** [comment]
Assuming the issues I raised are expected or me doing something weird (please let me know if so!) than I think this LGTM!

**Comment by jscook2345** [comment]
@cclerget If you can speak to my comments above, than I think we can get this merged today!

**Comment by cclerget** [comment]
@jscook2345 zero timeout is equal to no timeout. You noticed that a shell process as PID 1 doesn't respond to termination signals, this is a known issue which isn't specific to Singularity but all container runtimes

**Review by jscook2345 — APPROVED** [review]

**Pull request merged**
