### PR TITLE
Add cache deletion code for net and oras.

### LINKED ISSUE #3823: Cache clean command not making any effect
## Version of Singularity:

3.3.0-rc1

### Expected behavior

> ``singularity cache clean`` will now delete only sub-directories of SINGULARITY_CACHEDIR instead of the directory itself

### Actual behavior

No deletions occurred
```
sushma@Sushma-Ubuntu:~$ singularity cache clean
sushma@Sushma-Ubuntu:~$ cd .singularity/cache
sushma@Sushma-Ubuntu:~/.singularity/cache$ ls
library  net  oci-tmp  oras  shub
sushma@Sushma-Ubuntu:~/.singularity/cache$ cd library
sushma@Sushma-Ubuntu:~/.singularity/cache/library$ ls
sha256.b80bddda1d84d827ea135eb890f969a83ccba2a7a2152e15567d114857280120
sushma@Sushma-Ubuntu:~/.singularity/cache/library/sha256.b80bddda1d84d827ea135eb890f969a83ccba2a7a2152e15567d114857280120$ ls
busybox_latest.sif

sushma@Sushma-Ubuntu:~/.singularity/cache$ cd oras
sushma@Sushma-Ubuntu:~/.singularity/cache/oras$ ls
sha256:5e15d96e9a185c66e4e7c0f3ba4b96c383cba8e8769ed2c704906abecd6ef812
sha256:d48dba1449488d24d270a20a9b9c6144b79ded5e4971195bfd0e36f507a9436d
sha256:d7d0e0f5eeb6f14143a174b01c6c719d826cc7323ccff7a7f4d5c162e719aba7

```

### PR DESCRIPTION
**Pull request by phpHavok**
**Description of the Pull Request (PR):**

This PR adds missing cache deletion code for the net and oras types.

**This fixes or addresses the following GitHub issues:**

- Fixes #3823

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by phpHavok** [comment]
I just saw that @mem has a pending PR and this will create a merge conflict with that!

**Review by sushma-4 — APPROVED** [review]
Previously ``net`` and ``oras`` directories remained after ``cache clean --all`` command. However, with this PR all the directories were deleted. 
Thank you @phpHavok I hope this is what the PR is intended to perform.

**Comment by phpHavok** [comment]
> Previously `net` and `oras` directories remained after `cache clean --all` command. However, with this PR all the directories were deleted.
> Thank you @phpHavok I hope this is what the PR is intended to perform.

Thanks @sushma-4 , that is indeed what I intended :) I noticed they were missing from the code.

**Comment by jscook2345** [comment]
@ikaneshiro

It looks good to me, but can you please also review since we don't have full tests here yet?

**Review by ikaneshiro — APPROVED** [review]
LGTM, we should make a follow up issue to also add these to the `cache list` command as well. I'll go ahead and make that having as smaller PRs is better.

**Pull request merged**
