### PR TITLE
Arch Linux support for v2 format and a bunch of corrections here and there

### PR DESCRIPTION
**Pull request by czka**
@gmkurtzer

Please pay close attention to my "eval" calls before merging. It will be great help. I hope them right in all cases...

### CODE REVIEW

**Comment by gmkurtzer** [comment]
Looks great!

**Comment by gmkurtzer** [comment]
I fixed your copyright lines in [master be8a6e9]. I also think you should add MirrorURL to your definition file and possibly OSVersion too...

Thoughts?

**Comment by czka** [comment]
Thanks for accepting my contribution. That was fun :).

You are right about the copyright lines.

As for the backtick vs apostrophe - I'm using the former on purpose for tool names, sometimes code pieces etc. For other things I would use double quotes usually. A matter of style probably. See eg. `man find`, `man iptables`. This convention has long history - https://www.emacswiki.org/emacs/EmacsDocumentationNotation.

MirrorURL will not be used for anything by `pacstrap`. The tool uses host's mirrorlist only, and by default it even tries to copy them over to a new system. It's a rather simple shell script - 
https://git.archlinux.org/arch-install-scripts.git/tree/pacstrap.in. Also, it's expected on Arch system to have multiple mirror servers defined. Eg.:

```
$ cat /etc/pacman.d/mirrorlist
################################################################################
################# Arch Linux mirrorlist generated by Reflector #################
################################################################################

# With:       reflector --protocol https --sort rate --save /etc/pacman.d/mirrorlist
# When:       2015-11-02 22:16:46 UTC
# From:       https://www.archlinux.org/mirrors/status/json/
# Retrieved:  2015-11-02 22:16:29 UTC
# Last Check: 2015-11-02 22:11:45 UTC

Server = https://mirror.pseudoform.org/$repo/os/$arch
Server = https://ftp.lysator.liu.se/pub/archlinux/$repo/os/$arch
Server = https://archlinux.honkgong.info/$repo/os/$arch
Server = https://archlinux.limun.org/$repo/os/$arch
Server = https://mirrors.uni-plovdiv.net/archlinux/$repo/os/$arch
Server = https://ftp.myrveln.se/pub/linux/archlinux/$repo/os/$arch
Server = https://ftp.fau.de/archlinux/$repo/os/$arch
Server = https://mirror.fluxent.de/archlinux/$repo/os/$arch
Server = https://mirror.i3d.net/pub/archlinux/$repo/os/$arch
Server = https://arch.jensgutermuth.de/$repo/os/$arch
Server = https://mirror.fs.cx/archlinux/$repo/os/$arch
Server = https://arch.localmsp.org/arch/$repo/os/$arch
Server = https://mirror.js-webcoding.de/pub/archlinux/$repo/os/$arch
Server = https://archlinux.my-universe.com/$repo/os/$arch
Server = https://ftp.heanet.ie/mirrors/ftp.archlinux.org/$repo/os/$arch
Server = https://foss.aueb.gr/mirrors/linux/archlinux/$repo/os/$arch
Server = https://mirror.bitjungle.info/archlinux/$repo/os/$arch
Server = https://k42.ch/mirror/archlinux/$repo/os/$arch
Server = https://lug.mtu.edu/archlinux/$repo/os/$arch
Server = https://mirror.lty.me/archlinux/$repo/os/$arch
Server = https://mirrors.ocf.berkeley.edu/archlinux/$repo/os/$arch
Server = https://kwk.pw/arch/$repo/os/$arch
Server = https://www.mailtunnel.eu/archlinux/$repo/os/$arch
Server = https://archlinux.mirror.pkern.at/$repo/os/$arch
Server = https://mirrors.kernel.org/archlinux/$repo/os/$arch
Server = https://fooo.biz/archlinux/$repo/os/$arch
Server = https://mirrors.ustc.edu.cn/archlinux/$repo/os/$arch
Server = https://arch.static.lu/$repo/os/$arch
```

Given that, I can't see a use for MirrorURL in arch.def.

The concept of OSVersion does not fit Arch world. It's a rolling release ("OSVersion") by design. There are "tesing" and "unstable" repos (https://wiki.archlinux.org/index.php/Official_Repositories#testing), but the way they are enabled/disabled by the user does not mean anything in the context of the intended OSVersion use, as I get it at least.

 Is there some fundamental reason why it's better to have these set for Singularity anyway?

**Comment by gmkurtzer** [comment]
OK, that makes perfect sense. No fundamental reason why I want them set aside to keep in alignment with the other bootstraps. Would you be open to this?

```
OSType: arch
OSVersion: Null
MirrorURL: Null
```

Also, what about the "Include" directive which automatically installs additional packages. Is there a way to integrate that?

I have another question. Is it possible to make it such that Arch can be bootstrapped from a non-Arch system? For example, I think Arch has a bootstrap that can be used for this purpose.. You first download a minimal chroot, and then run the packstrap from there into a directory. Can we use that if someone wanted to run this from lets say... Ubuntu or Red Hat?

If not, it is fine, I just want to make sure that there is an Arch Linux base container that people can download. Do you know any of the Arch maintainers? Do you think they would be willing to also distribute a Singularity container from their download page?

Thanks again, and if you see anything else that needs fixing, please don't hesitate to jump in and send me a pull request!

**Comment by czka** [comment]
> Would you be open to this?

OK. But with a few words explaining what thoses `Null` entries mean. Otherwise it may look kindoff "intriguing" ;).

> what about the "Include" directive which automatically installs additional packages. Is there a way to integrate that?

Sure, but I decided it's an overhead, as one can install whatever extra packages he needs in `%post` with plain `pacman -Sy --noconfirm package1 package2 package3`. I believe that bootstrapping should be just it - installing a minimum required to get the system rolling. Anything above that is not a part of bootstrapping as I see it, and the `%post` section is a right place for that. If supporting the `Include` keyword in all bootstrap scripts is eg. crucial to further Singularity development please add whatever's needed in your opinion.

> Is it possible to make it such that Arch can be bootstrapped from a non-Arch system?

Never done it myself, but they are saying it's rather easy: https://wiki.archlinux.org/index.php/Install_from_Existing_Linux#From_a_host_running_another_Linux_distribution.

> Do you know any of the Arch maintainers?

Nope, sorry.

I was wondering about another thing. I have just succesfully built an i686 Arch image on an x86_64 Arch host. And it seems to run OK on that 64bit host. Should I expect any issues with such setup? Maybe Singularity bootstrap process could take such combination into account, if it's meant to be supported?

**Comment by gmkurtzer** [comment]
The point about the Null entries is just to show that these are standard keywords but this particular bootstrap definition doesn't take them. Maybe a comment or two.

Understood about the "Include" point. Maybe we can also add that as a Null option as well.

You bring up a really good point about arch! Maybe we should add a bootstrap keyword for OSArch!  And no, I do not anticipate any issue running 32bit on a 64bit kernel that supports multi-arch.

**Comment by czka** [comment]
> Maybe we should add a bootstrap keyword for OSArch!

I like the idea. Submitted in #210.

**Pull request merged**
