### PR TITLE
BF: tune ups for building on Debian buster and some exotic platforms lacking SIGSTKFLT

### PR DESCRIPTION
**Pull request by yarikoptic**
**Description of the Pull Request (PR):**

These changes were suggested in Debian : https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883466
so I have decided to provide them for your review/feedback before patching Debian package.

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [ ] I have tested this PR locally with a `make test`
- [ ] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by yarikoptic** [comment]
Dear @singularityware/singularity-admin , a review/feedback would have been very welcome!

**Comment by GodloveD** [comment]
Hey @yarikoptic sorry I'm late to the party here.  We are woefully behind on PRs and trying to get caught up.  

I just checked out the thread that you posted.

https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883466

I see that the bug is now considered fixed and the bug report is closed.  Is that correct?  Why is that?  Should this still be reviewed and merged?  Thanks very much.

**Review by yhcote — COMMENTED** [review]
Why do we move definitions from the header file to the C file ?

**Comment by yhcote** [comment]
Did you mean to write that patch against development instead ?

**Comment by yarikoptic** [comment]
@GodloveD sorry that I have missed your comment! 
yeap, marked as fixed since :
```
Fixed in version singularity-container/2.4.2-2
Done: Mehdi Dogguy <mehdi@debian.org>
```
and you can see on patch tracking page https://sources.debian.org/patches/singularity-container/2.4.2-2/ that there is ftbfs_mips patch which includes these changes, which looked good to go up to Mehdi's opinion and my ignorance ;)  whenever this issue gets resolved upstream (here) via this patch or some other means, we will drop the patch in debian

**Review by yhcote — CHANGES_REQUESTED** [review]
Why moving definitions from header file  to the C file ? I get what you are trying to do with the patch but I am not sure about moving those defs.

Also can you Create a pull request against our development branch please ? We use 'master' to track the tip of our latest release branch.

Cheers,

**Comment by GodloveD** [comment]
Heya @yarikoptic and @yhcote is this PR still relevant?  It hasn't been rebased and there are still requested changes pending from long ago.

**Comment by yarikoptic** [comment]
well, we are still applying the patch as of 2.5.1-1 in debian.  Do you think it is no longer needed somehow?

re @yhcote comments - sorry, missed them.  Indeed, in the most kosher way all those should be defined in .h but that would require exhaustive list even where those are not really used (since as described in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=883466  glibc provides a setns function )...  I guess a more lightweight patch could have been just to disable the `else error` clause and be done?

**Comment by yarikoptic** [comment]
doesn't issue remains unresolved?  FWIW this is a patch we are still applying in Debian packaging for singularity

**Comment by GodloveD** [comment]
Heya @yarikoptic I can reopen this.  It was closed as part of the mass PR closing we had last night due to the branch reorg.  

It looks like @yarikoptic did a review long ago, and his comments were never addressed.  To proceed with this PR, it would be good to address the comments of the reviewer I think?

**Pull request closed without merging**
