### PR TITLE
Fix logic for dropping permissions in parent thread caused by ns/user/user.c

### LINKED ISSUE #409: singularity_user_ns_enabled() call breaks functionality
Commit ed07e7ced8a1b5e25180715388e702e2586c1beb breaks functionality, reverting it to the previously used `singularity_ns_user_configured()` fixes this, however I'm not sure about the logic behind what we're doing here so I can't comment on if that is an acceptable fix. I'm looking into the best way to fix it, but for now it might be best to revert back to the original form, so that PR tests will pass again.

### PR DESCRIPTION
**Pull request by bauerm97**
Fixes #409 

Changes proposed in this pull request

 - This reverts commit ed07e7ced8a1b5e25180715388e702e2586c1beb.

@singularityware/singularity-admin

### CODE REVIEW

**Comment by gmkurtzer** [comment]
Why are you reverting ed07e7c?

**Comment by gmkurtzer** [comment]
Ahh, reading backlog now....

**Comment by gmkurtzer** [comment]
Please see my comment on #409 and include that in this pull request.

Thank you!

**Comment by bauerm97** [comment]
@gmkurtzer I updated the logic around this entire part of the code: 

 - Cleaned up a bit in `lib/ns/user/user.c`
 - Added `singularity_priv_is_suid()` to `lib/privilege.c`
 - Fixed `lib/fork.c` to drop privileges only when it has privileges to drop

**Comment by gmkurtzer** [comment]
This has been merged and I went ahead and cleaned the logic in user.c.

**Pull request merged**
