### PR TITLE
Improve the error message if cryptsetup version is unsupported

### PR DESCRIPTION
**Pull request by schebro**
**Description of the Pull Request (PR):**
In current code, if the cryptsetup version present on the host is not supported, we simply display "available cryptsetup is not supported".

This change changes the error displayed in the following format:

Min required cryptsetup version: 2.0.0, Found version 2.0.0

**This fixes or addresses the following GitHub issues:**

- Fixes #

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by gvallee — COMMENTED** [review]
So I guess the plan is not anymore to have something like
```
err := crypt.EncryptFilesystem()
if err == crypt.ErrUnsupportedCryptsetupVersion {
```
because based on this change, the unit test does not make sense anymore as it is (reason why it failed). Is the intent here to check the version returned and use that we identify errors where the version does not match? If so, how the package calling `EncryptFilesystem()` can cleanly catch that type of error?

**Comment by schebro** [comment]
> So I guess the plan is not anymore to have something like
> 
> ```
> err := crypt.EncryptFilesystem()
> if err == crypt.ErrUnsupportedCryptsetupVersion {
> ```
> 
> because based on this change, the unit test does not make sense anymore as it is (reason why it failed). Is the intent here to check the version returned and use that we identify errors where the version does not match? If so, how the package calling `EncryptFilesystem()` can cleanly catch that type of error?

One thing we can do in that case is to still return ErrUnsupportedCryptsetupVersion but simply print the current and minimum version numbers. Does that work?

**Comment by tcooper** [comment]
Just built and am testing 3.4.0-rc.1 on CentOS 6. I would add that it would be great if the cryptsetup test came *early*, ideally before the image build and/or removal of an existing image with same filename has happened.

**Comment by dtrudg** [comment]
This PR has gone stale and is on a branch on our main `sylabs/singularity` repo.

I'm closing, having captured the issue as #4621 and I grabbed this branch into https://github.com/dctrud/singularity/tree/schebro_cryptsetup also

**Pull request closed without merging**
