### PR TITLE
Fix unavailable link to pacman.conf file.

### PR DESCRIPTION
**Pull request by mherzberg**
**This fixes or addresses the following GitHub issues:**

- Ref: #1731 

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [ ] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by GodloveD** [comment]
Hey @mherzberg this looks good.  Can you add a note to the CHANGELOG.md.  You can also add yourself to the contributor file if you like.

**Review by GodloveD — APPROVED** [review]
lgtm

**Review by yhcote — APPROVED** [review]
Looks good to me.

**Comment by GodloveD** [comment]
Thanks @mherzberg and @yhcote !

**Pull request merged**
