### PR TITLE
Support SLE/openSUSE with zypper

### PR DESCRIPTION
**Pull request by crbaird**
Based on PR #475 by @FlyElephant-31

Changes proposed in this pull request

 - adds zypper bootstrap capability
 - adds openSUSE example def

@singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
awesome! Hey @gmkurtzer should we have a test proper, or just manual?

**Comment by gmkurtzer** [comment]
This looks great, thank you @crbaird!

@vsoch Yes, you are right. At some point we should have tests for each of our examples, but that is a bit hard to do via CI (unless we also spin up a SLES/OpenSuSE environment).

Thanks!

**Comment by GodloveD** [comment]
Heya @crbaird I'm trying to document usage of this.  Do you happen to have any recipe files lying around that could go in the examples directory?  If you want you could just copy and paste one here and I'll do the work.  Or if you want to submit a PR that also works.

**Comment by crbaird** [comment]
Hi @GodloveD. Unfortunately the extent of our testing in OpenHPC is just the examples/opensuse/Singularity hello, world. I would be happy to come up with something more substantial if it would be useful.

**Comment by GodloveD** [comment]
Hi @crbaird .  Thanks for getting back to me so quickly.  I dig your avatar by the way.  Do you happen to know if the mirror in that example file is up to date?  I'm getting this error when I try to build.  I commented out the `Include: zypper` and the zypper command in `%post`.  Do you have any advice?

```
david@dave-testing-self-bootstrap:~$ sudo /opt/singularity/bin/singularity build --force test Singularity
Using container recipe deffile: Singularity
Sanitizing environment
Adding base Singularity environment to container
Found Zypper at: /usr/bin/zypper
Adding repository 'repo-oss' .............................................................................................................................................................................[done]
Repository 'repo-oss' successfully added
Enabled     : Yes
Autorefresh : No
GPG Check   : Yes
URI         : http://download.opensuse.org/distribution/leap/42.2/repo/oss/

Retrieving repository 'repo-oss' metadata ...............................................................................................................................................................[error]
Repository 'repo-oss' is invalid.
[repo-oss|http://download.opensuse.org/distribution/leap/42.2/repo/oss/] Valid metadata not found at specified URL
Please check if the URIs defined for this repository are pointing to a valid repository.
Skipping repository 'repo-oss' because of the above error.
Could not refresh the repositories because of errors.
Warning: Enforced setting: $releasever=42.2
Error building the cache:
[repo-oss|http://download.opensuse.org/distribution/leap/42.2/repo/oss/] Valid metadata not found at specified URL
Warning: The metadata cache needs to be built for the 'repo-oss' repository. You can run 'zypper refresh' as root to do this.
Disabling repository 'repo-oss'.
Loading repository data...
Reading installed packages...
'aaa_base' not found in package names. Trying capabilities.
No provider of 'aaa_base' found.
ERROR: Bootstrap failed... exiting
ABORT: Aborting with RETVAL=255
```

**Comment by crbaird** [comment]
I wonder if it might be a proxy issue. That URL works fine for me on our nice open test rig, but fails in the fashion you describe from inside the corporate firewall.

**Comment by GodloveD** [comment]
I don't think it is a proxy issue.  I was trying from a GCP instance.  I
wonder if it has to do with OS.  I was trying on Ubuntu 16.04.  What OS's
are known to work here?

**Comment by vsoch** [comment]
Did you check the boxes to allow http/https traffic?

**Comment by GodloveD** [comment]
I'm pretty sure those boxes are for inbound traffic right? I don't think it
matters for this, but I can try again.

**Comment by crbaird** [comment]
@GodloveD It runs well under SLES 12 and OpenSUSE Leap.

**Pull request merged**
