### PR TITLE
Development 3.0: Instance fixes

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR contains :
- fix for `--boot` regression
- replace SIGTERM with SIGINT by default to stop instance
- set correct log file owner when using target UID (some daemon could get permission denied)
- move some instance message as Infof to Verbosef
- add URI handler
- fix regression with RPC/stage 2 fork by adding CLONE_FS

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [user](https://www.github.com/sylabs/singularity-userdocs) and [administrator](https://www.github.com/sylabs/singularity-admindocs) documentation bases.
- [x] I have tested this PR locally with a `make testall`
- [x] This PR is against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by GodloveD** [comment]
Unfortunately this doesn't actually fix #2176 afaik:
```
$ singularity version
be74315c

$ sudo singularity build debian.sif debian.def 
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
 40.36 MiB / 40.36 MiB [==========================================================================================================================================] 100.00% 5.23 MiB/s 7s
INFO:    Running post scriptlet
+ apt-get -y update
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]
Get:4 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]                 
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]               
Get:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [5148 B]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7099 kB]
Get:8 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [447 kB]
Fetched 7856 kB in 2s (2685 kB/s)                                
Reading package lists... Done
E: Unable to change to (unreachable)/home/david/sandbox/ - chdir (2: No such file or directory)
FATAL:   post proc: exit status 100
FATAL:   While performing build: while running engine: exit status 255
```

**Comment by cclerget** [comment]
@GodloveD I don't know what happens with CGO but you need to redo all the compilation step : `./mconfig && make -C builddir && sudo make -C builddir install` to correctly compile `starter.c`

**Comment by GodloveD** [comment]
Yeah.  I think I'm compiling this properly.  Still isn't working from where I'm sitting. 

```
12:03 PM 
ubuntu ~/go/src/github.com/sylabs/singularity
$ git checkout cclerget/master-instance-fix 
Note: checking out 'cclerget/master-instance-fix'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

HEAD is now at be74315c Add CLONE_FILES too, RPC server may need to open/manipulate file descriptors for stage 2

12:03 PM 
ubuntu ~/go/src/github.com/sylabs/singularity
$ ./mconfig && make -C builddir && sudo make -C builddir install
=> running base system checks ...
 checking: host C compiler... cc
 checking: host C++ compiler... c++
 checking: target C compiler... cc
 checking: target C++ compiler... c++
 checking: host compiles static binaries... yes
 checking: target compiles static binaries... yes
 checking: host os type... unix
 checking: host architecture... x86_64
 checking: target architecture... x86_64
 checking: host architecture word size... 64
 checking: target architecture word size... 64
 checking: verbose flag... 0
 checking: debug flag... 0
=> running project specific checks ...
 checking: namespace: CLONE_NEWPID... yes
 checking: namespace: CLONE_FS... yes
 checking: namespace: CLONE_NEWNS... yes
 checking: namespace: CLONE_NEWUSER... yes
 checking: namespace: CLONE_NEWIPC... yes
 checking: namespace: CLONE_NEWNET... yes
 checking: namespace: CLONE_NEWUTS... yes
 checking: namespace: CLONE_NEWCGROUP... yes
 checking: feature: NO_NEW_PRIVS... yes
 checking: feature: MS_SLAVE... yes
 checking: feature: MS_REC... yes
 checking: feature: MS_PRIVATE... yes
 checking: user capabilities... yes
 checking: header linux/securebits.h... yes
 checking: header linux/capability.h... yes
 checking: function setns... yes
 checking: libssl+headers... yes
 checking: libuuid+headers... yes
 checking: libseccomp+headers... no
INFO: userns and disable_suid are disabled. (mchecks/base.chk)
=> generating fragments ...
 found build modules:
   +-> src/runtime/c/lib/util/util.mconf
=> building Makefile ...
=> generating dist/rpm/singularity.spec ...
=> project setup with :
    - target arch: x86_64
    - target compiler: cc
    - target wordsize: 64-bit
    - host arch: x86_64
    - host wordsize: 64-bit
    - host system: unix
    - verbose: no
    - debug: no
=> builddir/Makefile ready, try:
   $ cd builddir
   $ make
make: Entering directory '/home/david/go/src/github.com/sylabs/singularity/builddir'
 CC src/runtime/c/lib/util/capability.c
 CC src/runtime/c/lib/util/message.c
 CC src/runtime/c/lib/util/setns.c
 AR src/runtime/c/lib/util/libutil.a
 CSCOPE
 DEPENDS
 AR lib/libruntime.a
 VENDORS
 GO singularity
 GO src/runtime/starter/c/starter
 CNI PLUGIN dhcp
 CNI PLUGIN host-local
 CNI PLUGIN static
 CNI PLUGIN bridge
 CNI PLUGIN host-device
 CNI PLUGIN ipvlan
 CNI PLUGIN loopback
 CNI PLUGIN macvlan
 CNI PLUGIN ptp
 CNI PLUGIN vlan
 CNI PLUGIN bandwidth
 CNI PLUGIN flannel
 CNI PLUGIN portmap
 CNI PLUGIN tuning
make: Leaving directory '/home/david/go/src/github.com/sylabs/singularity/builddir'
make: Entering directory '/home/david/go/src/github.com/sylabs/singularity/builddir'
/home/david/go/src/github.com/sylabs/singularity/makeit/gengodep: 8: /home/david/go/src/github.com/sylabs/singularity/makeit/gengodep: go: not found
/home/david/go/src/github.com/sylabs/singularity/makeit/gengodep: 8: /home/david/go/src/github.com/sylabs/singularity/makeit/gengodep: go: not found
/home/david/go/src/github.com/sylabs/singularity/makeit/gengodep: 8: /home/david/go/src/github.com/sylabs/singularity/makeit/gengodep: go: not found
/home/david/go/src/github.com/sylabs/singularity/makeit/gengodep: 8: /home/david/go/src/github.com/sylabs/singularity/makeit/gengodep: go: not found
 INSTALL /usr/local/bin/singularity
 INSTALL /usr/local/libexec/singularity/bin/starter
 INSTALL SUID /usr/local/libexec/singularity/bin/starter-suid
 INSTALL /usr/local/etc/singularity/singularity.conf
 INSTALL /usr/local/bin/run-singularity
 INSTALL /usr/local/etc/singularity/ecl.toml
 INSTALL /usr/local/etc/bash_completion.d/singularity
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/macvlan
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/tuning
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/loopback
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/ptp
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/bridge
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/bandwidth
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/static
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/host-local
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/vlan
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/host-device
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/ipvlan
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/dhcp
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/portmap
 INSTALL CNI PLUGIN /usr/local/libexec/singularity/cni/flannel
 INSTALL CNI CONFIGURATION FILES
 INSTALL /usr/local/etc/singularity/seccomp-profiles/default.json
 INSTALL /usr/local/etc/singularity/nvliblist.conf
 INSTALL /usr/local/etc/singularity/cgroups/cgroups.toml
 DONE
make: Leaving directory '/home/david/go/src/github.com/sylabs/singularity/builddir'

12:04 PM 
ubuntu ~/go/src/github.com/sylabs/singularity
$ singularity version
be74315c

12:04 PM 
ubuntu ~/go/src/github.com/sylabs/singularity
$ cat ~/debian.def 
Bootstrap: library
From: debian:9

%post
    apt-get -y update

12:04 PM 
ubuntu ~/go/src/github.com/sylabs/singularity
$ sudo singularity build ~/debian.sif ~/debian.def 
WARNING: Authentication token file not found : Only pulls of public images will succeed
INFO:    Starting build...
 40.36 MiB / 40.36 MiB [==========================================================================================================================================] 100.00% 5.11 MiB/s 7s
INFO:    Running post scriptlet
+ apt-get -y update
Get:1 http://security.debian.org/debian-security stretch/updates InRelease [94.3 kB]
Ign:2 http://cdn-fastly.deb.debian.org/debian stretch InRelease                              
Get:3 http://cdn-fastly.deb.debian.org/debian stretch-updates InRelease [91.0 kB]            
Get:4 http://security.debian.org/debian-security stretch/updates/main amd64 Packages [447 kB]
Get:5 http://cdn-fastly.deb.debian.org/debian stretch Release [118 kB]                  
Get:6 http://cdn-fastly.deb.debian.org/debian stretch-updates/main amd64 Packages [5148 B]
Get:7 http://cdn-fastly.deb.debian.org/debian stretch Release.gpg [2434 B]
Get:8 http://cdn-fastly.deb.debian.org/debian stretch/main amd64 Packages [7099 kB]
Fetched 7856 kB in 2s (2909 kB/s)   
Reading package lists... Done
E: Unable to change to (unreachable)/home/david/go/src/github.com/sylabs/singularity/ - chdir (2: No such file or directory)
FATAL:   post proc: exit status 100
FATAL:   While performing build: while running engine: exit status 255
```

**Comment by GodloveD** [comment]
@jmstover told me offline that I need to run a `go clean -cache`.  After running that I can verify that this is fixing #2176 .  😸

**Review by bauerm97 — APPROVED** [review]
Looks good

**Pull request merged**
