### PR TITLE
Improved error when pushing a unsigned container

### LINKED ISSUE #3407: change error when pushing an unsigned container
## Version of Singularity:

3.2.0rc2

```
[vagrant@localhost tmp]$ singularity push illolcow.sif library://jscook2345-double/default/illolcow.sif
WARNING: unable to verify container: error while searching for signature blocks: no signatures found for system partition
INFO:    TIP: Learn how to sign your own containers here : https://www.sylabs.io/docs/

Unable to verify Your container! You REALLY should sign your container before pushing!
Stoping upload.
```

Please remove `Unable to verify Your container! You REALLY should sign your container before pushing!
Stoping upload.`

It's a bit judgemental and I don't think it's needed. I would add a FATAL error message with `you can avoid this error with -U/unsigned option ... etc` after the INFO tip.

### PR DESCRIPTION
**Pull request by WestleyK**
## Description of the Pull Request (PR):

This PR improves the error message when pushing a unsigned container.

## This fixes or addresses the following GitHub issues:

- Fixes #3407 

<br>

### CODE REVIEW

**Comment by WestleyK** [comment]
Added cherry-pick label because the issue has a 3.2 label, maybe this can make it into 3.2?

CC @GodloveD

**Review by jscook2345 — APPROVED** [review]
I think I would flip-flop the messages there. Say the error, than give them the message which could resolve it.

**Comment by jscook2345** [comment]
3.2 is pretty much done pending testing, so I removed the cherry pick part.

**Review by jscook2345 — APPROVED** [review]
LGTM

**Review by ikaneshiro — APPROVED** [review]

**Pull request merged**
