### PR TITLE
Add --name flag to pull cmd

### LINKED ISSUE #2214: 3.0.0 singularity pull no long accepts --name, but this is not mentioned in the changelog
Hello and congratulations on the new Singularity release! 

## Version of Singularity:

3.0.0

### Expected behavior

Conventional command line invocations that worked in v2.[56].x continue to work in v3.0.0, except as documented at https://github.com/sylabs/singularity/blob/master/CHANGELOG.md

Example from the CWL reference runner, `cwltool`

```
['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']
```
(Singularity downloads the docker container and saves it as a Singularity image using the value of `--name`)

### Actual behavior

`--name` is not listed on the v3.0.0 changelog

```
['singularity', 'pull', '--force', '--name', 'kernsuite-prefactor.img', 'docker://kernsuite/prefactor']
Error: unknown flag: --name
Usage:
singularity [global options...] pull [pull options...]
```

### Steps to reproduce behavior
Install Singularity v3.0.0
```
singularity pull --force --name kernsuite-prefactor.img docker://kernsuite/prefactor
```

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
- Fixes #2214

Signed-off-by: ArangoGutierrez <eduardo@sylabs.io>

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by ArangoGutierrez** [comment]
Ready for review 
 - @GodloveD 

Call for testing:
 - @mr-c @pditommaso

**Review by GodloveD — DISMISSED** [review]
Can you please link this to the env var `$SINGULARITY_NAME` as well for consistency?

**Comment by pditommaso** [comment]
@ArangoGutierrez how to test? should i need to compile your branch?

**Comment by ArangoGutierrez** [comment]
@pditommaso 
If you have 3.0 installed, you can just do
```bash
$ git checkout ArangoGutierrez/pull_name_flag
$ go run src/cmd/singularity/cli.go pull no_flag.sif library://busybox
$ go run src/cmd/singularity/cli.go pull --name with_flag.sif library://busybox
```

**Comment by GodloveD** [comment]
@ArangoGutierrez did you verify that the env var works?  Because I'm pretty sure it won't with these changes.  You need an entry here at least:
https://github.com/sylabs/singularity/blob/master/src/cmd/singularity/cli/singularity.go#L217

**Review by GodloveD — APPROVED** [review]
Looks like a wiener!  🌭

**Pull request merged**
