### PR TITLE
Small tweaks for encryption CLI

### PR DESCRIPTION
**Pull request by ikaneshiro**
Signed-off-by: Ian Kaneshiro <iankane@umich.edu>

### CODE REVIEW

**Comment by ikaneshiro** [comment]
@GodloveD Can you test this with the documentation you're preparing to make sure everything is consistent?

**Comment by gvallee** [comment]
And just to make sure we are all on the same page: one of the goals of this PR is to have an early failure if users specify an empty path for a PEM file, instead of, for example, failing after starting to build an image.

**Comment by ikaneshiro** [comment]
@gvallee This does not do that, I was going to do that in another one. This only targets the order of flag precedence and removes the requirement for both the `--encrypt` and `--pem-path/--passphrase` flags to be present. I should have added a better description to avoid confusion

**Comment by gvallee** [comment]
@ikaneshiro My bad, it is what happens when I try to be too smart without really reading the code. :)

**Review by GodloveD — APPROVED** [review]
This is behaving as expected from my end.  Thank you @ikaneshiro !

**Pull request merged**
