### PR TITLE
Respect uppercase proxy env pass-through

### LINKED ISSUE #2504: Proxy env var passthrough does not match 2.6
## Version of Singularity:

3.0.x

### Expected behavior

In 2.6.x proxy environment vars are passed through into the container whether they are lower or uppercase. Most programs correctly look for lowercase these days, but some stuff (esp. crusty old bioinf scripts) may be expecting `HTTP_PROXY` etc. not `http_proxy`

In 2.6 the PR fixing the pass through did a case-insensitive check on the proxy vars:

https://github.com/sylabs/singularity/pull/1151/files

### Actual behavior

In 3.0.x the proxy var comparison is case-sensitive, so is not passing `HTTP_PROXY` etc.

### PR DESCRIPTION
**Pull request by dtrudg**
**Description of the Pull Request (PR):**

- Pass through upper case proxy env vars
- Update the `clean_test.go` so it checks for all pass-through proxy env vars.

**This fixes or addresses the following GitHub issues:**

- Fixes #2504 

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by sashayakovtseva** [comment]
Isn't it better to keep only upper or only lower case envs in `alwaysPassKeys`? I suggest translating key in `addIfReq` func with strings.ToUpper / ToLower, that is a more clean way to achieve the same IMO.

**Comment by dtrudg** [comment]
Hi @sashayakovtseva - I was originally going to do a case conversion for the comparison in the loop - but decided against it as here the existing code is passing through `TERM` (which should *always* be an upper case var) and not `term` - I didn't want to change that particular behavior. Case conversion for the comparison would also pass through mistaken mixed caps  e.g. `hTtTp_PrOxY` or `Term`.

I have no strong opinion though - anything that will pass `XXX_PROXY` in upper case will address the issue, so please let me know if you do want me to change this to do a case conversion prior to comparison.

**Comment by sashayakovtseva** [comment]
I wonder if lower/mixed case envs should be passed as it is to container, so conversion to upper case for each env var seems reasonable to me. So with conversion it won't matter whether you've passed `hTtTp_PrOxY` or `http_proxy`, they both will result in standard `HTTP_PROXY` env. 
Might want somebody else's opinion here.

**Comment by dtrudg** [comment]
Lower case is the preferred/standard form that most software uses. Some like I think wget ignore upper case:

https://serverfault.com/questions/571887/why-wget-doesnt-read-http-proxy-in-uppercase-format

... so we can’t always force the proxy env vars to upper case in the container.

Some other software only reads upper case. This means we’d need to pass both forms in if set.




________________________________

**Comment by sashayakovtseva** [comment]
Thanks for clarification, in this case I think your changes are perfectly fine.

**Review by sashayakovtseva — APPROVED** [review]

**Review by bauerm97 — APPROVED** [review]
I think the justification for only passing `ALL_CAPS` or `no_caps` forms here is solid. Looks good to me, many thanks @dctrud

**Pull request merged**
