### PR TITLE
Fix fakeroot build with pacstrap and debootstrap

### LINKED ISSUE #4331: Failed to bootstrap build from zypper/pacstrap/debootstrap with fakeroot
## Version of Singularity:

3.3.0

### Expected behavior

Build succeed

### Actual behavior

Build failed with error :

`FATAL:   While performing build: conveyor failed to get: while copying pseudo devices: while creating /tmp/sbuild-129933562/fs/dev/null: open /tmp/sbuild-129933562/fs/.singularity.d/runscript: no such file or directory`

### Steps to reproduce behavior

```
singularity build --fakeroot /tmp/s.sif examples/opensuse/Singularity
singularity build --fakeroot /tmp/s.sif examples/debian/Singularity
singularity build --fakeroot /tmp/s.sif examples/arch/Singularity
```

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR fixes fakeroot build bootstrap:
- pacstrap works and was tested with `examples/arch/Singularity`)
- debootstrap debian works and was tested with `examples/debian/Singularity`
- debootstrap ubuntu works and was tested with `examples/ubuntu/Singularity`

**This fixes or addresses the following GitHub issues:**

- Fixes #4331

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by sashayakovtseva — APPROVED** [review]

**Comment by kamedodji** [comment]
singularity (3.5) fakeroot build with debootstrap (on debian stretch) failed with :
```
$ singularity version
3.5.0
$ singularity build -F --fakeroot stretch.img stretch.def 
INFO:    Starting build...
/usr/sbin/debootstrap.bin --no-check-gpg --variant=minbase --exclude=openssl,udev,debconf-i18n,e2fsprogs --include=apt,inetutils-ping,iproute,bash,dash --arch=amd64 stretch /tmp/rootfs-f218f23e-06b9-11ea-80c5-e4e7493a80c3 http://deb.debian.org/debian
<snip>
W: Failure trying to run: chroot /tmp/rootfs-f218f23e-06b9-11ea-80c5-e4e7493a80c3 dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.43_amd64.deb
W: See /tmp/rootfs-f218f23e-06b9-11ea-80c5-e4e7493a80c3/debootstrap/debootstrap.log for details
```
**But it's work fine with `fakechroot`** 
```
singularity build -F --fakeroot stretch.img stretch.def 
INFO:    Starting build...
/usr/sbin/debootstrap.bin --no-check-gpg --foreign --variant=fakechroot --variant=minbase --exclude=openssl,udev,debconf-i18n,e2fsprogs --include=apt,inetutils-ping,iproute,bash,dash --arch=amd64 stretch /tmp/rootfs-1f6fd57e-06ba-11ea-9764-e4e7493a80c3 http://deb.debian.org/debian
<snip>
INFO:    Running setup scriptlet
INFO:    Creating SIF file...
INFO:    Build complete: stretch.img
```

**Comment by cclerget** [comment]
@kamedodji Could you please paste `stretch.def` content with and without `fakechroot` ?

**Comment by kamedodji** [comment]
here you are @cclerget:
```
BootStrap: debootstrap
OSVersion: stretch
MirrorURL: http://ftp.fr.debian.org/debian
Include: inetutils-ping,iproute,bash,dash
```

**Comment by cclerget** [comment]
@kamedodji I'm also curious about the content of you're own `/usr/sbin/debootstrap` wrapper around `/usr/sbin/debootstrap.bin`, could you provide the content too, I'm not able to reproduce the issue on debian stretch, I got a warning about another chroot error for `/sys` mount but no build failure

**Comment by kamedodji** [comment]
yes, @cclerget , see bellow my wrapper 
```
cp /usr/sbin/debootstrap /usr/sbin/debootstrap.bin
cat << EOF > /usr/sbin/debootstrap
#!/bin/sh

cmd="/usr/sbin/debootstrap.bin --no-check-gpg --foreign --variant=fakechroot $@"
#cmd="/usr/sbin/debootstrap.bin --no-check-gpg $@"
echo ${cmd}
eval ${cmd}
EOF
```

**Comment by cclerget** [comment]
@kamedodji Can't reproduce, could you retry with `singularity build -F --fakeroot stretch.img stretch.def` with `cmd="/usr/sbin/debootstrap.bin --no-check-gpg $@"` in the wrapper and look at the exact error in `debootstrap/debootstrap.log`, Singularity should display the content of `debootstrap/debootstrap.log` in case of error so it would be good to look at the exact error for `Failure trying to run: chroot /tmp/rootfs-f218f23e-06b9-11ea-80c5-e4e7493a80c3 dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.43_amd64.deb`

**Comment by kamedodji** [comment]
singularity seems to clean working ` /tmp/rootfs-f218f23e-06b9-11ea-80c5-e4e7493a80c3` directory, despite the use of `--keep-debootstrap-dir` :-( !
Any idea @cclerget ?

**Comment by cclerget** [comment]
@kamedodji Ok build it with `singularity build --no-cleanup -F --fakeroot stretch.img stretch.def` in conjunction with `--keep-debootstrap-dir`

**Comment by kamedodji** [comment]
@cclerget i'll need your help to simulate raising `chroot` command as i'm not root :-( !
Il use unsuccessfully : `fakeroot chroot /tmp/rootfs-80973f1a-06da-11ea-b83c-e4e7493a80c3 dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.43_amd64.deb` :-( !

**Comment by cclerget** [comment]
@kamedodji You should be able to execute :

```
singularity exec -w --fakeroot /tmp/rootfs-80973f1a-06da-11ea-b83c-e4e7493a80c3 dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.43_amd64.deb
```

**Comment by cclerget** [comment]
@kamedodji and you can also try :
```
singularity exec -f docker://alpine chroot /tmp/rootfs-468610d5-06e5-11ea-955b-0800278dc04d dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.43_amd64.deb
```

**Comment by kamedodji** [comment]
thx, @cclerget, for these guideline:
```
singularity exec -w --fakeroot /tmp/rootfs-6a8b89b0-06fb-11ea-9866-e4e7493a80c3 dpkg --force-depends --install /var/cache/apt/archives/base-passwd_3.5.43_amd64.deb
WARNING: container does not have /.singularity.d/actions/exec, calling dpkg directly
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing description
dpkg: warning: parsing file '/var/lib/dpkg/status' near line 5 package 'dpkg':
 missing architecture
Selecting previously unselected package base-passwd.
(Reading database ... 0 files and directories currently installed.)
Preparing to unpack .../base-passwd_3.5.43_amd64.deb ...
Unpacking base-passwd (3.5.43) ...
dpkg: base-passwd: dependency problems, but configuring anyway as you requested:
 base-passwd depends on libc6 (>= 2.8); however:
  Package libc6 is not installed.
 base-passwd depends on libdebconfclient0 (>= 0.145); however:
  Package libdebconfclient0 is not installed.

Setting up base-passwd (3.5.43) ...
debconf: unable to initialize frontend: Dialog
debconf: (No usable dialog-like program is installed, so the dialog based frontend cannot be used. at /usr/share/perl5/Debconf/FrontEnd/Dialog.pm line 76.)
debconf: falling back to frontend: Readline
debconf: unable to initialize frontend: Readline
debconf: (Can't locate Term/ReadLine.pm in @INC (you may need to install the Term::ReadLine module) (@INC contains: /etc/perl /usr/local/lib/x86_64-linux-gnu/perl/5.24.1 /usr/local/share/perl/5.24.1 /usr/lib/x86_64-linux-gnu/perl5/5.24 /usr/share/perl5 /usr/lib/x86_64-linux-gnu/perl/5.24 /usr/share/perl/5.24 /usr/local/lib/site_perl /usr/lib/x86_64-linux-gnu/perl-base .) at /usr/share/perl5/Debconf/FrontEnd/Readline.pm line 7.)
debconf: falling back to frontend: Teletype
```

I'm investigate also from my side...

**Comment by kamedodji** [comment]
for your information, @cclerget, stretch image build work fine on Centos 7.7 host.
It's means my issue is on debian stretch host.
I'll try debian buster and will let you known...

**Pull request merged**
