### PR TITLE
Doc improvement for mount

### PR DESCRIPTION
**Pull request by loveshack**
I realized I was under a misapprehension about mounts from the reply to a previous issue.

### CODE REVIEW

**Comment by loveshack** [comment]
I'm confused about pull requests (amongst other things!).  I was hoping this was a separate one, providing a temporary fix for #77

**Comment by gmkurtzer** [comment]
Did commenting out `dnf` fix the read only issue you saw in #77?

**Comment by loveshack** [comment]
You wrote: 

> Did commenting out `dnf` fix the read only issue you saw in #77?

Yes.

**Comment by loveshack** [comment]
This is in relation to #77, but very messy and probably should be started anew.
It needs the change for --tolerant, which dnf doesn't support.

I still don't understand what's happening in 2.0.

**Comment by gmkurtzer** [comment]
I will merge this PR, and take a look at it in more detail from work. 

What about 2.0 is troublesome? The bootstrapping?

**Comment by loveshack** [comment]
You wrote: 

> I will merge this PR, and take a look at it in more detail from work. 
> 
> What about 2.0 is troublesome? The bootstrapping?

Yes.  I haven't yet found what change in master made the dnf change work
with el6.

**Pull request merged**
