### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Kundan28**
**Description of the Pull Request (PR):**

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

**This fixes or addresses the following GitHub issues:**

- Fixes #

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [user](https://www.github.com/sylabs/singularity-userdocs) and [administrator](https://www.github.com/sylabs/singularity-admindocs) documentation bases.
- [x] I have tested this PR locally with a `make testall`
- [ ] This PR is against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularity-maintainers

### CODE REVIEW

**Review by GodloveD — CHANGES_REQUESTED** [review]
I think this is a fine idea.  I believe the badge on the left is Travis.  Can you put Travis in the header instead of build?  Also, do you feel like fixing the text at the top that starts and ends with underscores?  It is supposed to be italicized but I think markdown is not working because of the newlines.  Each paragraph likely needs to be individually wrapped in underscores.

**Comment by Kundan28** [comment]
@GodloveD Changed Travis in the header instead of build.

**Comment by Kundan28** [comment]
@GodloveD Changed Travis in the header instead of build and fixed the text at the top that was supposed to be italicized.

**Comment by GodloveD** [comment]
Please add yourself to the `CONTRIBUTORS.md` in this PR as explained in #2142.  Thank you.

**Comment by Kundan28** [comment]
@GodloveD Why was the branch not merged ?

**Comment by GodloveD** [comment]
Heya @Kundan28 I'm still waiting on you to add yourself to the contributors list on this PR as stated in the comments above.  If for some reason you are unable to do this I can probably make the change myself.

**Comment by Kundan28** [comment]
@GodloveD You can merge this branch and add my name to the CONTRIBUTORS.md

**Review by GodloveD — APPROVED** [review]

**Comment by GodloveD** [comment]
Thanks @Kundan28

**Comment by Kundan28** [comment]
@GodloveD Most welcome.

**Pull request merged**
