### PR TITLE
fixing issue with cmd missing $@

### LINKED ISSUE #1138: Runscript do not forward arguments in the container anymore
When an image is built via docker pull singularity extracts the CMD to generate the runscript. In previous versions of singularity the runscript was generated in such a way that arguments passed on the command line were forwarded to the command run inside the container. In version 2.4 no arguments are passed because the generated runscript lacks the `"$@"` argument after the main command.

## Version of Singularity:

Version 2.4

### Expected behavior

Arguments get passed through the runscript to the command inside the container.

### Actual behavior

No argument is passed through the runscript inside the container.

### Possbile fix

Add back `"$@"` to the [runscript generation](https://github.com/singularityware/singularity/blob/e480d9640f5e76a51af7a9f43e87b77f008f6652/libexec/python/docker/tasks.py#L105])

### PR DESCRIPTION
**Pull request by vsoch**
**Description of the Pull Request (PR):**

This will fix #1138 

Attn: @singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
Added this issue too https://github.com/singularityware/singularity/issues/1140

**Comment by vsoch** [comment]
This fixes #1140 and #1138 @gmkurtzer please review for 2.4.1.

**Review by GodloveD — APPROVED** [review]
This looks good to me.

**Comment by gmkurtzer** [comment]
Thanks!

**Pull request merged**
