### PR TITLE
Add centos7 rpmbuild and test to travis tests

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

Adds second travis matrix entry to test building on centos7 using docker.
A centos6 entry is commented out because it currently fails with a build error saying setns() is undefined.

**This fixes or addresses the following GitHub issues:**

No specific issue, but several times I have run into rpmbuild issues on centos caused by previous commits and I hope this will avoid those kinds of issues.

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [Author's file](https://github.com/singularityware/singularity/blob/master/AUTHORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by DrDaveD** [comment]
Note that this removes the legacy test of the released singularity-2.2.1 from the default travis test build.  I don't understand what the point of that was.

**Comment by GodloveD** [comment]
The legacy testing stuff can and should be removed.  As it stands it is trying to do legacy testing in the wrong direction.  @vsoch and I have talked about pulling and running some containers from shub with old builders to do legacy testing instead, but I haven't had time to work on it.

**Comment by gmkurtzer** [comment]
Wow, this is really cool, great work @DrDaveD!

I agree with @GodloveD, can you remove the code for the legacy support, and then we can merge this.

Thanks!

**Comment by DrDaveD** [comment]
@gmkurtzer The legacy support code was already removed.

I have now merged in the setns changes, including the not-yet-merged pr #905 to allow make dist to work, and so was able to uncomment the centos6 build as well.  Unfortunately it appears the test suite makes python assumptions not valid in the centos6 python, so I skip the test suite there and just make sure the rpmbuild works.

**Comment by vsoch** [comment]
what python assumptions?

**Comment by vsoch** [comment]
the modules in the test suite should match the set that we use (and test for) during install, so if there is something missing it should be added for testing.

**Comment by DrDaveD** [comment]
@vsoch I made a new issue #906 with the details.  There's a syntax error with the python 2.6.6 version on centos6.

**Comment by vsoch** [comment]
That test is just for invalid json - we can change it so the invalid-ness works for centos6.

**Comment by DrDaveD** [comment]
I think that's just the first of the problems.  When they're all fixed, we can change .travis/rpmbuild_test to renable the test suite on centos6, but meanwhile let's get this much in to prevent more things from breaking.

**Comment by DrDaveD** [comment]
@gmkurtzer Is there any reason remaining to not merge this?

**Comment by gmkurtzer** [comment]
@DrDaveD Apologies for the delay. I've been way behind on email and git responses. There is a minor conflict. I think the fix is easy, but I'm admittedly not very knowledgeable in Travis, can you take a look?

**Comment by DrDaveD** [comment]
@gmkurtzer I fixed the merge conflict but now there's again centos6 & 7 build problems with the new code added, because there was no travis check on the merge :-(.  Please check the travis details, and meanwhile I will too but I've only got limited time right now.

**Comment by gmkurtzer** [comment]
@DrDaveD Yep, I'm on it! Thank you for fixing the other issues, I will merge as soon as I resolve the RPM builds.

**Comment by gmkurtzer** [comment]
We are running into some autoconf limitations (or rather my personal limitations related to autoconf) relating to the SLURM build and `make clean` trying to remove a library that has already been removed by a different Makefile... Even when SLURM is not being built...

I am very much inclined to move to SLURM out of Singularity proper, and make the module a subproject. For now I am disabling it's build and inclusion.

**Comment by vsoch** [comment]
@gmkurtzer and @DrDaveD we could make a template for adding a Singularity plugin. I don't think submodules are right because they will likely confuse most users, but a separate repo for slurm with simple, cleanly written instructions should fit the bill for most that will want to install, HPC admins, etc.

**Comment by gmkurtzer** [comment]
Excellent, thank you for the Travis fixes @DrDaveD!

@vsoch Totally agree, and most people that are doing this will be system-admins which may mitigate some of the issues, at least specifically for SLURM.

**Pull request merged**
