### PR TITLE
Fixes #3134. Improve Plugin Command Errors for Privileged Operations

### LINKED ISSUE #3134: Improve Plugin Command Errors for Privileged Operations
## Version of Singularity:

`3.1.0-502.ga20591179`

### Expected behavior

Several `plugin` commands require `root` privileges to function properly, such as `install`, `uninstall`, `enable`, `disable`. These should provide a clear error message when run without `root`, similar to the OCI command group:

```
FATAL:   command 'oci run' requires root privileges
```

### Actual behavior

When run without `root`, it would be nice to have a friendly error message that is consistent with other CLI commands such as the OCI group. Instead, the `plugin` command group provides long and scary (albeit accurate) error messages:

```
$ singularity plugin install examples/plugins/test-plugin/test-plugin.sif 
FATAL:   Failed to install plugin "examples/plugins/test-plugin/test-plugin.sif": mkdir /usr/local/libexec/singularity/plugin/sylabs.io: permission denied.
$ singularity plugin uninstall sylabs.io/test-plugin
FATAL:   Failed to uninstall plugin "sylabs.io/test-plugin": remove /usr/local/libexec/singularity/plugin/sylabs.io/test-plugin/plugin.sif: permission denied; remove /usr/local/libexec/singularity/plugin/sylabs.io/test-plugin/object.so: permission denied; remove /usr/local/libexec/singularity/plugin/2ac101e1ca45e98c94f55b3ee92af290920059425c0873bbb5e0d11fdb30e54d.meta: permission denied; remove /usr/local/libexec/singularity/plugin/sylabs.io/test-plugin: permission denied.
$ singularity plugin enable sylabs.io/test-plugin
FATAL:   Failed to enable plugin "sylabs.io/test-plugin": open /usr/local/libexec/singularity/plugin/2ac101e1ca45e98c94f55b3ee92af290920059425c0873bbb5e0d11fdb30e54d.meta: permission denied.
$ singularity plugin disable sylabs.io/test-plugin
FATAL:   Failed to disable plugin "sylabs.io/test-plugin": open /usr/local/libexec/singularity/plugin/2ac101e1ca45e98c94f55b3ee92af290920059425c0873bbb5e0d11fdb30e54d.meta: permission denied.
```

### Steps to reproduce behavior

As above.

### PR DESCRIPTION
**Pull request by gvallee**
**Description of the Pull Request (PR):**

Improve Plugin Command Errors for Privileged Operations

**This fixes or addresses the following GitHub issues:**

- Fixes #3134 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by GodloveD — COMMENTED** [review]
I'm not an expert here, but I'll give my $0.02.  Seems like the function that was defined in `cmd/internal/cli/oci_linux.go` is generally useful.  Instead of copying the same code in another place, would it be useful to just break that function out into a package that can be imported in multiple places?

**Comment by gvallee** [comment]
The function for the OCI use case explicitly mentions `oci` in the output and here, we are dealing with plugins, not oci :) I would be happy to create a single function that would accept a context (e.g., "oci", "plugin") and performs the test if we really want to avoid having two functions.

https://github.com/sylabs/singularity/blob/e79d88fa56f0e8f5e74c2a9c68a0004b1924dac4/cmd/internal/cli/oci_linux.go#L83

**Comment by GodloveD** [comment]
Oh, that is weird.  When I actually try to run an oci command in 3.1.1, it just gives me a generic error:
```
vagrant@vagrant:~$ singularity oci mount blah blah
FATAL:   this command is required to be run as root
```
imho it would be useful to just make a single shared function that can be used to display errors like this across all command groups that need elevated privs.  In the grand scheme of things it is probably a pretty minor point but it seems like we should not be duplicating the same code in multiple places.

**Comment by gvallee** [comment]
It was a change made a couple of weeks ago. Regardless, I updated my PR to avoid code duplication.

**Review by GodloveD — APPROVED** [review]
Thanks for the changes @gvallee.  lgtm pending tests passing.  :shipit:

**Pull request merged**
