### PR TITLE
Stopped test.sh from failing when test user accounts / groups already exist

### PR DESCRIPTION
**Pull request by bauerm97**
Fixes #

Changes proposed in this pull request

 - Ensure test user accounts / groups don't already exist in test.sh

@singularityware/singularity-admin

### CODE REVIEW

**Comment by bbockelm** [comment]
Hi - I actually have a separate fix for this here:

https://github.com/singularityware/singularity/pull/394/commits/e26b3058c8a644984235beb90ecdce6240fc154f

Can we cherry-pick that instead?  I'd prefer to avoid removing system users if possible.

**Comment by bauerm97** [comment]
@bbockelm Yea, that works too. I just hadn't seen that your other PR is fixing this. I think it would also work if we just removed the stest from the lines (so it doesn't stop when it hits this error). Or, tell stest that 0/9 are acceptable return values (is this even possible?). Either way, I think it's reasonable to do this in a separate PR and push this through quickly since it's a bit annoying currently.

EDIT: Also if you can hop on slack I have a question for you about something @vsoch and I have been discussing recently

**Comment by gmkurtzer** [comment]
Which one of these should I merge (#405 or #406)?

**Comment by bauerm97** [comment]
@gmkurtzer Your call, they're identical in every way. Maybe just go with @bbockelm s branch? I'll go ahead and close this PR

**Comment by gmkurtzer** [comment]
Thanks!

**Pull request closed without merging**
