### PR TITLE
Add bind mounts to slurm support, and clarify options

### PR DESCRIPTION
**Pull request by djw8605**
After testing with real user's feedback, we have made changes to the Slurm support for singularity.

Changes proposed in this pull request:

- Added some return value checks.
- Renamed option --image to --singularity-image.
- Added --singularity-bind option
- Added "spank/singularity" string in format string passed to slurm_error().
- Wrapped lines that spanned more than 80 characters where I could.

@singularityware-admin

### CODE REVIEW

**Comment by djw8605** [comment]
@bbockelm As the original contributor of the slurm support, could you take a look at this pull request.

**Comment by gmkurtzer** [comment]
Hi @djw8605,

This looks fantastic! Can you rebase or resubmit this PR against the development branch (as opposed to master)? Sorry about the confusion in branches, we are moving to the standard GitFlow model as soon as we get 2.3 released.

Thank you!

**Comment by djw8605** [comment]
Great!  @gmkurtzer I was able to change the "base" of this pull request.

Could you look at the conflict, it looks like you changed it to use the function `singularity_registry_get` instead of `envar_path`.  I'm not familiar with this function, possibly you could help resolve this conflict?

**Comment by gmkurtzer** [comment]
I resolved it via the web interface, can you test it?

Thanks!

**Comment by gmkurtzer** [comment]
I am inclined to accept this PR as it stands considering I am pretty sure that the SLURM support as it stands in the development branch right now doesn't work.

@djw8605 If you have an opportunity to test and find any issues, let's open another PR.

Thanks!

**Comment by djw8605** [comment]
Thank you very much @gmkurtzer.  I was waiting on my sys admin here to build and install the new version to test it.

Thank you very much, I will open an issue or PR if we find anything not working.

**Pull request merged**
