### PR TITLE
added example build-singularity

### PR DESCRIPTION
**Pull request by GH-maggio**
## Description of the Pull Request (PR):

New example; definition file creates a container to build rpm/deb packages for local install.

### This fixes or addresses the following GitHub issues:

 - Fixes #

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by dtrudg — COMMENTED** [review]
Hi @GH-maggio - this looks pretty neat to me as something under `examples`. I think it site okay there as something that we might not officially support but is useful to people.

Going to ping @gmkurtzer here for his thoughts, as he used to do something similar, and may have thoughts about any stance on bringing package builds like this into the main tree in some way.

**Comment by GH-maggio** [comment]
I originally threw it together as a more advance tutorial exercise since I'm learning singularity; I don't believe it should be used in a production environment (missing alot of package metadata) but as example of what singularity can do for a user.

**Comment by dtrudg** [comment]
pinging @gmkurtzer @ikaneshiro @jfrey - any thoughts r.e. inclusion? Seems reasonable to me as an example, but not an officially promoted / supported way of building packages.

**Comment by dtrudg** [comment]
In the absence of any other comment I'll merge this now. Thanks @GH-maggio

**Review by dtrudg — APPROVED** [review]

**Pull request merged**
