### PR TITLE
Fix cgroup test panic

### LINKED ISSUE #3559: make testall fails because of cgroups_linux_test.go
## Version of Singularity:

Master on Ubuntu.

### Expected behavior

`make testall` should not fail.

### Actual behavior

```
--- FAIL: TestCgroups (0.01s)
    cgroups_linux_test.go:56: open /sys/fs/cgroup/blkio/singularity/12690/blkio.weight: permission denied
    cgroups_linux_test.go:63: can't determine cgroups root path, is cgroups enabled ?
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x8875c8]

goroutine 6 [running]:
testing.tRunner.func1(0xc0000cc200)
	/usr/local/go/src/testing/testing.go:830 +0x68a
panic(0x8e35c0, 0xc86c30)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
github.com/sylabs/singularity/internal/pkg/cgroups.(*Manager).Remove(0xc0000d7ed0, 0xc0000d7e80, 0x1)
	/home/gvallee/go/src/github.com/sylabs/singularity/internal/pkg/cgroups/cgroups_linux.go:133 +0x68
runtime.Goexit()
	/usr/local/go/src/runtime/panic.go:406 +0xed
testing.(*common).FailNow(0xc0000cc200)
	/usr/local/go/src/testing/testing.go:609 +0x5b
testing.(*common).Fatalf(0xc0000cc200, 0x94bfc6, 0x37, 0x0, 0x0, 0x0)
	/usr/local/go/src/testing/testing.go:672 +0x9f
github.com/sylabs/singularity/internal/pkg/cgroups.TestCgroups(0xc0000cc200)
	/home/gvallee/go/src/github.com/sylabs/singularity/internal/pkg/cgroups/cgroups_linux_test.go:63 +0xc70
testing.tRunner(0xc0000cc200, 0x94e8e8)
	/usr/local/go/src/testing/testing.go:865 +0x164
created by testing.(*T).Run
	/usr/local/go/src/testing/testing.go:916 +0x69a
FAIL	github.com/sylabs/singularity/internal/pkg/cgroups	0.026s
```

### Steps to reproduce behavior

`make testall`

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Title

**This fixes or addresses the following GitHub issues:**

- Fixes #3559

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by mem — APPROVED** [review]
I'm going to trust you that this is the correct fix.

**Comment by jscook2345** [comment]
I will test the PR quick. I don't think we `testall` in any of our builds atm.

**Comment by jscook2345** [comment]
@cclerget 

The panic is gone, but the permission denied error is still there.

```
--- FAIL: TestCgroups (0.02s)
    cgroups_linux_test.go:56: open /sys/fs/cgroup/blkio/singularity/6029/blkio.weight: permission denied
FAIL
```

I'm not sure this was meant to fix that, however. So I also approve of this PR. Feel free to merge at your leisure!

**Review by jscook2345 — APPROVED** [review]
LGTM, assuming permission denied error was not meant to be addressed by this PR.

**Pull request merged**
