### PR TITLE
Debian squashfs-tools dependency

### PR DESCRIPTION
**Pull request by dexter2cz**
**Description of the Pull Request (PR):**

Added squashfs-tools as debian dependency

**This fixes or addresses the following GitHub issues:**

- Ref: #1090

**Checkoff for all PRs:**

- [ ] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin @yarikoptic

### CODE REVIEW

**Review by GodloveD — APPROVED** [review]
This looks good to me.

**Comment by GodloveD** [comment]
Tagging with bug so it gets our attention and makes it into the 2.4.1 release.

**Comment by vsoch** [comment]
@GodloveD we would want every PR to have a clean line added to the CHANGELOG no?

**Comment by GodloveD** [comment]
I think we only want things in the changelog that impact the user interface.  For instance, if you refactor a library, but it is exactly the same from a user's point of view.  I don't think it belongs in the changelog.  Otherwise the change log is just a copy of the git log.

**Comment by vsoch** [comment]
+1, and it's always good to ask/check!

**Comment by yarikoptic** [comment]
changes to debian/  are subject to be noted in debian/changelog.  The purpose is to have the log describing changes to packaging. git clone of the repo might not be available.

BTW -- note that changes to debian/ in this repo aren't automagically picked up by me for the official debian package.  that one is packaged out of released source tarballs and its "main" git at https://anonscm.debian.org/git/collab-maint/singularity-container.git  .  I feel that we might better avoid such dichotomy one way or another

**Comment by vsoch** [comment]
how do you  think is best to go about it?

**Comment by yarikoptic** [comment]
If noone uses `debian/` within this (upstream) codebase, then the best, while also staying inline with the debian community, is just remove `debian/` here and add a note that patches to packaging should be submitted to Debian (`reportbug` tool).
But if someone sees the value of having debian packaging straight in this repo, we could come up with other approaches

**Comment by vsoch** [comment]
@olifre I think you added the debian changelog, what are your thoughts on this? We could maintain one changelog here, and then @yarikoptic references to update his, or the equivalent with two. @yarikoptic I think (maybe?) the general idea was to make the packaging possible from this repo (@olifre can comment) in which case, what are  your thoughts on that?

**Comment by olifre** [comment]
@vsoch I did not add the changelog, I only complained when it was not updated with the last release, and added a line to the release checklist to keep it updated ;-). 
As you can see from #1057 , people appear to use the `debian/` files within this repo to build packages. 

I can only speak for us: We generally pull packaging code from a distro (e.g. debian) and base our build to roll out on our cluster and desktops on their packaging (we do our on packaging for some things to have better control over "when updates are rolled out" and have updates in-sync between RedHat and Debian). 
On the other hand, if the packaging code in the project is well maintained and updated (e.g. with new dependencies), this allows both the distro to base their initial packaging on it, and allows users to base their packaging on it. 
So I'd think it's nice to have packaging code "someplace singularity maintained" to give all distros and users a good starting point. It's also a clean place to document new dependencies, and would allow you to offer independently built deb's and rpm's easily, if you decide to do that. 

Of course, if there is someone within the singularity team who has a short turnaround time to contribute directly to debian ( @yarikoptic ?) and feels detecting new dependencies is possible without maintained packaging code directly in Singularity, that's fine with me. Then I'll keep looking at official debian packaging and pull from there. 

Maybe, in this context, I should also mention https://github.com/singularityware/singularity/pull/1093 which still has entered neither the singularity packaging code nor debian.

**Comment by vsoch** [comment]
@yarikoptic and @dexter2cz I don't have much opinion here - what is your preference?

**Comment by gmkurtzer** [comment]
This looks good to me, so I'm gonna merge. Thanks!

**Pull request merged**
