### PR TITLE
Consolidate mounting code

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

The motivation for this PR is to get ready for another PR to address issue #1207, although I think it has quite a bit of merit on its own.  It eliminates a lot of duplicated code dealing with mounting and overlay mountpoint creation and moves it into a common function.  Mounts are put onto a queue and then one function handles them in the order they were requested.  Functionality should be almost identical as before, with only minor changes that I don't expect anyone to notice.

**This fixes or addresses the following GitHub issues:**

- It is a precursor to a fix for #1207.

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by DrDaveD** [comment]
Rebased against current development-2.x

**Comment by DrDaveD** [comment]
Rebased again on current development-2.x

**Comment by DrDaveD** [comment]
Rebased to development-2.x

**Comment by DrDaveD** [comment]
Rebased again on current development-2.x

**Comment by DrDaveD** [comment]
Debian travis builds failed at least as of [this commit](https://github.com/singularityware/singularity/commit/41229565eedb14b196423e603fee23141a780a18#diff-67e997bcfdac55191033d57a16d1408aR2), not due to this PR.

**Comment by DrDaveD** [comment]
Rebased again on development-2.x

**Comment by DrDaveD** [comment]
Rebased on development-2.x at tag of 2.6.0-rc2

**Comment by DrDaveD** [comment]
@godloved I can't reopen, please reopen it.  I rebased against release-2.6.

**Comment by GodloveD** [comment]
@DrDaveD we've had several conversations about this through PM and email.  Seems pretty clear that there is no appetite on our end to merge this into the 2.x branch right?  And the 2.x branch is now officially closed to new features.  That being the case, I'm sorry but I don't see a point in re-opening this PR.  

Thanks very much for your contributions.  I encourage you to switch any development efforts you wish to make to the master branch (formerly development-3.0).

**Comment by DrDaveD** [comment]
@godloved It is understood that this won't get integrated into a release but it is integrated into EPEL and an open PR helps to keep the patch up to date when I need to rebase, and it also runs the helpful travis checks.   Can it be reopened or do I need to make a new PR?

**Comment by GodloveD** [comment]
Hi @DrDaveD.  If it is convenient for you, I can re-open.  

EDIT:  Actually, it looks like I cannot reopen this PR either.  It's complaining that the PR was force-pushed or recreated?  Don't know.  

screen shot 2018-08-06 at 8 14 07 am

Do you want to copy the changes and submit a new PR?  Alternately, I think that you can actually rebase through the git cli and you can set travis up to work on your own fork too so that your branches go through the same tests as those on the main repo.

**Comment by DrDaveD** [comment]
I will submit a new PR

**Pull request closed without merging**
