### PR TITLE
Adding more universal tar support

### PR DESCRIPTION
**Pull request by jekriske**
**Description of the Pull Request (PR):**

This pull request adds support for tar.bz2, tar.xz, and a number of other extensions.

Instead of limiting tar compression support to only a few extensions, this pull request expands the number of extensions to cover all common compression algorithms. It uses tar's built-in compression algorithm detection instead of hardcoding algorithm flags. This also allows for incorrect compression extensions as long as they are supported by tar.

The help files used to claim bz2 support even though tar.bz2 was never actually supported because it wasn't listed as a valid extension. 

**This fixes or addresses the following GitHub issues:**

- Ref: #1154

**Checkoff for all PRs:**

- [X] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [X] I have tested this PR locally with a `make test`
- [X] This PR is NOT against the project's master branch
- [X] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
I haven't tested manually with the different extensions, but the change is simple and as @jekriske mentioned if the algorithm can figure out the type automatically, it's a better approach to do that than hard code extensions. This TGTM if you want to look @GodloveD @gmkurtzer

**Comment by GodloveD** [comment]
Can somebody verify that this works on Alpine before we give the go-ahead?

**Comment by vsoch** [comment]
How does one test on alpine? @truatpasteurdotfr I know I've associated alpine and busybox expertise with you in the past, is this something you could test? Or tell me how to do it?

**Comment by jekriske** [comment]
@vsoch Alpine uses gnu tar and gnu tar supports tar -xf 
You can test with Singularity using:
```
BootStrap: docker
From: alpine:latest

%post
apk add --no-cache alpine-sdk linux-headers openssl-dev automake autoconf util-linux-dev libtool libuuid python gzip bzip2 xz wget git
git clone https://github.com/jekriske/singularity.git --branch xz_support singularity_
cd singularity_
./autogen.sh
./configure --prefix=/usr/local --sysconf=/etc
make
make install
singularity pull shub://jekriske/lolcow:lowfat
singularity image.export jekriske* | xz -c - > /lolcow.tar.xz


%runscript
  exec singularity run /lolcow.tar.xz
```
then 
`sudo singularity run your_image_name`

**Comment by vsoch** [comment]
Thanks @truatpasteurdotfr Did you run into this issue with the recipe? I tried with sudo and without during the build, same both times

```
Progress |===================================| 100.0% 
Done. Container is at: /singularity_/jekriske-lolcow-master-lowfat.simg
+ singularity image.export+ xz jekriske-lolcow-master-lowfat.simg
 -c -
ERROR  : Could not virtualize mount namespace: Operation not permitted
ABORT  : Retval = 255
Adding runscript
```

**Comment by jekriske** [comment]
@vsoch 
I was running it in an ubuntu 16.04 vagrant box with singularity 2.4.1-master.gf2d7795 and ubuntu 17.10 with singularity 2.4.1-release-2.4.g56581cf3 and I always used sudo.
I can confirm that if the host is running singularity from the development branch it results in the error you encountered. The development version doesn't like running Singularity in a Singularity container :(

**Comment by vsoch** [comment]
@jekriske do you mean testing generally, or testing on alpine with the recipe above? I just tested on ubuntu 16.04, using the PR branch both for the host install of singularity, and the install of the container inside to then export and run via the runscript.

**Comment by jekriske** [comment]
@vsoch testing with that recipe for an alpine container... the PR is based on the development branch so using that on the host won't work. You'd have to use release-2.4 or the master branch to run the PR singularity inside singularity. (if that makes sense)
[the capability of running singularity inside singularity is broken in the development branch]

**Comment by vsoch** [comment]
okay, second time is the charm! 

```
# master branch
git clone git@github.com:singularityware/singularity.git
cd singularity/
./autogen.sh
./configure --prefix=/usr/local
make
sudo make install
gedit Singularity # created recipe from above
sudo singularity build container.simg Singularity 
sudo singularity run container.simg 
sudo singularity run container.simg 
Opening tar archive, stand by...
 _________________________________________
/ I hate trolls.  Maybe I could metamorph \
| it into something else -- like a        |
| ravenous, two-headed, fire-breathing    |
| dragon.                                 |
\                 -- Willow               /
 -----------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||
```
Note that the run command doesn't work without sudo. Overall, verified works on alpine for this compression type, with sudo.

**Review by GodloveD — COMMENTED** [review]
Sorry for the long turnaround time on this.  It looks good to me.  If you will kindly add these changes to [CHANGELOG.md](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) (which I think did not exist when you first wrote this PR) I will be happy to approve.  If @vsoch also approves, I think we can go ahead and merge into development.  Thank you!

**Comment by vsoch** [comment]
Yes! Based on the answers to my initial questions and then a successful test I approve. This simplifies the code base quite nicely and adds functionality, both things I am hugely in support of. @GodloveD +1 to add a note to the changelog, that would be the final additional before merge.

**Comment by jekriske** [comment]
Added an entry to the changelog, thanks!

**Review by vsoch — APPROVED** [review]

**Review by GodloveD — APPROVED** [review]

**Comment by GodloveD** [comment]
Thank you!

**Pull request merged**
