### PR TITLE
Simplification of logger

### PR DESCRIPTION
**Pull request by vsoch**
This is a simplification of the logger, to not use python's and to match the Singularity C code, allowing for a bit more flexibility in functionality.  It works as follows:

Here is the standard, regular verbosity:

```bash
vanessa@som-ctp:/tmp$ singularity import ubuntu.img  docker://ubuntu:latest
Docker image path: index.docker.io/library/ubuntu:latest
Cache folder set to /home/vanessa/.singularity/docker
Importing: base Singularity environment
Importing: /home/vanessa/.singularity/docker/sha256:d54efb8db41d4ac23d29469940ec92da94c9a6c2d9e26ec060bebad1d1b0e48d.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:f8b845f45a87dc7c095b15f3d9661e640ebc86f42cd8e8ab36674846472027f7.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:e8db7bf7c39fab6fec91b1b61e3914f21e60233c9823dd57c60bc360191aaf0d.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:9654c40e9079e3d5b271ec71f6d83f8ce80cfa6f09d9737fc6bfd4d2456fed3f.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:6d9ef359eaaa311860550b478790123c4b22a2eaede8f8f46691b0b4433c08cf.tar.gz
Importing: /home/vanessa/.singularity/metadata/sha256:fe44851d529f465f9aa107b32351c8a0a722fc0619a2a7c22b058084fac068a4.tar.gz
```

Notice the difference now is that INFO statements (previously printed like INFO:python Hello! are now just printed without the prefix. Here is quiet mode:

```bash
vanessa@som-ctp:/tmp$ singularity -q import ubuntu.img  docker://ubuntu:latest

```

and here is debug, notice that I've changed a lot of the levels to be more specific (verbose vs. debug, we weren't using any verbose levels before). The one issue I see is that some of my prints follow some of yours and there isn't a newline - eg:

```bash
Exec'ing: /usr/local/libexec/singularity/cli/import.exec ubuntu.imgVERBOSE2 SINGULARITY_COMMAND_ASIS found as False
```

I added my newline after - is there a good way to make this consistent?

```bash
vanessa@som-ctp:/tmp$ singularity --debug import ubuntu.img  docker://ubuntu:latest
enabling debugging
ending argument loop
Exec'ing: /usr/local/libexec/singularity/cli/import.exec ubuntu.imgVERBOSE2 SINGULARITY_COMMAND_ASIS found as False
VERBOSE2 SINGULARITY_ROOTFS not defined (None)
VERBOSE2 SINGULARITY_METADATA_FOLDER found as None/.singularity.d
VERBOSE2 SINGULARITY_DISABLE_CACHE found as False
VERBOSE2 SINGULARITY_CACHEDIR found as /home/vanessa/.singularity
VERBOSE2 SINGULARITY_ENVBASE found as None/.singularity.d/env
VERBOSE2 SINGULARITY_LABELFILE found as None/.singularity.d/labels.json
VERBOSE2 SINGULARITY_INCLUDECMD found as False
VERBOSE2 SINGULARITY_PULLFOLDER found as /tmp
VERBOSE2 SINGULARITY_CONTENTS found as /tmp/.singularity-layers.FBK2rXJD
VERBOSE2 SINGULARITY_CONTAINER found as docker://ubuntu:latest
DEBUG Found uri docker://
DEBUG 
*** STARTING DOCKER IMPORT PYTHON  ****
DEBUG Docker layers and (env,labels,runscript) will be written to: /tmp/.singularity-layers.FBK2rXJD
VERBOSE2 SINGULARITY_DOCKER_USERNAME not defined (None)
VERBOSE2 SINGULARITY_DOCKER_PASSWORD found
DEBUG Starting Docker IMPORT, includes environment, runscript, and metadata.
VERBOSE Docker image: ubuntu:latest
VERBOSE2 Specified Docker ENTRYPOINT as %runscript.
DEBUG Headers found: Accept,Content-Type
VERBOSE Registry: index.docker.io
VERBOSE Namespace: library
VERBOSE Repo Name: ubuntu
VERBOSE Repo Tag: latest
VERBOSE Version: None
VERBOSE Obtaining tags: https://index.docker.io/v2/library/ubuntu/tags/list
DEBUG GET https://index.docker.io/v2/library/ubuntu/tags/list
DEBUG GET https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/ubuntu:pull
DEBUG Headers found: Accept,Authorization,Content-Type
DEBUG GET https://auth.docker.io/token?service=registry.docker.io&scope=repository:library/ubuntu:pull
DEBUG Headers found: Accept,Authorization,Content-Type
Docker image path: index.docker.io/library/ubuntu:latest
VERBOSE Obtaining manifest: https://index.docker.io/v2/library/ubuntu/manifests/latest
DEBUG GET https://index.docker.io/v2/library/ubuntu/manifests/latest
DEBUG Image manifest version 2.2 found.
DEBUG Adding digest sha256:d54efb8db41d4ac23d29469940ec92da94c9a6c2d9e26ec060bebad1d1b0e48d
DEBUG Adding digest sha256:f8b845f45a87dc7c095b15f3d9661e640ebc86f42cd8e8ab36674846472027f7
DEBUG Adding digest sha256:e8db7bf7c39fab6fec91b1b61e3914f21e60233c9823dd57c60bc360191aaf0d
DEBUG Adding digest sha256:9654c40e9079e3d5b271ec71f6d83f8ce80cfa6f09d9737fc6bfd4d2456fed3f
DEBUG Adding digest sha256:6d9ef359eaaa311860550b478790123c4b22a2eaede8f8f46691b0b4433c08cf
VERBOSE Obtaining manifest: https://index.docker.io/v2/library/ubuntu/manifests/latest
DEBUG GET https://index.docker.io/v2/library/ubuntu/manifests/latest
Cache folder set to /home/vanessa/.singularity/docker
VERBOSE3 Found Docker command (Entrypoint) None
VERBOSE3 Found Docker command (Cmd) /bin/bash
VERBOSE3 Adding Docker CMD as Singularity runscript...
DEBUG /bin/bash
VERBOSE3 Found Docker command (Env) PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
VERBOSE3 Found Docker container environment!
VERBOSE3 Adding Docker environment to metadata tar
DEBUG Found template for tarinfo
VERBOSE3 Found Docker command (Labels) {}
VERBOSE3 Adding Docker labels to metadata tar
DEBUG Found template for tarinfo
VERBOSE3 Adding Docker runscript to metadata tar
DEBUG Found template for tarinfo
DEBUG metadata file /home/vanessa/.singularity/metadata/sha256:fe44851d529f465f9aa107b32351c8a0a722fc0619a2a7c22b058084fac068a4.tar.gz already exists, will over-write.
VERBOSE2 Tar file with Docker env and labels: /home/vanessa/.singularity/metadata/sha256:fe44851d529f465f9aa107b32351c8a0a722fc0619a2a7c22b058084fac068a4.tar.gz
VERBOSE3 Writing Docker layers files to /tmp/.singularity-layers.FBK2rXJD
VERBOSE2 Writing file /tmp/.singularity-layers.FBK2rXJD with mode w.
VERBOSE2 Writing file /tmp/.singularity-layers.FBK2rXJD with mode a.
DEBUG *** FINISHING DOCKER IMPORT PYTHON PORTION ****
Importing: base Singularity environment
.
.
.
```
For the logger newline, it seems to work ok when I test locally:

```bash
In [1]: from message import bot

In [2]: bot.debug('hello!')
DEBUG hello!
```

@singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
ah yes, this is also updating singularity.help, and making the metadata write to a different folder in cache! This should close #561  and #562 

```bash
Importing: /home/vanessa/.singularity/metadata/sha256:e80c0a66921eec6dd79953e0a070d6e3aaba56ed01a002d7d53c3ac48913813b.tar.gz
```

**Comment by vsoch** [comment]
you know, we could potentially do some cool other stuff - a logger is essentially the image's voice / speaking when it's being built, and we could send that to different places where the image might want to communicate (eg, as a post to some http based endpoint if the user has an API, to a socket of some kind, or as a communication at the end of a build or run to trigger the start of another process). We could also save the build log in the metadata folder, so there is a record of how it's built, and you could use a similar function to write to it as is done for the json labels in C. @gmkurtzer thoughts?

**Comment by vsoch** [comment]
@gmkurtzer ready for review!

**Comment by gmkurtzer** [comment]
This is working great, I'm merging it! Thanks!

**Pull request merged**
