### PR TITLE
`-f/--file` option restored to export command in export.exec and export.help

### PR DESCRIPTION
**Pull request by ArangoGutierrez**
Changes proposed in this pull request

 - `-f/--file` option restored to export command in export.exec and export.help

@singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
This option is no longer supported. https://github.com/singularityware/singularity/issues/610#issuecomment-294570584

**Comment by gmkurtzer** [comment]
Hi @ArangoGutierrez,

This looks good, but check the CI failure:

https://travis-ci.org/singularityware/singularity/builds/223749358#L3522

Thanks!

**Comment by ArangoGutierrez** [comment]
Hi @gmkurtzer Done!  

Green travis !

**Comment by gmkurtzer** [comment]
Actually, the problem was fixed by `SINGULARITY_EXPORT_FILE=""` as that defined the variable. The error you were getting was because the variable was not defined (not the quotes, but quotes are good). Another fix, and what I would recommend would be to instead get rid of the above line and do this to your conditional:

```
if [ -n "${SINGULARITY_EXPORT_FILE:-}" ]; then
```

**Comment by gmkurtzer** [comment]
Looks good! Now just one more thing to do. Can you write a few tests for this in `tests/28-importexport.sh`?

Then it will be ready to merge! Well done!

**Comment by gmkurtzer** [comment]
It looks good! Well done! I will test it locally here shortly.

**Comment by gmkurtzer** [comment]
Merged, thanks!

**Pull request merged**
