### PR TITLE
change scope of "defer" used inside of for loops

### PR DESCRIPTION
**Pull request by PaulCharlton**
change scope of "defer" used inside of for loops by adding local closure or named function -- to prevent potential leaks of "defer" stacking up from each loop iteration

## Description of the Pull Request (PR):

 - Fixes # 6266

### CODE REVIEW

**Comment by DrDaveD** [comment]
Please be more descriptive in git commit descriptions.  Fix by force-push. 

In the description, remove space after '#' so github will link to the issue and show the title.

**Comment by DrDaveD** [comment]
The e2e_tests failure should be fixed by rebasing on the current master after pr #6300.

You seem to have attempted to fix the short_unit_tests in PR #6294 but I don't think that was the correct fix.  It is more likely caused by the changes you made to socket_test.go.

**Comment by PaulCharlton** [comment]
@DrDaveD yes and yes.   My apologies for littering.  I need to get everything working locally before I submit more commits.

**Comment by DrDaveD** [comment]
Helpful hint: if you create a PR against your own repository, all the github actions also run and it's a good way to test things without creating noise.

**Comment by DrDaveD** [comment]
@PaulCharlton If you'd like this to get in please resubmit it to https://github.com/apptainer/apptainer

**Pull request closed without merging**
