### PR TITLE
fixing pull for shub when directory specified

### PR DESCRIPTION
**Pull request by vsoch**
**Description of the Pull Request (PR):**

This PR will fix the singularity hub pull command so specifying a name with a directory will not error! See #847 

Attn: @singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
@pditommaso this should fix the issue! Do you want to test?

**Comment by pditommaso** [comment]
Master branch?

**Comment by vsoch** [comment]
Oh no, you would need to pull the PR branch:

```
git checkout -b vsoch-shub/fix-pull development
git pull https://github.com/vsoch/singularity.git shub/fix-pull
```

**Comment by pditommaso** [comment]
Fixed 👍 ! 

Any ETA for 2.3.2 release?

**Comment by vsoch** [comment]
haha, TBA not any time soon! There is a lot in the works, and I think @gmkurtzer is a little backlogged (look at the number of PRs waiting!) Don't worry, we will/are doing our best! :running_man: :running_woman:

**Comment by pditommaso** [comment]
[Continuous delivery](https://en.wikipedia.org/wiki/Continuous_delivery) is good! 😉

**Comment by gmkurtzer** [comment]
This looks good to me, merging! Thanks!

**Pull request merged**
