### PR TITLE
Replace +dirty by -dirty to be compatible with semantic version

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Replace `+dirty` by `-dirty` to be compatible with semantic version. @mem do you see any side effects with this change ?

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by dtrudg — COMMENTED** [review]
@cclerget - can you give an example of when it causes a problem to have `+dirty`? `+dirty` should be valid from my reading of https://semver.org/

**Comment by cclerget** [comment]
@dctrud Typically while developping and when you didn't commit change, when you run e2e tests and hit the version test, if singularity has a version like `3.5.2+152-g75f4433c0+dirty`, the test fail as two consecutives `+` is not valid semantic version and means we have two build part, so changing it to `3.5.2+152-g75f4433c0-dirty` just make it valid with `152-g75f4433c0-dirty` as the build part

**Comment by dtrudg** [comment]
> @dctrud Typically while developping and when you didn't commit change, when you run e2e tests and hit the version test, if singularity has a version like `3.5.2+152-g75f4433c0+dirty`, the test fail as two consecutives `+` is not valid semantic version and means we have two build part, so changing it to `3.5.2+152-g75f4433c0-dirty` just make it valid with `152-g75f4433c0-dirty` as the build part

This looks good to me for that situation. However, if we have checkout a tag, e.g. `v3.5.2` and then make it dirty would we have then `3.5.2-dirty` instead of `3.5.2+dirty`?

**Comment by cclerget** [comment]
> This looks good to me for that situation. However, if we have checkout a tag, e.g. v3.5.2 and then make it dirty would we have then 3.5.2-dirty instead of 3.5.2+dirty?

Yes ... By adding a check to conditionally set the dirty part to either `-dirty` or `+dirty` depending of a previous `+` presence that should generate a usable version in all cases right ?

**Comment by dtrudg** [comment]
> > This looks good to me for that situation. However, if we have checkout a tag, e.g. v3.5.2 and then make it dirty would we have then 3.5.2-dirty instead of 3.5.2+dirty?
> 
> Yes ... By adding a check to conditionally set the dirty part to either `-dirty` or `+dirty` depending of a previous `+` presence that should generate a usable version in all cases right ?

Yes - that sounds good to me :+1:

**Review by dtrudg — APPROVED** [review]
This seems to work fine for the situations I can see. Off a tag we have e.g. `3.5.2-dirty` and not `3.5.2+dirty` but I don't see any issue with that.

**Pull request merged**
