### PR TITLE
Fix RPMPREFIX on el6 and el7

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

This fixes RPMPREFIX for el6 and el7

**This fixes or addresses the following GitHub issues:**

- Addresses post-merge comments on the PR that enabled the feature, #2621 

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by hpcdevops** [comment]
@DrDaveD ...

I've confirmed that while this change does drop man pages in the `RPMPREFIX` on CentOS 6 a side effect is that man pages are no longer compressed by `/usr/lib/rpm/redhat/brp-compress` which expects them to be in a path starting with `./usr/...`.

The appears to be a quirk of CentOS 6 (inherited from Redhat) and I'm not sure it's worth quibbling over.

Another thing that *is* fairly consistent in the macros provided by the rpm RPM though is that `%_mandir` is almost always defined as `%{_datarootdir}/man` with `%_datarootdir` itself defined as `%{_prefix}/man`.

Perhaps it's better to define and pass down `%_datarootdir` to get more consistent behavior across OS'es that build RPMs?

As an aside...

I notice that you don't appear to have sync'd the 3.1.0-rc# tags to your fork. This causes auto-configuration of RPM `VERSION` (using `git describe...`) to be inconsistent with upstream.

Thanks for getting this updated... again.

**Comment by DrDaveD** [comment]
@hpcdevops thanks for testing, and for noticing the bug in the first place.   Makefile.stub does still define _prefix, which as you pointed out is used by default in _datarootdir (although I think you meant %{_prefix}/share), so _datarootdir is covered for the general case.  In the specific case of el6, /usr/lib/rpm/redhat/macros defines _mandir explicitly not in terms of %{_datarootdir}, so that's why this PR needs to explicitly set _mandir.  Even on el7 that file defines _mandir directly in terms of _prefix, not _datarootdir.

Also, this branch was made after I updated to 3.1.0-rc1 yesterday, so for me git describe says v3.1.0-rc1-3-gaae37fb in the branch.  Do you have the 3.1.0-rc1 tag?  I learned the hard way that it's not sufficient to do "git pull upstream master" in your master branch, you have to do "git fetch upstream" to make sure you get all the latest tags.  I made issue #2268 because I thought syncing tags was even harder than that.

**Comment by hpcdevops** [comment]
@DrDaveD ... you are, of course, correct about my incorrect definition of `%{_datarootdir}` in my previous comment. Bad copy/paste from test machine... 😉 

With regard to which tag is on the repo clone I'm using to build/test...

I'm using a Singularity image to build Singularity and within the image my runscript is cloning your repository in a clean environment and checking out the specified branch.

When I did the build test on my system in that manner my generated RPM had the following name `singularity-3.0.0-1352.gaae37fb.el6.x86_64.rpm`.

**Comment by DrDaveD** [comment]
Ah, that's what you meant.  You didn't [pull in my PR](https://help.github.com/articles/checking-out-pull-requests-locally/) into a clone of the sylabs repository, which is what I usually do when I test a PR.  So the issue is that I didn't do 'git push --tags', which I don't usually do.  I did that now, so a rebuild should show up as 3.1.0-rc1.  But next time it will probably have the same issue because I don't normally keep tags up to date in my github repository.  You could probably work around it by pulling the tags from the sylabs upstream repository into your copy of my repository.

**Comment by DrDaveD** [comment]
@GodloveD @jmstover this is important for 3.1.0 milestone if the release notes mention RPMPREFIX.

**Review by jmstover — APPROVED** [review]

**Pull request merged**
