### PR TITLE
ENH: use flawfinder in test.sh, install flawfinder in travis env

### PR DESCRIPTION
**Pull request by yarikoptic**
locally: fails to run test.sh before flawfinder run 

```
Building test container...
 + sudo singularity create -s 568 container.img                 (retval=0) OK
 + sudo singularity bootstrap container.img /home/yoh/deb/persp (retval=1) ERROR
Setting RELEASE=7
ERROR: Neither yum nor dnf in PATH!
Full output in: /tmp/tmp.RY842ZBOox

```

### CODE REVIEW

**Comment by yarikoptic** [comment]
travis build shows the same error :  https://travis-ci.org/yarikoptic/singularity/builds/144812709

**Comment by gmkurtzer** [comment]
Maybe also do a "apt-get install yum"? I just checked the busybox.net site again, still seems to be down. I just email'ed Erik and Rob to see if it will come back soon. As soon as it does, I will fix the link back to busybox.

**Comment by yarikoptic** [comment]
oh... I was still waiting for travis to run it ;) not sure if it all works... ok, will fix later if it doesn't ;-)  whenever travis gets enabled, you will receive notifications right here in the pull requests so you would know if tests ran/pass/failed

**Comment by yarikoptic** [comment]
still didn't make it to the end:

```
 + sudo singularity copy container.img singularity /            (retval=2) ERROR
/tmp/singularity-test.usj8gk/libexec/singularity/copy.sh: 40: /tmp/singularity-test.usj8gk/libexec/singularity/copy.sh: Bad substitution
Full output in: /tmp/tmp.70y6xkziq8
The command "./test.sh" exited with 1.
```

**Comment by yarikoptic** [comment]
I think I saw such failures whenever that PS4 for set -x mode was too fancy for the shell... but I thought all that was fixed up, so might be smth else ;)

**Comment by gmkurtzer** [comment]
I can't seem to replicate that error locally. Is there a more reliable/portable shell method of extracting arg ranges that you know of?

**Comment by yarikoptic** [comment]
re replicate -- what is your `/bin/sh` pointing to?  if bash, try to change to `dash`

**Comment by gmkurtzer** [comment]
Dash on RHEL/Centos?! LOL....

We should probably rewrite that then to not be so bash'y. How is your shell-fu? ;-)

**Comment by yarikoptic** [comment]
When I do shell I do it in bash :-)
I do fix some bashisms when ppl complain though, but the foo is low ;-)

**Comment by yarikoptic** [comment]
Can you run singularity within singularity? :-)

**Comment by gmkurtzer** [comment]
Oh, well.. the interpreter is set to /bin/bash.. I wonder why it isn't working then. Is /bin/bash linked to /bin/dash? I would doubt that...

Yes, you can sort of run Singularity within a Singularity. You have to be root because Singularity doesn't allow SUID within a container.

**Pull request merged**
