### PR TITLE
Recreating PR#2209 (Allow colon in image names for release-3.0)

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

This allows colons in image names for the release-3.0 branch, in case there's going to be a 3.0.1.  Recreating PR because #2209 refused to run all the circleci pieces.

**This fixes or addresses the following GitHub issues:**

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by DrDaveD** [comment]
Even recreating PR didn't do it, so I recomitted the last commit and did push -f

**Comment by DrDaveD** [comment]
I think I figured out why the get_source and singularity_test circleci tests never run -- they are not referenced at all in .circleci/config.yml.  They were added after the 3.0.0 release.  Apparently the tests to run are a repository-wide setting and not driven from the config.yml file.  Now the go1.11-alpine test is failing too. 

Again, I don't know if it's worth doing anything about because I don't know if there's going to be a 3.0.1.

**Comment by yhcote** [comment]
One thing for sure is that I am changing the parsing code to use awk instead at the moment. It's hard with GNU deviations to make use something that works on Full GNU, then correct, then busybox implementations.

**Comment by DrDaveD** [comment]
Not needed

**Pull request closed without merging**
