### PR TITLE
Inspect command

### LINKED ISSUE #1885: inspect command is not yet supported
## Version of Singularity:
```
$ singularity --version
singularity version 3.0.0-alpha.1-117-gc297513f
```
### Expected behavior

I think what we want to do here is put the metadata into a sif partition (in addition to the `/.singularity.d` directory within the container) and then use sif commands to extract the data instead of mounting the image and parsing the `/.singularity.d` directory.  So there is a bit of work involved in this afaik.   

```
$ singularity inspect my_container
{
    "org.label-schema.usage.singularity.deffile.bootstrap": "docker",
    "org.label-schema.usage.singularity.deffile": "ubuntu.def",
    "org.label-schema.schema-version": "1.0",
    "org.label-schema.usage.singularity.deffile.from": "ubuntu",
    "org.label-schema.build-date": "Tue,_28_Aug_2018_12:03:33_-0400",
    "org.label-schema.usage.singularity.version": "2.5.999-development-2.x-instance-env.a3a35ba",
    "org.label-schema.build-size": "178MB"
}
```
### Actual behavior
```
$ singularity inspect my_container 

Linux container platform optimized for High Performance Computing (HPC) and
Enterprise Performance Computing (EPC)

Usage:
  singularity [global options...]

Description:
  Singularity containers provide an application virtualization layer enabling
  mobility of compute via both application and environment portability. With
  Singularity one is capable of building a root file system and running that
  root file system on any other Linux system where Singularity is installed.

Options:
  -d, --debug              Print debugging information
  -h, --help               help for singularity
  -q, --quiet              Suppress all normal output
  -s, --silent             Only print errors
      --tokenfile string   path to the file holding your sylabs
                           authentication token (default
                           "/home/david/.singularity/sylabs-token")
  -v, --verbose            Increase verbosity +1
      --version            version for singularity

Available Commands:
  build       Build a new Singularity container
  capability  Manage Linux capabilities on containers
  exec        Execute a command within container
  help        Help about any command
  instance    Manage containers running in the background
  keys        Manage OpenPGP key stores
  pull        Pull a container from a URI
  push        Push a container to a Library URI
  run         Launch a runscript within container
  shell       Run a Bourne shell within container
  sign        Attach cryptographic signatures to container
  verify      Verify cryptographic signatures on container
  version     Show application version

Examples:
  $ singularity help
      Will print a generalized usage summary and available commands.

  $ singularity help <command>
      Additional help for any Singularity subcommand can be seen by appending
      the subcommand name to the above command.


For additional help or support, please visit https://docs.sylabs.io
```
### Steps to reproduce behavior
```
$ singularity inspect my_container 
```

### PR DESCRIPTION
**Pull request by ikaneshiro**
Adds support for the `inspect` command by using the singularity engine to mount the image and print the metadata within the container in a similar manner as the current `help` command. This does not implement the `--json` option.

Fixes #1885

### CODE REVIEW

**Review by GodloveD — APPROVED** [review]
This looks ready to go.  I will open a separate issue for the `--json` option.

**Comment by GodloveD** [comment]
!@#$ Looks like the Travis gods are displeased.

**Comment by bauerm97** [comment]
@GodloveD @ikaneshiro :

```
../src/cmd/singularity/cli/inspect.go:52:11: undefined: "github.com/sylabs/singularity/vendor/github.com/singularityware/singularity/src/docs".InspectUse
../src/cmd/singularity/cli/inspect.go:53:11: undefined: "github.com/sylabs/singularity/vendor/github.com/singularityware/singularity/src/docs".InspectShort
../src/cmd/singularity/cli/inspect.go:54:11: undefined: "github.com/sylabs/singularity/vendor/github.com/singularityware/singularity/src/docs".InspectLong
../src/cmd/singularity/cli/inspect.go:55:11: undefined: "github.com/sylabs/singularity/vendor/github.com/singularityware/singularity/src/docs".InspectExample
../src/cmd/singularity/cli/inspect.go:100:14: undefined: "github.com/sylabs/singularity/vendor/github.com/singularityware/singularity/src/pkg/buildcfg".SBINDIR
```

Yep, Ian introduced files with new imports, meaning he needs to change to use `sylabs/singularity` instead of `singularityware/singularity`. Travis will correctly fail until then

**Comment by GodloveD** [comment]
I think this is a small enough change that I'm happy to merge with just a single review.

**Pull request merged**
