### PR TITLE
Fix fedora & epel builds for some architectures

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

After incorporating pr #2472, builds of 3.0.1 for epel fail on the ppc64 architecture because there is no golang package available for that type (only ppc64le), and builds for fedora fail because mconfig does not support the s390x architecture type.  This PR excludes ppc64 builds and changes mconfig to not fail on unrecognized architectures.  An alternative for the latter would be to not even bother to try to figure out the architecture or word size, because the information isn't used for anything.

This pr does not have a dependency on #2472 and is not based on it, it's just that it doesn't improve anything until after #2472 is included.

**This fixes or addresses the following GitHub issues:**

None

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by DrDaveD** [comment]
Trying to kick CircleCI by closing & reopening.

**Comment by DrDaveD** [comment]
Trying close & open again after unfollowing my fork at circleci.com.

**Comment by DrDaveD** [comment]
CircleCI worked but Travis failed this time, sigh.  Trying close & open again to retry it.

**Comment by jscook2345** [comment]
@DrDaveD would this change break building RPMs on PPC architectures?

**Comment by DrDaveD** [comment]
@jscook2345 No, because the only existing PPC architecture support by golang is the ppc64le architecture.  This only excludes ppc64 which would never have worked.

**Comment by DrDaveD** [comment]
So can we go ahead with this?

**Review by jscook2345 — APPROVED** [review]
Sorry! Meant to approve this yesterday! LGTM!

**Pull request merged**
