### PR TITLE
Fix spelling of existent.

### PR DESCRIPTION
**Pull request by markeganfuller**
**Description of the Pull Request (PR):**

Fix spelling of existent:
existant -> existent

**This fixes or addresses the following GitHub issues:**

- Ref: #

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [Author's file](https://github.com/singularityware/singularity/blob/master/AUTHORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
definitely approved by me!

**Comment by vsoch** [comment]
@gmkurtzer this is a tiny PR to fix some spelling errors, should be easy to review and merge.

**Comment by gmkurtzer** [comment]
Oooops, spelling is hard. lol... Thanks everyone!

**Comment by vsoch** [comment]
Spelling is ok (I was pretty good when I was in school) but what doesn't map so cleanly is the connection from brain --> fingers, especially when one is typing quickly, and [this](https://www.mrc-cbu.cam.ac.uk/people/matt.davis/cmabridge/).

Slnielpg is ok (I was pttery good wehn I was in soohcl) but waht dnseot map so cnaely is the ctnicoenon form biarn --> fegrnis, eilclaepsy wehn one is tnipyg qlkciuy.

**Comment by gmkurtzer** [comment]
Is it weird that I find that almost impossible to read?

**Comment by vsoch** [comment]
no, it's pretty darn weird :P

**Pull request merged**
