### PR TITLE
Development 3.0: fix instance hang while starting instance

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

This PR fixes instance start hang while `CreateContainer` method is failing

**This fixes or addresses the following GitHub issues:**

- Ref: #1963 

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by jmstover** [comment]
@cclerget ... 
This is now working correctly, *but* (yes, the dreaded but).... 

```
$ /usr/local/singularity/3.0.0-dev/bin/singularity instance start -B web/htdocs:/usr/local/apache2/htdocs:ro -B web/logs:/usr/local/apache2/logs httpd.sif httpd
$ /usr/local/singularity/3.0.0-dev/bin/singularity instance list
INSTANCE NAME    PID      IMAGE
$
```

It doesn't seem to be writing out the information to `$HOME/.singularity/instances` 

I *think* the writing out was working properly...

**Comment by cclerget** [comment]
@jmstover I think it works, can you check if instance process is running ?

**Comment by jmstover** [comment]
The instance process is running. _but_ it isn't writing out the PID information for `instance list`, or `instance stop`

Do you want a separate issue for that?

**Review by jmstover — APPROVED** [review]
This is starting an instance as expected now.

**Pull request merged**
