### PR TITLE
Tweaking output of progress bar

### PR DESCRIPTION
**Pull request by vsoch**
This will tweak the output to look like this:

```bash
singularity import test.img docker://ubuntu
Docker image path: index.docker.io/library/ubuntu:latest
Cache folder set to /home/vanessa/.singularity/docker
(1/5)Download |========================================| 100.0% layer d54efb8d  
(1/5)Prepare  |========================================| 100.0% layer d54efb8d  
(2/5)Download |========================================| 100.0% layer f8b845f4  
(2/5)Prepare  |========================================| 100.0% layer f8b845f4  
(3/5)Download |========================================| 100.0% layer e8db7bf7  
(3/5)Prepare  |========================================| 100.0% layer e8db7bf7  
(4/5)Download |========================================| 100.0% layer 9654c40e  
(4/5)Prepare  |========================================| 100.0% layer 9654c40e  
(5/5)Download |========================================| 100.0% layer d9ef359e  
(5/5)Prepare  |========================================| 100.0% layer d9ef359e  
Importing: base Singularity environment
Importing: /home/vanessa/.singularity/docker/sha256:d54efb8db41d4ac23d29469940ec92da94c9a6c2d9e26ec060bebad1d1b0e48d.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:f8b845f45a87dc7c095b15f3d9661e640ebc86f42cd8e8ab36674846472027f7.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:e8db7bf7c39fab6fec91b1b61e3914f21e60233c9823dd57c60bc360191aaf0d.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:9654c40e9079e3d5b271ec71f6d83f8ce80cfa6f09d9737fc6bfd4d2456fed3f.tar.gz
Importing: /home/vanessa/.singularity/docker/sha256:6d9ef359eaaa311860550b478790123c4b22a2eaede8f8f46691b0b4433c08cf.tar.gz
Importing: /home/vanessa/.singularity/metadata/sha256:fe44851d529f465f9aa107b32351c8a0a722fc0619a2a7c22b058084fac068a4.tar.gz
```

and shub images are mostly the same, because we only have one, and only one step, it doesn't add value to alert the user of a number or additional descriptors!

```bash
vanessa@som-ctp:/tmp$ singularity pull shub://vsoch/singularity-images
Download |========================================| 100.0% downloading image  
Done. Container is at: ./vsoch-singularity-images-mongo.img
```
@singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
sorry for the extraneous commits - I'm testing on a server because I can't install locally, and had to do that for each time to see the output.

**Comment by gmkurtzer** [comment]
That is the coolest looking thing ever! You rock!

**Comment by satra** [comment]
@vsoch - this appears to work for me: here is a situation showing where things may break:

```
In [14]: for i in range(9): show_progress(i + 1, 9, length=40, prefix='test-foo' ); sleep(0
    ...: .05)
test-foo |========================================| 100.0%   

In [15]: for i in range(**10**): show_progress(i + 1, 9, length=40, prefix='test-foo' ); sleep(
    ...: 0.05)
test-foo |========================================| 100.0%   
test-foo |========================================| 100.0%   
In [16]: 
```

**Comment by vsoch** [comment]
just got back to keyboard - let me test this! So the only difference is 9 vs. 10? I haven't tested this yet, but if there is some bug related to the number of layers, it must be that when I tested, I tested on an image with odd (or whatever x pattern is) number and it worked, and later tried a different number and saw the bug. Give me a few minutes, testing now.

**Comment by vsoch** [comment]
ah I think I figured it out - and it's stupid. The line is just too long, and so it makes a newline. Derpaderp! Let me see if I can redo this, tweak it a bit, and do a new PR so we can count the number of layers.

**Comment by vsoch** [comment]
see https://github.com/singularityware/singularity/pull/605

**Pull request merged**
