### PR TITLE
Fix permission denied during bind of NFS mount point

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

Fix permission denied error while binding NFS mount point when root_squash enabled. Both uid and gid are set to corresponding NFS directory owner

**This fixes or addresses the following GitHub issues:**

- Ref: #1205 #1249 

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [ ] This PR is NOT against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by GodloveD** [comment]
It's been on my list to set up an NFS at home and try to test this PR.  But I see that it is related to https://github.com/singularityware/singularity/issues/1249.  @sheenams and @ttrafford are you able to test this PR in your environments and verify that it fixes the issue?

**Comment by ttrafford** [comment]
I will see what I can do about testing this.  My environment is GPFS with *no* root squash enabled, though (which makes the permission denied stuff especially weird).

**Comment by kav2k** [comment]
@ttrafford I'm seeing similar problems on a GPFS mounted home folder with 2.4.1/2.4.2 but not with 2.4, so hopefully it's the same problem.

Sadly, I'm not administering the system on which it reproduces, so I can't quickly test it in the problematic environment.

**Comment by ttrafford** [comment]
@GodloveD This patch did not fix my specific "Permission Denied" issue.  Mine (which I was assuming was the same as others) can be reproduced by trying to bind a directory like so:

directory /foo is owned by user2:mygroup, permissions 0770
directory /foo/bar is owned by user1:mygroup permissions 0777 (but the parent's permissions are the issue here)

user1 and user2 are both in mygroup.

If user1 trys to bind /foo/bar in a singularity container, they will get a permission denied error.  If I run chmod o+x /foo first then then error goes away.

As I said, I was assuming this was the same problem others were describing, but perhaps not.

**Comment by cclerget** [comment]
@ttrafford Just submitted a new fix which doesn't affect user groups during mount operation. Could you give it a try to see if that fix issue ?

**Comment by ttrafford** [comment]
@cclerget Yes, that does seem to make the problem go away.

**Comment by jlbl** [comment]
Is this branch usable in a production environment?  Alternatively, is there a goal date for a release incorporating this branch?  This is a show stopper for us, but I'm a bit hesitant to deploy a non-released branch across our cluster to resolve it.  Thanks.

**Comment by johnbradley** [comment]
I would also like to see a fix for this issue to make it to production. After deploying singularity to our cluster, the first user interested in using singularity hit this limitation. Thanks.

**Comment by GodloveD** [comment]
Hey @johnbradley I think what's missing on this PR is testing.  It shouldn't be merged into development until at least 2 people have reviewed the code, tested it and found it to be working well or have suggested changes.  Are you able to test this PR on your cluster and tell us whether it works and whether you see any unusual behavior?  The effort would be greatly appreciated!  😄

**Comment by jlbl** [comment]
On Wed, 7 Feb 2018 at 2:21pm, David Godlove wrote

> Hey @johnbradley I think what's missing on this PR is testing.  It 
> shouldn't be merged into development until at least 2 people have 
> reviewed the code, tested it and found it to be working well or have 
> suggested changes.  Are you able to test this PR on your cluster and 
> tell us whether it works and whether you see any unusual behavior?  The 
> effort would be greatly appreciated!  😄

I've built the PR and the users who ran into this issue reported that it 
fixed their issue.  Is there a standard test suite we can run to ensure 
that nothing else got broken?

-- 
Joshua Baker-LePain
QB3 Shared Cluster Sysadmin
UCSF

**Comment by cclerget** [comment]
@jlbl You can run test suite by executing : `make test`

**Comment by GodloveD** [comment]
Yes.  If you do that you will also need to build support for contained builds.  I forget the command.  But if you try to run make test and it fails b/c of that it will give you a message with the command to build that.

**Comment by johnbradley** [comment]
> Are you able to test this PR on your cluster and tell us whether it works and whether you see any unusual behavior? 

I ran `make test` on an Ubuntu 16.04 VM resulting in: `All tests passed`. All tests had `OK` beside them. I didn't see any warning about contained builds. I went through the commands from http://singularity.lbl.gov/quickstart and everything looked fine to me. I will do a more thorough test tomorrow morning.

My user who had the NFS mounting issue tested this branch on a VM and says it resolved his NFS issue.

**Comment by johnbradley** [comment]
I did some more testing of this branch on `Ubuntu 16.04.1 LTS (Xenial Xerus)`.
I was able to pull/shell/run images from shub, dockerhub and quay.
I ran [trim-galore](https://hub.docker.com/r/dukegcb/trim-galore/) in a container processing some example fastq files with various bind settings.

I didn't encounter any problems.

**Comment by cclerget** [comment]
Thank you for testing @johnbradley ! I'm going to ping team to review this PR

**Comment by jlbl** [comment]
On Wed, 7 Feb 2018 at 2:38pm, cclerget wrote

> @jlbl You can run test suite by executing : `make test`

FWIW, I also get "All tests passed" running on CentOS-7.

-- 
Joshua Baker-LePain
QB3 Shared Cluster Sysadmin
UCSF

**Review by yhcote — APPROVED** [review]
Looks good to me

**Pull request merged**
