### PR TITLE
Add/opensuse

### PR DESCRIPTION
**Pull request by dmytro-spodarets**
Fixes #

Changes proposed in this pull request

 -
 -
 -

@singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
hey @FlyElephant-M31 ! Would you be interested in adding this build to [Singularity Hub](http://www.singularity-hub.org)? It basically means having your .def file renamed to Singularity, located in the base of the repo, and then connecting it to Singularity Hub.

**Comment by dmytro-spodarets** [comment]
@vsoch Yes. We will create some of the images for Singularity Hub too ;)

**Comment by vsoch** [comment]
Great! Thanks muchly :) And please let me know if there is additional functionality you would be interested in.

**Comment by gmkurtzer** [comment]
Hi @FlyElephant-M31!

Oh, this is a great feature addition! Sorry for the delay, we have been hammering on the pre-2.3 development code and getting it ready for release. Can you move this PR to the "development" branch and update for the new bootstrap module format so we can include it in the 2.3 release? It should be pretty straight forward, but let me know if you have any questions.

Thanks!

**Comment by gmkurtzer** [comment]
Ping @FlyElephant-M31!

**Comment by gmkurtzer** [comment]
@FlyElephant-M31, We are getting close to releasing 2.3, and would love to have this support. Any chance on getting it ported to the development branch?

Thank you!

**Comment by gmkurtzer** [comment]
This has been implemented via #688. Closing.

**Pull request closed without merging**
