### PR TITLE
Fail if tried to remote build a sandbox container

### LINKED ISSUE #2415: Remote building with `--sandbox` doesn't produce a sandbox container
## Version of Singularity:

```
3.0.1-145.gc9822fec
```

### Expected behavior:

Build succeeds, and produce a sandbox container:

```
$ singularity build --remote --sandbox sand.sif docker://ubuntu:latest
[...]
$ ls
sand.sif  # a sandbox directory
```

<br>

### Actual behavior

Does not producing a sandbox container:

```
$ singularity build --remote --sandbox sand.sif docker://ubuntu:latest
Getting image source signatures
Copying blob sha256:32802c0cfa4defde2981bec336096350d0bb490469c494e21f678b1dcf6d831f
 30.62 MiB / 30.62 MiB  1s
Copying blob sha256:da1315cffa03c17988ae5c66f56d5f50517652a622afc1611a8bdd6c00b1fde3
 847 B / 847 B  0s
Copying blob sha256:fa83472a3562898caaf8d77542181a473a84039376f2ba56254619d9317ba00d
 556 B / 556 B  0s
Copying blob sha256:f85999a86bef2603a9e9a4fa488a7c1f82e471cbb76c3b5068e54e1a9320964a
 162 B / 162 B  0s
Copying config sha256:dec80b78b0e6d45cbe2e098c747d28dc7c4ca39cab2608fe22790e68098ae7c4
 2.42 KiB / 2.42 KiB  0s
Writing manifest to image destination
Storing signatures
INFO:    Creating SIF file...
INFO:    Build complete: /tmp/image-242422562
INFO:    Now uploading /tmp/image-242422562 to the library
 26.69 MiB / 26.69 MiB  100.00% 31.69 MiB/s 0s
INFO:    Setting tag latest
 26.69 MiB / 26.69 MiB [=========================================================================================================================================] 100.00% 3.27 MiB/s 8s
$ ls
sand.sif  # not a directory
```

<br>

### Steps to reproduce behavior

```
$ singularity build --remote --sandbox sand.sif docker://ubuntu:latest
```

### PR DESCRIPTION
**Pull request by WestleyK**
# Now will fail if the user tried to remote build a sandbox container.

<br>

## Before This PR:

```
$ singularity build --remote --sandbox foo.sif library://alpine:3.8
Getting image source signatures
[...]
INFO:    Creating SIF file...
INFO:    Build complete: /tmp/image-242422562
INFO:    Now uploading /tmp/image-242422562 to the library
 26.69 MiB / 26.69 MiB  100.00% 31.69 MiB/s 0s
INFO:    Setting tag latest
 26.69 MiB / 26.69 MiB [=========================================================================================================================================] 100.00% 3.27 MiB/s 8s
```
The build will succeed, and does **Not** produce a sandbox container.

<br>

## After This PR:

```
$ singularity build --remote --sandbox foo.sif library://alpine:3.8
FATAL:   Unable to create build: Can't remote build a sandbox container.
```

The build will fail, Not producing any container.

<br>

## This fixes or addresses the following GitHub issues:

- Fixes #2415 

<br>

**NOTE:** This is most likely a temporary fix, until it is possible to remote build a sandbox container.

<br>

### CODE REVIEW

**Review by GodloveD — CHANGES_REQUESTED** [review]
This is one approach.  But I think it would be better if Singularity built a sif remotely, downloaded, and then dumped the contents out into a sandbox for the user when these options are specified.

**Comment by WestleyK** [comment]
That makes sense.
It will probably be better if someone smarter does this... but, I'll see what I can do...

**Comment by bauerm97** [comment]
@GodloveD Unfortunately, I don't think that's possible to do in a secure way without root. That sort of limits the usefulness of building remotely. In my opinion, we shouldn't try to workaround this option and should proceed with @WestleyK 's PR as is.

**Comment by jmstover** [comment]
@bauerm97 ... Would take a bit more logic included, but can't we get the offset of the Squashfs image in the SIF file and use unsquashfs?

Right now if a 2.x image is used as the source, it gets offset ~32 bytes to get rid of the `run-singularity` header. For a SIF image, we'd actually need to get what the offset is then use unsquashfs.

**Review by jscook2345 — APPROVED** [review]

**Comment by jscook2345** [comment]
@WestleyK @GodloveD After this is merged we should add some issues to both document and test for this.

**Comment by gmkurtzer** [comment]
I'm pretty certain we /can/ do this as non-root, but I'm not sure that we should. I concur with @WestleyK's and @bauerm97's initial assessment.

**Pull request merged**
