### PR TITLE
Fixes use of --pwd with --contain

### PR DESCRIPTION
**Pull request by hcraT**
As reported in #1208 when `--contain` is specified the --pwd option is not honored. This patch fixes the problem.

**Description of the Pull Request (PR):**

The solution adopted in the patch is simple. I simply moved the if branch that checkes if a target path is specified by the user as first. With this change if `--pwd` is specified the user requested path is set if `--contain` is present in the command line the path is set to the user home and if no either option is present the folder is set to the current directory.

**This fixes or addresses the following GitHub issues:**

- Ref: #1208 

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [ ] I have tested this PR locally with a `make test`
- [ ] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Review by gmkurtzer — APPROVED** [review]
Oh wait, I didn't realize this was to master... Can this be rebased to the development branch please?

**Review by GodloveD — APPROVED** [review]
I can confirm that this works.  Looks good to me as well. 

But yeah.  It needs to be against development not master.

**Comment by ArangoGutierrez** [comment]
hey @hcraT can you re submit this Pull request against the `development` branch in order to be merged?
thanks !

**Comment by hcraT** [comment]
Yes, sorry. I was busy today.

Tomorrow I should be able to make it.


On Jan 18, 2018 22:30, "Eduardo Arango" <notifications@github.com> wrote:

hey @hcraT <https://github.com/hcrat> can you re submit this Pull request
against the development branch in order to be merged?
thanks !

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/singularityware/singularity/pull/1226#issuecomment-358787986>,
or mute the thread

**Comment by ArangoGutierrez** [comment]
@hcraT no problem, your contribution is important. 
let me know if you need help on the re-submit

**Pull request closed without merging**
