### PR TITLE
Loopback changes

### PR DESCRIPTION
**Pull request by locula**
## Description of the Pull Request (PR):

This PR mainly changes the way that a new loopback device is found. Instead of going through all of the loopback devices one by one and checking if each one is free, we now use the function LOOP_CTL_GET_FREE to find a new loopback device. If the device found can't be opened, then we will repeat the process to find another free loop device and continue until we find one that we can use. 
We also change the maximum number of loop devices from 256 to 10,000 and fix a bug that makes the host become unresponsive after allocating a large number of loop devices.

### This fixes or addresses the following GitHub issues:

 - Fixes #

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by dtrudg** [comment]
Hi @locula - I just saw this PR appear and closed in a short timescale. If you would like to pursue this could you please open an issue for discussion of changes to the loop device code?

We don't use `LOOP_CTL_GET_FREE` because we still work on distributions with older kernels than `3.1`, when it appeared.

Also, the shared loop device functionality isn't something that would be removed without discussion, as it was added as a useful feature for people running a lot of instances of the same container on large machines.

Thanks!

**Review by dtrudg — CHANGES_REQUESTED** [review]
Hi @locula - please could you open an issue, or issues, describing how the current behaviour is limiting, and to provide a venue for discussion. As in the comment above there are concerns around kernel version compatibility, utility of the shared loop device code etc.

**Comment by locula** [comment]
The tests are currently failing because this fix does not take into account shared loop devices. We will revisit this PR once we have updated the code to allow for shared loop devices.

**Comment by DrDaveD** [comment]
At this point this is quite stale.  Please open a new PR when you're ready.

**Pull request closed without merging**
