### PR TITLE
group.c - handle ENOENT from getgrgid

### PR DESCRIPTION
**Pull request by dtrudg**
**Description of the Pull Request (PR):**

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

**This fixes or addresses the following GitHub issues:**

- Ref: #1303 

**Checkoff for all PRs:**

- [X] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [X] I have tested this PR locally with a `make test`
- [X] This PR is NOT against the project's master branch
- [X] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [ ] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by GodloveD** [comment]
@paulo7777 and @sylabskeith, can you guys test this or have it tested plz? 😺

**Review by GodloveD — APPROVED** [review]
I'm happy to approve this PR pending testing by someone with the appropriate environment.

**Comment by dtrudg** [comment]
@cclerget or @yhcote - would you be able to confirm if this small change makes sense to you?

The PR aims to fix #1303 by adding handling of ENOENT which is a listed possible return in the man page for `getgrgid`

@GodloveD - if approved I'm inclined to suggest merging it so it goes into 2.5, as I am fairly confident it will fix the issue with the dynamic groups on UGE reported for the particular system without adverse effect elsewhere.

**Comment by cclerget** [comment]
@dctrud `man getgrgid` mention `0 or ENOENT or ESRCH or EBADF or EPERM` for gid which doesn't exists, that makes sense to handle those errors correctly like you did

**Review by ctmadison — APPROVED** [review]

**Comment by unode** [comment]
Hi guys, https://groups.google.com/a/lbl.gov/forum/#!topic/singularity/KcbKBRigpNQ seems related.
Is this another use-case not covered by this pull request?

**Pull request merged**
