### PR TITLE
3.0: fix compilation on RHEL6 and RHEL7

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

This PR makes the master branch compile on RHEL6 and RHEL7.  Without it, compilation dies with these messages:
```
GO singularity
# github.com/singularityware/singularity/src/pkg/util/user
../src/pkg/util/user/identity.go:79: cannot use C.uid_t(uid) (type C.uid_t) as type C.__uid_t in argument to _C2func_getpwuid
../src/pkg/util/user/identity.go:114: cannot use C.gid_t(gid) (type C.gid_t) as type C.__gid_t in argument to _C2func_getgrgid
make: *** [singularity] Error 2
```

**This fixes or addresses the following GitHub issues:**

None

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is against the project's master branch
- [x] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by jscook2345** [comment]
Thanks for the contribution @DrDaveD!

It appears the code here was originally meant to support the usage of musl-libc as an alternative to glibc. Here is the commit where the change went in: 

https://github.com/singularityware/singularity/pull/1846/commits/ca5fb96d8bfdd397030f6b5a5a28ef95cfe341bd

While I think the fix you provided *should* work for both libc and musl-libc (since the *_defined macro will never be defined for a musl-libc system) I think it would be a good idea to be more verbose here.

Perhaps it would be better to enclose the current section in an ifdef checking for GLIBC? Those typedefs do not appear to be needed so they can be ignored.

#ifndef __GLIBC__
...
#endif

What do you think?

**Comment by DrDaveD** [comment]
That does seem to be less hacky than my approach, but I really don't know.  Let me know if you want me to update the PR.

**Comment by bauerm97** [comment]
@DrDaveD Hey Dave, thanks for diving into 3.0 and helping out. It's greatly appreciated! Unfortunately, we're not sure that there's a great way to make a "non-hacky" cross-distro solution to wrapping the `C.getpwuid` function call. I think @cclerget is going to rework this package to instead wrap the functions implemented in the Go standard library `os/user` package. @cclerget has [submitted a pull request](https://github.com/singularityware/singularity/pull/1852) implementing this change, would you be able to test that and see if it resolves this issue?

**Comment by DrDaveD** [comment]
I tested it on el6 and it got a different compilation error.  I will post the results in the PR.

**Comment by bauerm97** [comment]
Fixed by #1852

**Pull request closed without merging**
