### PR TITLE
Fix starter.c error message typo

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

Fixes a typo in a starter.c error message:
```
Cant' open /proc/self/auxv
```

**This fixes or addresses the following GitHub issues:**

- None

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by jchavezlavalle — APPROVED** [review]

**Comment by bauerm97** [comment]
@DrDaveD For some reason, CircleCI isn't running the build. I'm going to try closing and re-opening the PR to see if that kicks it into gear

**Review by mem — APPROVED** [review]

**Comment by bauerm97** [comment]
@DrDaveD I do approve of these changes, and I'd like to get this merged. However, I also think we need to figure out why exactly Circle is refusing to run the test suite here. One suggestion from @mikegray is that if you have somehow set up Circle with your own account on your fork there may be an issue, have you done anything like that?

**Comment by DrDaveD** [comment]
@bauerm97 Indeed I did set it up on my singularity fork.   [Here are the commits](https://github.com/DrDaveD/singularity/commits/fix-starter-typo) on this branch.  Indeed it failed running the [macos check](https://circleci.com/gh/DrDaveD/singularity/611?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link) on this branch.  That gives a message "Sorry! Your build didn't run because it looks like you haven't selected a macOS plan yet. "

**Comment by bauerm97** [comment]
@DrDaveD Ugh sorry man. I'm not sure what we can do to fix this and get Circle running again. It *should* still be running when you submit a pull request.... @jscook2345 do you have any insight here into CircleCI and what we can do to fix this?

**Pull request merged**
