### PR TITLE
Fix bad pull library URI variable introduces during CLI refactoring

### LINKED ISSUE #3815: Pull with Library Broken in 3.2.1
## Version of Singularity:

3.2.1

### Expected behavior

For 3.1, I could pull a container from a custom library (here I am pulling with the singularity Docker image for previous version 3.1):

```bash
$ docker run -it singularityware/singularity:3.1-slim --debug pull --library https://xxxxxxxxxxx collection/container:shadoop
Unable to find image 'singularityware/singularity:3.1-slim' locally
3.1-slim: Pulling from singularityware/singularity
48ecbb6b270e: Pull complete 
2ceaa3199c9d: Pull complete 
d653269fbd57: Pull complete 
Digest: sha256:5253c519697a1489d0bf98c8f3fedefba6beb97e17014a00d4e5e6bda631b59e
Status: Downloaded newer image for singularityware/singularity:3.1-slim
WARNING [U=0,P=1]          sylabsToken()                 Authentication token file not found : Only pulls of public images will succeed
DEBUG   [U=0,P=1]          apiGet()                      apiGet calling https://xxxxxxxxxxxxxx/v1/images//collection/container:shadoop
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /root/.singularity/cache
DEBUG   [U=0,P=1]          initCacheDir()                Creating cache directory: /root/.singularity/cache/library/sha256.a904e546638a8778d1c89c79d721aec76bd315b882a253df6875aa0b5f0ec637
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library/sha256.a904e546638a8778d1c89c79d721aec76bd315b882a253df6875aa0b5f0ec637
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library/sha256.a904e546638a8778d1c89c79d721aec76bd315b882a253df6875aa0b5f0ec637
DEBUG   [U=0,P=1]          updateCacheSubdir()           Caching directory set to /root/.singularity/cache/library
INFO    [U=0,P=1]          pullRun()                     Downloading library image
DEBUG   [U=0,P=1]          DownloadImage()               Pulling from URL: https://xxxxxxxxxxxxxx/v1/imagefile/collection/container:shadoop
DEBUG   [U=0,P=1]          DownloadImage()               OK response received, beginning body download
DEBUG   [U=0,P=1]          DownloadImage()               Created output file: /root/.singularity/cache/library/sha256.a904e546638a8778d1c89c79d721aec76bd315b882a253df6875aa0b5f0ec637/container_shadoop.sif
 764.00 KiB / 764.00 KiB [=====================================================================================] 100.00% 7.93 MiB/s 0s
DEBUG   [U=0,P=1]          DownloadImage()               Download complete

```

### Actual behavior

And now with 3.2.1, I cannot:

```bash
$ singularity --debug pull --library https://xxxxxxxxxxxxxx collection/container:shadoop
DEBUG   [U=1000,P=12506]   createConfDir()               /home/vanessa/.singularity already exits. Not creating.
FATAL   [U=1000,P=12506]   pullRun()                     While pulling library image: image does not exist in the library: collection/container:shadoop
```

What changed?

### PR DESCRIPTION
**Pull request by cclerget**
**Description of the Pull Request (PR):**

As title

**This fixes or addresses the following GitHub issues:**

- Fixes #3815

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by Flamefire** [comment]
Any chance you can come up with a test for this? This slipping through during refactoring indicates missing test coverage.

**Comment by cclerget** [comment]
> Any chance you can come up with a test for this? This slipping through during refactoring indicates missing test coverage.

Sure, done

**Review by ikaneshiro — APPROVED** [review]
lgtm

**Review by WestleyK — APPROVED** [review]
Looks good to me! Thanks :+1:

**Pull request merged**
