### PR TITLE
removing bootstrap and definition from help

### PR DESCRIPTION
**Pull request by GodloveD**
subject says it all.

Attn: @singularityware-admin

### CODE REVIEW

**Comment by vsoch** [comment]
Looks good to me!  Alas bootstrap, ye shall be missed.

image

but maybe not. Build sounds a lot cooler!

**Comment by vsoch** [comment]
question for @gmkurtzer and @GodloveD are we good to start PRing to development again, and it's version 2.4+ something? Or should we still wait?

**Comment by gmkurtzer** [comment]
@vsoch Almost ready to start merging to development. Let's wait until release announcement goes out.

Thanks!

**Comment by GodloveD** [comment]
@gmkurtzer @vsoch This is a pretty trivial change.   If neither of you mind I will just merge.

**Comment by vsoch** [comment]
bwaahah

**Comment by vsoch** [comment]
*diabolical*

**Comment by GodloveD** [comment]
Feels good doesn't it.  lol

**Pull request merged**
