### PR TITLE
Improved documentation for 'pull'

### LINKED ISSUE #3955: document return value of 10
While reviewing the e2e pull tests, I noticed the following which @gvallee commented on here:

https://github.com/sylabs/singularity/pull/3942#discussion_r305502821

Could we document the use of the return value `10` somehow or replace it with a enum? I would like it to be easier to understand why the value `10` is returned. ex: Is there a special meaning for this somewhere else I don't know about?

Thanks!

### LINKED ISSUE #4119: Pulling from http, https protocol is not documented
### Version of Singularity:

```
3.3.0
```

### Expected behavior

Pulling from http, https protocol is documented in the `singularity pull --help`.

### Actual behavior

No documentation on pulling from http, https protocol, (at least I did not see any)

### Steps to reproduce behavior

Run `singularity pull --help`, then try and guess how to pull a image from https protocol.

### PR DESCRIPTION
**Pull request by WestleyK**
## Description of the Pull Request (PR):

This PR imporves/adds documentation for the:
 - exit code from 'pull' when pulling a unsigned container
 - pulling from http, https protocol

### This fixes or addresses the following GitHub issues:

- ~Fixes #3955~
- Fixes #4119

<br>

### CODE REVIEW

**Review by gvallee — DISMISSED** [review]
Unfortunately, I believe this is in contradiction with change in #4120 where exit codes are changed. We need to have agreement about that and when a given exit code is supposed to be returned and make sure the implementation complies.

**Comment by WestleyK** [comment]
Thanks @gvallee, once https://github.com/sylabs/singularity/pull/4124 is updated I'll remove the exit code documentation in this PR, so my PR will just add documentation for http, and https.

**Comment by ikaneshiro** [comment]
The pr is now #4167

**Comment by sashayakovtseva** [comment]
@WestleyK Please, update branch since #4167 is already merged

**Review by sashayakovtseva — APPROVED** [review]

**Pull request merged**
