### PR TITLE
updating scif-revision to be against development-2.x branch

### PR DESCRIPTION
**Pull request by vsoch**
**Description of the Pull Request (PR):**

This is a rebase of PR #1272 . This should *not* be merged until the work here https://github.com/singularityware/singularity/pull/1238/files that is not existing in the current development-2.x is properly added back. It will not work without that. The function has been updated but the rest of the code base is not, as it was already pull requested, reviewed, and merged with a previous version of singularity (that looks like it's now gone?) :( 

Attn: @singularityware-admin

### CODE REVIEW

**Comment by dtrudg** [comment]
Hi @vsoch - would it be okay with you if I pulled out the change so it is not dependent on #1272 ?

I believe it just needs the following on current codebase:

```diff
-        app=(`echo $app | sed -e "s/-/_/g"`)
+        app=(`echo $app | sed -e "s/-/_/g" | sed -e "s/[.]/_/g"`)
```

#1272 is something we've identified as being merged into development, but not present on the release branches. The concern on pulling that change for 2.5 is that is changes all the environment namings, so there is likely a fair amount of doc change to do with it, that might delay a release of the whiteout things etc. Maybe we could target that as a 2.6 instead?

Let us know how you feel about this. Thanks.

**Comment by vsoch** [comment]
Making only this change does not conform to the SCIF specification. You are breaking the specification and people's build recipes if you don't. Here is the specification, for detail about the namespace:

https://sci-f.github.io/spec-v1#environment-namespace

All of these are changes that were previously integrated into Singularity, and I hope that the work that I put into that isn't just... erased?  The paper is accepted, and will be published any day, and readers will expect to be able to use SCIF natively with Singularity. I put great effort into making this happen, had done several PRs to do these changes already, and it doesn't seem fair that my options are to do it at all again, or do nothing and have Singularity look bad. I don't know what is going on over there, but please make sure that the work that I already put into this is properly integrated back into the code base. If it takes a little longer, this is still the right thing to do. This is good and fair practice, I think.

**Review by dtrudg — APPROVED** [review]
This looks good to me as a fix for the reported issue, but would it be better long term to check in SCIF things that app names (after substitutions) are [a-zA-Z_]+[a-zA-Z0-9_]*  which is the POSIX requirement for env-vars. That could give a more specific error upstream.

**Comment by vsoch** [comment]
oh I didn't know that! That is indeed a good idea. :)

**Review by GodloveD — APPROVED** [review]
This looks fine to me as well.

**Comment by GodloveD** [comment]
Thanks @vsoch!

**Comment by vsoch** [comment]
And thank you @GodloveD and @dctrud ! :hugs:

**Pull request merged**
