### PR TITLE
Fixed typo in image.import example

### PR DESCRIPTION
**Pull request by mimame**
Fixed typo in image.import example

**Checkoff for all PRs:**

- [X] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [ ] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [ ] I have tested this PR locally with a `make test`
- [X] This PR is NOT against the project's master branch
- [ ] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [X] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Review by ArangoGutierrez — APPROVED** [review]

**Comment by ArangoGutierrez** [comment]
Good Catch!
---
```bash
  -c, --stdout      write on standard output, keep original files unchanged
  -d, --decompress  decompress
  -9, --best        compress better
```
I think is good to go.
Let's wait for @GodloveD  review

**Comment by vsoch** [comment]
I don't think this is necessarily a typo, the choice of level is subjective, right? I always use the 9 as the highest level of compression. It's largely up to the user to decide on the exact level, but in the example I think the 9 is ok to encourage slightly slower for a higher level. @ArangoGutierrez why do you think it's a typo?

**Comment by ArangoGutierrez** [comment]
Because the examples are for image importing coming from a stdout
```bash
EXAMPLES:
  
      $ singularity image.import /tmp/Debian.img < /tmp/Debian.tar
      $ gzip -9 > Debian.tar.gz | singularity image.import /tmp/Debian.img
      $ tar -cvf - -C data_dir/ . | singularity image.import /tmp/data.img
```
the `-9` flag would apply on a export example.

**Review by GodloveD — APPROVED** [review]
Yes, nice catch.  Thank you.

**Pull request merged**
