### PR TITLE
Fix intermittent failures of docker api tests

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

This PR removes some forcing of 'old_version=True' on calls to the python docker api call get_manifest().  They were causing intermittent failures on travis because of a mismatch on the 'Accept' header.   The log output contained the following:
```
VERBOSE Obtaining manifest: https://gcr.io/v2/tensorflow/tensorflow/manifests/latest
DEBUG GET https://gcr.io/v2/tensorflow/tensorflow/manifests/latest
DEBUG Http Error with code 404
ERROR MANIFEST_UNKNOWN: Manifest with tag 'latest' has media type
'application/vnd.docker.distribution.manifest.v2+json', but client accepts 'application/json'.
```
I was able to reproduce it on my EL7 VM about 95% of the time, and after this patch it passed many repeats of the test.

**This fixes or addresses the following GitHub issues:**

None, discussed on slack devel channel.

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [x] I have added myself as a contributor to the [Author's file](https://github.com/singularityware/singularity/blob/master/AUTHORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by bauerm97** [comment]
@gmkurtzer Please merge, these failures are so annoying.

Thank you so much for this fix

**Comment by gmkurtzer** [comment]
We have a minor conflict with @vsoch's PR that just got merged too. Can that be resolved?

Thanks!

**Comment by vsoch** [comment]
Note that I addressed this with my PR - it removes the redundant tests (we were doing both ubuntu and tensorflow, and it's probably overkill)

**Comment by DrDaveD** [comment]
Ok so I merged the current development branch which removed one of the places I had fixed.  I have been running the unit test repeatedly on my machine with just that patch and haven't seen it fail.  However I have seen travis failures from the remaining place as well (e.g. [this one](https://travis-ci.org/singularityware/singularity/jobs/283242704#L4296)) so I think this remaining one might as well be included too.

**Comment by gmkurtzer** [comment]
So should we merge both? @vsoch, thoughts?

**Comment by vsoch** [comment]
The fail doesn't have the fix. I say don't test here further until we are convinced there is still issue.

**Comment by GodloveD** [comment]
Are these changes still necessary?  We are still having a ton of Travis build failures, but as @olifre points out in comments on https://github.com/singularityware/singularity/pull/1093 these errors are on the Travis/Docker Hub end and not due to our setup.

https://www.traviscistatus.com/incidents/v4jnp6nkgzqx

**Comment by vsoch** [comment]
This doesn't make sense to merge. If the manifestv1 is None, we want to ask the API for it. Removing "old_version=True" doesn't ask for a specific version, it returns the wrong thing.

**Comment by olifre** [comment]
@GodloveD The issue I referred to is now also acknowledged upstream:
https://status.docker.com/pages/incident/533c6539221ae15e3f000031/59f1da512cd214649ebc33b0
and is an infrastructure issue on the DockerHub end triggered mainly for large layers. Also, this is only happening since 1-2 days. 

So I think it's a different issue from the one discussed here, sadly also causing travis failures.

**Comment by vsoch** [comment]
it's always the fat layers...

**Comment by DrDaveD** [comment]
@vsoch says it's not needed, I believe her, closing request.

**Comment by GodloveD** [comment]
Thanks @DrDaveD!

**Pull request closed without merging**
