### PR TITLE
Update deprecated links

### PR DESCRIPTION
**Pull request by mwiens91**

### CODE REVIEW

**Review by jmstover — CHANGES_REQUESTED** [review]
Thanks!  Can you rebase off of `development-2.x` ?

**Comment by mwiens91** [comment]
@jmstover Done.

**Comment by jmstover** [comment]
Ack....   You're still basing this on `master` ... 

```
mwiens91 wants to merge 192 commits into singularityware:master from mwiens91:update-deprecated-links
```

**Comment by mwiens91** [comment]
@jmstover Oops. Thanks for pointing that out.

**Review by jmstover — APPROVED** [review]

**Comment by jmstover** [comment]
@mwiens91 
Thanks much.

@GodloveD ... note here.

**Pull request merged**
