### PR TITLE
Make ReST docs use :ref:

### PR DESCRIPTION
**Pull request by multimeric**
**Description of the Pull Request (PR):**

This is a fix to the PR #2617, which introduced ReST (restructured text) documentation generation. This PR worked correctly, but it generated ReST that wasn't optimized for Sphinx, the documentation builder used by Singularity. In particular, it didn't use the `:ref:` directive for documentation cross-references, meaning that it generated ReST like this, where the links didn't work correctly:

```
SEE ALSO
~~~~~~~~

* `singularity apps <singularity_apps.rst>`_ 	 - apps <image path>
* `singularity build <singularity_build.rst>`_ 	 - Build a new Singularity container
* `singularity capability <singularity_capability.rst>`_ 	 - Manage Linux capabilities on containers
* `singularity exec <singularity_exec.rst>`_ 	 - Execute a command within container
```

This PR fixes this issue, following the method described [here](https://github.com/spf13/cobra/blob/master/doc/rest_docs.md#customize-the-output). The ReST we generate now looks like this:

```
SEE ALSO
~~~~~~~~

* :ref:`singularity apps <singularity_apps>` 	 - apps <image path>
* :ref:`singularity build <singularity_build>` 	 - Build a new Singularity container
* :ref:`singularity capability <singularity_capability>` 	 - Manage Linux capabilities on containers
* :ref:`singularity exec <singularity_exec>` 	 - Execute a command within container
```

### CODE REVIEW

**Comment by jmstover** [comment]
@devprincess ... This looks okay to me, but I don't have the background on the RST side that you do.

**Comment by multimeric** [comment]
Some things the reviewer might want to consider are:

* Have I done the correct thing by having a function that returns `""` to try and bypass the `filePrepender` argument? (the third argument to `GenReSTTreeCustom`)
* Should I make the `:ref:` syntax configurable with a boolean argument to the `rstDocs` function?

**Review by bauerm97 — APPROVED** [review]
@TMiguelT this actually LGTM in it's current state. I don't mind the fact that having this output format isn't optional, since our only use of this command should require that syntax. Also, your use of the prepend function seems fine to me here.

**Comment by multimeric** [comment]
Excellent, thanks for the merge! This should let me submit the final PR for automatic CLI documentation

**Pull request merged**
