### PR TITLE
Provide instructions for installing golangci-lint

### PR DESCRIPTION
**Pull request by mem**
Signed-off-by: Marcelo E. Magallon <marcelo@sylabs.io>

### CODE REVIEW

**Comment by DrDaveD** [comment]
My PR #2953 will make this unnecessary, as it always automatically installs if it isn't installed.

**Review by gvallee — APPROVED** [review]

**Comment by gvallee** [comment]
Note: the Travis error has nothing to do with the PR. I believe it is ready to merge.

**Comment by DrDaveD** [comment]
Someone please comment on why to do this instead of #2953

**Comment by mem** [comment]
I merged this one to document the fact that `make check` should be run locally, and to provide instructions as to how to install golangci-lint if the person wants to do it permanently. Dave's PR automates a temporary installation of golangci-lint, so that's a nice complement to this one.

**Pull request merged**
