### PR TITLE
Add travis checks for centos 6 and 7 rpms

### PR DESCRIPTION
**Pull request by DrDaveD**
**Description of the Pull Request (PR):**

This PR adds travisci checks for centos 6 and 7, building rpms and testing them.   I considered circleci for just building, but couldn't find any examples for centos. Instead I ported forward the checks from singularity-2.6 and adapted them for singularity-3.  I included some of the infrastructure for debian and opensuse but will leave it to other people to complete them.

**This fixes or addresses the following GitHub issues:**

None

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](../CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](../CHANGELOG.md) if necessary according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](../CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](../CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by DrDaveD** [comment]
There was a server timeout in travis build .  Closing & reopening to trigger rebuild.

**Comment by boegel** [comment]
Good to see that there's an effort to try and avoid that packaging Singularity in an RPM fails, especially given the recent problems reported in #2149, and caused by the changes in #2185, thanks @DrDaveD!

**Comment by DrDaveD** [comment]
There was another transient test error (Error reading blob from docker hub) after adding the use of the -B link option, so closing & reopening again.

**Comment by GodloveD** [comment]
Yes.  Thanks indeed @DrDaveD.  This is much needed.

ping @jmstover @ArangoGutierrez @jscook2345

**Comment by yhcote** [comment]
> Good to see that there's an effort to try and avoid that packaging Singularity in an RPM fails, especially given the recent problems reported in #2149, and caused by the changes in #2185, thanks @DrDaveD!

Hi @boegel, 

This is because #2185 was an effort to split builds for "normal release" including symbols and "rpm friendly stripping builds", configurations in an easy way. 

By looking at the -P : 

-P use config profile to configure the project:
           release             (DEFAULT) normal release mode (production)
           release-stripped    release mode, stripped symbols (rpm packaging)
           debug               C portion of CGO built unoptimized, with symbols

You see that doing "  ./mconfig -P release-stripped " would have created a configuration suitable for running the buildrpm script.

Does that make sense?

**Review by yhcote — APPROVED** [review]
Looks good to me.

**Pull request merged**
