### PR TITLE
make_suid fix for alpine linux

### PR DESCRIPTION
**Pull request by truatpasteurdotfr**
allow the abuild wrapper to chmod 4755 sexec-suid

### CODE REVIEW

**Comment by gmkurtzer** [comment]
If I remember correctly, I used to have it as this, but it was failing under some circumstances. Have you tested on different Centos versions too?

**Comment by gmkurtzer** [comment]
@truatpasteurdotfr ping

**Comment by truatpasteurdotfr** [comment]
pong :P 
it works for me on centos7 and centos6 build host compiling singularity 2.2.

**Comment by gmkurtzer** [comment]
Heya @truatpasteurdotfr, did you mean to close the PR? I'm happy to implement it as long as it doesn't break builds on other OSs. I seem to recall that I used to have it defined as such, and it didn't work for one reason or another somewhere, someplace.. but I really don't recall the reason right now. I could dig if necessary...

**Comment by truatpasteurdotfr** [comment]
my bad :P re-opening. If you have time I would also like to know  why the perms settings was pushed to the data hook instead of exec. :)

**Pull request merged**
