### PR TITLE
WiP ENH: try testing under different shells (to demo #187)

### PR DESCRIPTION
**Pull request by yarikoptic**
most probably wouldn't work right away -- just want to see what the effect would be atm

### CODE REVIEW

**Comment by gmkurtzer** [comment]
hrmm, I wonder why travis didn't test this PR...

**Comment by yarikoptic** [comment]
hm, indeed ... I will also enable travis for my clone then, although I think it should've not been needed

**Comment by yarikoptic** [comment]
actually it is enabled!  so don't know.  Let me rewrite the commit and push again, may be it was just a travis fluke of some kind

**Comment by bbockelm** [comment]
This PR is for branch `2.x`: is Travis only enabled for PRs against `master`?

**Comment by yarikoptic** [comment]
I think it is my changes syntax, let me redo it a bit.  in any case -- do not merge until it actually runs and passes! ;)

**Comment by yarikoptic** [comment]
it passed the tests :-/  which suggests that changing the shell wasn't in effect.  Should have failed per #187

**Comment by gmkurtzer** [comment]
@yarikoptic Are you ready for me to merge this, or are you still working on it?

**Comment by yarikoptic** [comment]
On Wed, 10 Aug 2016, Gregory M. Kurtzer wrote:

>    @yarikoptic Are you ready for me to merge this, or are you still working
>    on it?

since it doesn't demonstrate the bug, not sure if it is worth merging
ATM. feel free to close or take over (fix up so it reveals the bug if it
is there ;) )

**Comment by gmkurtzer** [comment]
The shell handling is different in the 'development' branch and this does not seem to still be an error. Additionally I have scripts in `tests/` that test for custom shells, so I think it should be good.

**Pull request closed without merging**
