### PR TITLE
Run E2E suites in parallel

### PR DESCRIPTION
**Pull request by mem**
Signed-off-by: Marcelo E. Magallon <marcelo@sylabs.io>

**Description of the Pull Request (PR):**

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

**This fixes or addresses the following GitHub issues:**

- Fixes #

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by mem** [comment]
Sorry about the misleading description: this is not running anything in parallel. This change causes the tests to run in unspecified order, which is the first step towards running them in parallel.

**Comment by jscook2345** [comment]
I want to run this locally and see how it works a bit.

**Review by jscook2345 — APPROVED** [review]

**Comment by gvallee** [comment]
There is no description for this PR but I am guessing based on the title. e2e tests are not right now thread-safe because of the image cache management so this is really not something safe to do :(

**Comment by jscook2345** [comment]
@gvallee 

See @mem's comment above. It just makes the tests run in an unspecified order. It does not add the parallel part yet. We'll make sure to wait on the image cache part before parallelizing.

**Comment by mem** [comment]
@gvallee what Justin said. Please see the commit message (not the PR description :man_shrugging:)

**Pull request merged**
