### PR TITLE
Fix RPM building with buildrpm script

### PR DESCRIPTION
**Pull request by jmstover**
**Description of the Pull Request (PR):**
This PR fixed a few of the RPM building issues with `dist/rpm/buildrpm`:
 * Fix `singularity.conf.in` 
 * Honor RPM macro values
 * Change install locations to appropriate Macro value (LOCALSTATEDIR, SYSCONFDIR, etc...)
 * Add DESTDIR for `make install`
 * Cleanup in `.spec.in` and makeit files

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by jmstover** [comment]
@DrDaveD
As you have an interest in this. This PR should make `buildrpm` work again, as well as honor RPM macros. It's a precursor patch to getting the build from dist tarball working.

**Comment by DrDaveD** [comment]
@jmstover this conflicts with my pr #2202 which fixes the rpm builds and enables travis builds for centos6 & 7.  Could you please review that one first?

**Review by yhcote — APPROVED** [review]
Looks tedious to me.

**Comment by yhcote** [comment]
@jmstover : I merged @DrDaveD PR #2202, Is there something that needs to be changed for this one to go in also?

Thanks.

**Comment by jmstover** [comment]
@yhcote I don't think there was anything here that conflicts with #2202. That was more CI stuff than anything else.

*Edit:*
If the setting of the ldflags in `go_normal_opts.mk` works as advertised, then `-P release-stripped` can be removed here. I'd like to keep it as an option though.

**Comment by DrDaveD** [comment]
@jmstover Please do remove the -P release-stripped from the singularity.spec.in.

**Comment by jmstover** [comment]
@DrDaveD I changed it... Once quick question... It _appears_ to do as advertised. Though my `ld` shows using:
```
--build-id=0x[blah]
```
as the way to set it, not `-B 0x[blah]` ... using `-B` like that isn't mentioned in the man page (just -Bstatic, -Bgroup, etc...). `GNU ld version 2.26.20160125` (Slackware)

Is `-B` usage like this actually valid, and it's not documented? `objdump -sj .note.gnu.build-id singularity` _does_ return a section... but I can only get `-Wl,--build-id=[blah]` to work when doing it manually.

**Comment by DrDaveD** [comment]
I thought at first it was ld too, but it isn't, it's go's own "link" program: https://golang.org/cmd/link/

**Comment by jmstover** [comment]
Sounds good. I thought they offloaded to ld as well after doing some initial manipulation. :+1:

**Pull request merged**
