### PR TITLE
Use fixed image offset of zero for SquashFS images

### PR DESCRIPTION
**Pull request by oschulz**
Backport of #431 to current release branch.

### CODE REVIEW

**Comment by gmkurtzer** [comment]
The more I think about this, the more I consider this is a bug in `singularity_image_offset()` as it should `return(0)` when there is no offset or when it is not a Singularity image. Can you check out what I did in lib-refactor, and see if you can do something similar here?

Thank you!

**Comment by oschulz** [comment]
Should be really fix this in different ways on master and on 2.x, though?

**Comment by gmkurtzer** [comment]
You are right, that it would be better if it wasn't.... But we aren't using the standard GitFlow process right now. With the 2.3 release, we will move to the standard GitFlow model, but for now, what is in lib-refactor is the basis for what will end up in development, and development will end up in master.

**Comment by oschulz** [comment]
Hi @gmkurtzer , I backported your elegant fix for the issue from lib-refactor to here (2.x). I gave it a quick test, seems to work fine. :-)

**Comment by oschulz** [comment]
I rebased this PR, it only contains your nice fix now, Greg (with a tiny change for 2.x).

**Comment by gmkurtzer** [comment]
Thanks!

Hrmm, looks like the busybox container download is failing again. I'm gonna override the CI failure and merge.

**Comment by oschulz** [comment]
Thanks!

**Pull request merged**
