### PR TITLE
Run E2E suites in parallel

### PR DESCRIPTION
**Pull request by mem**
Signed-off-by: Marcelo E. Magallon <marcelo@sylabs.io>

**Description of the Pull Request (PR):**

Write your description of the PR here. Be sure to include as much background,
and details necessary for the reviewers to understand exactly what this is
fixing or enhancing.

**This fixes or addresses the following GitHub issues:**

- Fixes #

**Before submitting a PR, make sure you have done the following:**

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Comment by jscook2345** [comment]
Need to merge something with the cache work (per @gvallee) before we can merge this.

**Review by sashayakovtseva — APPROVED** [review]

**Comment by jscook2345** [comment]
@mem 

Looks like there are some conflicts that need to be addressed.

**Comment by mem** [comment]
> @mem
> 
> Looks like there are some conflicts that need to be addressed.

I might try to upload another version just to see what happens.

Some of the (current) issues are tests stepping on each other's toes because they are working on the same test directory.

A balance is needed between a clever way to fix this and one that allows people to debug issues when they happen.

**Comment by cclerget** [comment]
Follow up in #4825

**Pull request closed without merging**
