### PR TITLE
Fix build post section issue /etc/resolv.conf and/or /etc/hosts are missing

### LINKED ISSUE #4969: build for some docker containers fails with simple `%post` in definition file
### Version of Singularity:

What version of Singularity are you using? Run:

```
$ singularity version
3.5.2
```

### Expected behavior

Building from a biocontainer docker container using a def file to make modifications should work:

```
$ cat > test.def <<'EOF'
BootStrap: docker
From: quay.io/biocontainers/deepvariant:0.9.0--py27h7333d49_0

%post
    echo "test"
EOF
$ sudo singularity build test.sif test.def
```

### Actual behavior

The build fails if there is a `%post` section , but it succeeds if there is not:

```
$ sudo singularity --debug build test.sif test.def
...
DEBUG   [U=0,P=16276]      CreateContainer()             Mounting /dev at /usr/local/var/singularity/mnt/session/rootfs/dev
DEBUG   [U=0,P=16276]      CreateContainer()             Mounting /usr/local/var/singularity/mnt/session/resolv.conf at /usr/local/var/singularity/mnt/session/rootfs/etc/resolv.conf
FATAL   [U=0,P=16276]      Master()                      container creation failed: mount /usr/local/var/singularity/mnt/session/resolv.conf failed: no such file or directory
DEBUG   [U=0,P=16219]      cleanUp()                     Cleaning up "/tmp/rootfs-25687a0e-3e0a-11ea-918a-42010a800002" and "/tmp/bundle-temp-527084539"
FATAL   [U=0,P=16219]      runBuildLocal()               While performing build: while running engine: while running /usr/local/libexec/singularity/bin/starter: exit status 255
```

Without the `%post` section, the same build succeeds

```
$ cat > test.def <<'EOF'
BootStrap: docker
From: quay.io/biocontainers/deepvariant:0.9.0--py27h7333d49_0
EOF
$ sudo singularity build test.sif test.def
...
INFO:    Creating SIF file...
INFO:    Build complete: test.sif
```

### Steps to reproduce this behavior

see above

### What OS/distro are you running

```
$ cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

### How did you install Singularity

compiled from release tarball with go 1.13.5

### PR DESCRIPTION
**Pull request by cclerget**
## Description of the Pull Request (PR):

Fix build post section issue if `/etc/resolv.conf` and/or `/etc/hosts` are not missing or are dangling symlinks

### This fixes or addresses the following GitHub issues:

 - Fixes #4969 

#### Before submitting a PR, make sure you have done the following:

- Read the [Guidelines for Contributing](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- Added changes to the [CHANGELOG](https://github.com/sylabs/singularity/blob/master/CHANGELOG.md) if necessary according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added tests to validate this PR and tested this PR locally with a `make testall`
- Based this PR against the appropriate branch according to the [Contribution Guidelines](https://github.com/sylabs/singularity/blob/master/CONTRIBUTING.md)
- Added myself as a contributor to the [Contributors File](https://github.com/sylabs/singularity/blob/master/CONTRIBUTORS.md)

Attn: @singularity-maintainers

### CODE REVIEW

**Review by dtrudg — APPROVED** [review]
LGTM :+1:

**Comment by pcm32** [comment]
Would this fix apply when running like this?

```
singularity shell docker://quay.io/biocontainers/wget:1.20.1
INFO:    Using cached SIF image
WARNING: Skipping mount /var/singularity/mnt/session/etc/resolv.conf [files]: /etc/resolv.conf doesn't exist in container
Singularity> ping www.google.com
ping: bad address 'www.google.com'
Singularity> cd /etc/
Singularity> ls -ltr
total 41
-rw-rw-r--    1 root     root         10873 Feb 27  2014 services
-rw-rw-r--    1 root     root           386 Feb 27  2014 securetty
lrwxrwxrwx    1 root     root            18 Feb 27  2014 resolv.conf -> ../tmp/resolv.conf
```

I'm running:
```
singularity version
3.6.4-1.el7
```

which I would guess would contain the fix in this PR.

**Comment by dtrudg** [comment]
@pcm32 - no, this fix was to address _builds_ that fail when `/etc/resolv.conf` is not present, or is a dangling symlink. It won't fix that skipped mount on `shell` that you see.

The fact that `/etc/resolv.conf` links to `/tmp/resolv.conf` means that it will be hidden when singularity mounts `/tmp`. However, in the upcoming 3.7 you will be able to now disable this `/tmp` mount, via `--no-mount tmp`, which offers a workaround for containers that have this strange link:

```
dave@ythel~/G/singularity> clear
dave@ythel~/G/singularity> /usr/local/bin/singularity shell --no-mount tmp docker://quay.io/biocontainers/wget:1.20.1
INFO:    Using cached SIF image
Singularity> ping google.com
PING google.com (216.58.193.142): 56 data bytes
```

I don't really understand why a container would link an important system file like `resolv.conf` into `/tmp` - I'd advise running a build with a definition that replaces `/etc/resolv.conf` as a normal file.

**Comment by pcm32** [comment]
Thanks @dctrud ! Is there a workaround I could use with 3.6 to make this work or is 3.7 being released shortly?

**Comment by dtrudg** [comment]
@pcm32 - a release candidate for 3.7.0 will come out later today. There will be a a couple/few weeks testing, completing documentation and so on before it is a stable release version.

**Pull request merged**
