### PR TITLE
fixes for v3.3.0-rc.2 

### PR DESCRIPTION
**Pull request by GodloveD**
**Description of the Pull Request (PR):**

cherry-pick the following PRs to get ready for 3.3.0-rc.2

#3791
#3749
#3796
#3759
#3696
#3780
#3825

Attn: @singularity-maintainers

### CODE REVIEW

**Review by cclerget — CHANGES_REQUESTED** [review]
Just to be sure to not forget it, this one https://github.com/sylabs/singularity/pull/3803 will be also required once approved.

**Comment by jscook2345** [comment]
@GodloveD Looks like #3803 has been merged and can be included here now.

**Review by jscook2345 — DISMISSED** [review]
Approve pending addition of #3803

**Comment by GodloveD** [comment]
@jscook2345 it's been suggested that we also include the following:

#3758
#3782 
#3803 
~#3290~
#3889
~#3395 open~
~#3789 open~
~#3793 open~

EDIT: After consultation with @jscook2345 have decided to cross out some of the backports.

**Comment by jscook2345** [comment]
@GodloveD Several of those will add significant test time, pending documentation provided. How long will we have to test before we want to release the rc?

**Comment by ikaneshiro** [comment]
@jscook2345 another regression found and soon to be fixed here: https://github.com/sylabs/singularity/pull/3897

**Comment by GodloveD** [comment]
Also added #3897 I think this is good to go now @jscook2345 and @cclerget.  Want to give this a second look?

**Comment by GodloveD** [comment]
Think we also need to address #3892 before merging this.

**Comment by cclerget** [comment]
#3926 fix for #3892 (but need confirmation from @Zohman)

**Review by cclerget — APPROVED** [review]

**Pull request merged**
