### PR TITLE
Check GID in 45-targetmode.sh

### PR DESCRIPTION
**Pull request by jmstover**
**Description of the Pull Request (PR):**

Check GID in `tests/45-targetmode.sh` to see if we have a GID >= 1000.  Skip test if we have a primary GID < 1000.

**Checkoff for all PRs:**

- [x] I have read the [Guidelines for Contributing](https://github.com/singularityware/singularity/blob/master/CONTRIBUTING.md), and this PR conforms to the stated requirements.
- [] I have added changes to the [CHANGELOG](https://github.com/singularityware/singularity/blob/development/CHANGELOG.md) and and documentation updates to the [singularityware](https://www.github.com/singularityware/singularityware.github.io) documentation base.
- [x] I have tested this PR locally with a `make test`
- [x] This PR is NOT against the project's master branch
- [] I have added myself as a contributor to the [contributors's file](https://github.com/singularityware/singularity/blob/master/CONTRIBUTORS.md)
- [x] This PR is ready for review and/or merge

Attn: @singularityware-admin

### CODE REVIEW

**Comment by GodloveD** [comment]
Just for the record this allows tests to pass on SLES where the default gid for a new user is like 500 or something.

**Review by GodloveD — APPROVED** [review]
This works.

**Review by dtrudg — APPROVED** [review]
This works  for me when I setup <1000 - but before merge could you comment on exactly what we are losing in the test that don't run?

**Comment by jmstover** [comment]
The test does something like:

```
SINULARITY_TARGET_GID=99 SINGULARITY_TARGET_UID=99 singularity exec $CONTAINER whoami
```
If those are set, then when the user information is set in `src/util/privlege.c`  it uses the value requested. This is used on some schedulers where jobs are submitted as one user, but run as a different user. The tests just verify that that the target_gid/uid is what is seen when the container runs.

**Comment by dtrudg** [comment]
@jmstover - thanks, I'd read it as that but hadn't seen it used in the wild so wanted confirmation. Think this looks good for you to merge.

**Pull request merged**
